import type { Express, Request, Response } from 'express';
import type { AuthenticatedPrincipal } from './auth';
import { CreditCardStatementAuthority, type CreditCardStatementActor } from './creditCardStatementAuthority';
import { CreditCardStatementDetailAuthority } from './creditCardStatementDetailAuthority';
import { registerCreditCardPurchaseCycleRoutes } from './creditCardPurchaseCycleRoutes';
import { registerCreditCardStatementCreditRoutes } from './creditCardStatementCreditRoutes';
import { deriveCreditCardStatementOverdue } from './creditCardStatementOverdue';

class CreditCardValidationError extends Error {}
function principal(req: Request): AuthenticatedPrincipal | undefined { return (req as Request & { principal?: AuthenticatedPrincipal }).principal; }
function requirePrincipal(req: Request, res: Response): AuthenticatedPrincipal | null { const p=principal(req); if(!p){res.status(401).json({error:'Unauthorized: Authentication required'});return null;} return p; }
function actor(p: AuthenticatedPrincipal): CreditCardStatementActor { return { companyId:p.companyId,userId:p.userId,name:p.name }; }
function body(value: unknown): Record<string, unknown> { if(!value||typeof value!=='object'||Array.isArray(value)) throw new CreditCardValidationError(); return value as Record<string,unknown>; }
function only(value: Record<string,unknown>, allowed: string[]): void { const set=new Set(allowed); if(!Object.keys(value).every(k=>set.has(k))) throw new CreditCardValidationError(); }
function text(value: unknown,max=200): string { const v=typeof value==='string'?value.trim():''; if(!v||v.length>max) throw new CreditCardValidationError(); return v; }
function optionalText(value: unknown,max=200): string|undefined { if(value===undefined||value===null||value==='') return undefined; return text(value,max); }
function amount(value: unknown, allowZero=false): number { const v=Number(value); if(!Number.isFinite(v)||(allowZero?v<0:v<=0)||Math.abs(v)>999999999.99) throw new CreditCardValidationError(); return Math.round(v*100)/100; }
function day(value: unknown): number { const v=Number(value); if(!Number.isInteger(v)||v<1||v>31) throw new CreditCardValidationError(); return v; }
function isoDate(value: unknown): string { const v=text(value,10); if(!/^\d{4}-\d{2}-\d{2}$/.test(v)) throw new CreditCardValidationError(); const d=new Date(`${v}T00:00:00Z`); if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v) throw new CreditCardValidationError(); return v; }
function send(res: Response,error: unknown): void { const m=error instanceof Error?error.message:''; if(error instanceof CreditCardValidationError){res.status(400).json({error:'Invalid credit-card statement request'});return;} if(m.startsWith('Acesso negado:')){res.status(403).json({error:'Forbidden'});return;} if(m.includes('não encontrada')||m.includes('não encontrado')){res.status(404).json({error:'Not found'});return;} if(m.includes('já existe')||m.includes('incompatível')||m.includes('inativa')||m.includes('fechada')||m.includes('elegível')||m.includes('excede')||m.includes('divergente')||m.includes('ajuste')||m.includes('Ajuste')||m.includes('Desconto')){res.status(409).json({error:'Credit-card statement conflict'});return;} console.error('AUTOERP_CREDIT_CARD_STATEMENT_API_FAILURE',error);res.status(500).json({error:'Credit-card statement operation failed'}); }

export function registerCreditCardStatementRoutes(app: Express): void {
  registerCreditCardPurchaseCycleRoutes(app);
  registerCreditCardStatementCreditRoutes(app);
  app.get('/api/finance/credit-cards/profiles',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{res.json({items:await CreditCardStatementAuthority.listProfiles(actor(p))});}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/profiles',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body);only(b,['financialAccountId','creditLimit','closingDay','dueDay']);res.status(201).json({item:await CreditCardStatementAuthority.createProfile(actor(p),{financialAccountId:text(b.financialAccountId),creditLimit:amount(b.creditLimit,true),closingDay:day(b.closingDay),dueDay:day(b.dueDay)})});}catch(e){send(res,e);}});
  app.get('/api/finance/credit-cards/statements',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const profileId=req.query.profileId===undefined?undefined:text(req.query.profileId);const statements=await CreditCardStatementAuthority.listStatements(actor(p),profileId);const asOf=new Date().toISOString().slice(0,10);res.json({items:statements.map((statement:any)=>({...statement,...deriveCreditCardStatementOverdue(statement,asOf)}))});}catch(e){send(res,e);}});
  app.get('/api/finance/credit-cards/statements/:id/detail',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{res.json(await CreditCardStatementDetailAuthority.get(actor(p),text(req.params.id)));}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/statements',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body);only(b,['creditCardProfileId','cycleRef','closingDate','dueDate']);res.status(201).json({item:await CreditCardStatementAuthority.createStatement(actor(p),{creditCardProfileId:text(b.creditCardProfileId),cycleRef:text(b.cycleRef,20),closingDate:isoDate(b.closingDate),dueDate:isoDate(b.dueDate)})});}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/statements/:id/items',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body);only(b,['financialTransactionId','payableId','originType','originId','originalAmount','adjustmentAmount']);res.status(201).json({item:await CreditCardStatementAuthority.attachItem(actor(p),text(req.params.id),{financialTransactionId:text(b.financialTransactionId),payableId:optionalText(b.payableId),originType:optionalText(b.originType),originId:optionalText(b.originId),originalAmount:amount(b.originalAmount,true),adjustmentAmount:b.adjustmentAmount===undefined?0:amount(b.adjustmentAmount,true)})});}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/statements/:id/close',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body||{});only(b,[]);res.json({item:await CreditCardStatementAuthority.closeStatement(actor(p),text(req.params.id))});}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/statements/:id/payments',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body);only(b,['financialTransactionId','idempotencyKey']);res.status(201).json(await CreditCardStatementAuthority.linkPayment(actor(p),text(req.params.id),{financialTransactionId:text(b.financialTransactionId),idempotencyKey:text(b.idempotencyKey,200)}));}catch(e){send(res,e);}});
  app.post('/api/finance/credit-cards/statements/:id/adjustments',async(req,res)=>{const p=requirePrincipal(req,res);if(!p)return;try{const b=body(req.body);only(b,['interestAmount','fineAmount','discountAmount','reason','idempotencyKey']);res.status(201).json(await CreditCardStatementAuthority.applyAdjustment(actor(p),text(req.params.id),{interestAmount:amount(b.interestAmount??0,true),fineAmount:amount(b.fineAmount??0,true),discountAmount:amount(b.discountAmount??0,true),reason:text(b.reason,1000),idempotencyKey:text(b.idempotencyKey,200)}));}catch(e){send(res,e);}});
}
