import type {Express,Request,Response} from 'express';
import type {AuthenticatedPrincipal} from './auth';
import {MaintenanceAuthorityService,MaintenanceConflictError,MaintenanceNotFoundError,MaintenanceValidationError,type CreatePartInput,type CreateSupplierInput,type CreateWorkOrderInput,type UpdatePartInput,type UpdateSupplierInput} from './maintenanceAuthority';
import {registerMaintenancePreventiveRoutes} from './maintenancePreventiveRoutes';
import {registerMaintenanceTimelineRoutes} from './maintenanceTimelineRoutes';
import {registerMaintenanceTemplateVehicleRoutes} from './maintenanceTemplateVehicleRoutes';
import {registerMaintenanceArchiveRoutes} from './maintenanceArchiveRoutes';

type Action='VIEW_MAINTENANCE'|'MUTATE_MAINTENANCE';
const READ=new Set(['ADMIN','MANAGER','OPERATIONAL_MANAGER','FINANCIAL','FINANCIAL_MANAGER','OPERATIONAL','READONLY']),WRITE=new Set(['ADMIN','MANAGER','OPERATIONAL']);
const PROTECTED=new Set(['companyId','userId','userName','role','status','total','subtotalParts','subtotalServices','subtotalLabor','accountPayableId','createdBy','createdAt','updatedAt','openedAt','startedAt','completedAt','cancelledAt']);
function actor(req:Request,res:Response,action:Action):AuthenticatedPrincipal|null{const p=(req as Request&{principal?:AuthenticatedPrincipal}).principal;if(!p){res.status(401).json({error:'Unauthorized: Authentication required'});return null;}const role=String(p.role||'').toUpperCase(),permissions=Array.isArray(p.permissions)?p.permissions:[],ok=permissions.includes('*')||permissions.includes(action)||(action==='VIEW_MAINTENANCE'?READ.has(role):WRITE.has(role));if(!ok){res.status(403).json({error:'Forbidden'});return null;}return p;}
function reject(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))throw new MaintenanceValidationError('Invalid payload');for(const key of Object.keys(body as Record<string,unknown>))if(PROTECTED.has(key))throw new MaintenanceValidationError(`Protected field: ${key}`);}
function text(v:unknown,max=1000):string{const s=typeof v==='string'?v.trim():'';if(!s||s.length>max)throw new MaintenanceValidationError('Invalid text');return s;}
function opt(v:unknown,max=1000):string|undefined{if(v===undefined||v===null||v==='')return undefined;return text(String(v),max);}
function nullable(v:unknown,max=1000):string|null|undefined{if(v===undefined)return undefined;if(v===null||v==='')return null;return text(String(v),max);}
function nonneg(v:unknown):number{const n=Number(v);if(!Number.isFinite(n)||n<0)throw new MaintenanceValidationError('Invalid number');return n;}
function pos(v:unknown):number{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new MaintenanceValidationError('Invalid number');return n;}
function status(v:unknown):'ACTIVE'|'INACTIVE'|undefined{if(v===undefined)return undefined;if(v!=='ACTIVE'&&v!=='INACTIVE')throw new MaintenanceValidationError('Invalid status');return v;}
function items(value:unknown,kind:'parts'|'services'|'labor'):any[]|undefined{if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>100)throw new MaintenanceValidationError('Invalid work order items');return value.map(raw=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new MaintenanceValidationError('Invalid item');const x=raw as Record<string,unknown>;if(kind==='parts')return{partId:opt(x.partId,200),description:opt(x.description,500),quantity:pos(x.quantity),unitCost:x.unitCost===undefined?undefined:nonneg(x.unitCost)};if(kind==='services')return{serviceId:opt(x.serviceId,200),description:text(x.description,500),quantity:pos(x.quantity),unitCost:nonneg(x.unitCost)};return{description:text(x.description,500),hours:pos(x.hours),hourlyRate:nonneg(x.hourlyRate)};});}
function ids(value:unknown):string[]|undefined{if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>100)throw new MaintenanceValidationError('Invalid preventive plan selection');return Array.from(new Set(value.map(item=>text(item,200))));}
function financeComponents(value:unknown):CreateWorkOrderInput['financialComponents']{if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>3)throw new MaintenanceValidationError('Invalid financial components');return value.map(raw=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new MaintenanceValidationError('Invalid financial component');const x=raw as Record<string,unknown>,kind=x.kind==='PARTS'||x.kind==='SERVICES'||x.kind==='LABOR'?x.kind:undefined,condition=x.paymentCondition==='CASH'||x.paymentCondition==='INSTALLMENTS'?x.paymentCondition:undefined;if(!kind||!condition||typeof x.hasInvoice!=='boolean')throw new MaintenanceValidationError('Invalid financial component');return{kind,supplierId:opt(x.supplierId,200),categoryId:text(x.categoryId,200),paymentMethodId:text(x.paymentMethodId,200),paymentCondition:condition,installmentsCount:Number(x.installmentsCount),firstDueDate:text(x.firstDueDate,10),discountAmount:x.discountAmount===undefined?undefined:nonneg(x.discountAmount),hasInvoice:x.hasInvoice,invoiceNumber:opt(x.invoiceNumber,120)};});}
function unique(e:unknown):boolean{let c:unknown=e;for(let i=0;i<6&&c&&typeof c==='object';i++){if('code'in c&&(c as any).code==='23505')return true;c='cause'in c?(c as any).cause:undefined;}return false;}
function send(res:Response,e:unknown){const m=e instanceof Error?e.message:'';if(e instanceof MaintenanceValidationError){res.status(400).json({error:'Invalid maintenance request'});return;}if(e instanceof MaintenanceNotFoundError||m.includes('não encontrado')||m.includes('não encontrada')){res.status(404).json({error:'Not found'});return;}if(e instanceof MaintenanceConflictError||unique(e)||m.includes('período financeiro')||m.includes('Período')){res.status(409).json({error:'Maintenance command conflict'});return;}if(m.startsWith('Acesso negado:')){res.status(403).json({error:'Forbidden'});return;}console.error('AUTOERP_MAINTENANCE_AUTHORITY_FAILURE',e);res.status(500).json({error:'Maintenance operation failed'});}

export function registerMaintenanceRoutes(app:Express):void{
  registerMaintenancePreventiveRoutes(app);
  registerMaintenanceTemplateVehicleRoutes(app);
  registerMaintenanceTimelineRoutes(app);
  registerMaintenanceArchiveRoutes(app);
  app.get('/api/maintenance/work-orders',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{const vehicleId=typeof req.query.vehicleId==='string'&&req.query.vehicleId.trim()?req.query.vehicleId.trim():undefined;res.json({items:await MaintenanceAuthorityService.listWorkOrders(p.companyId,vehicleId)});}catch(e){send(res,e);}});
  app.get('/api/maintenance/work-orders/:id',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{const item=await MaintenanceAuthorityService.getWorkOrder(p.companyId,req.params.id);if(!item)throw new MaintenanceNotFoundError('Ordem de serviço não encontrada');res.json({item});}catch(e){send(res,e);}});
  app.post('/api/maintenance/work-orders',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreateWorkOrderInput={number:text(req.body?.number,80),vehicleId:text(req.body?.vehicleId,200),supplierId:opt(req.body?.supplierId,200),serviceDate:opt(req.body?.serviceDate,10),entryKm:nonneg(req.body?.entryKm),description:text(req.body?.description,1000),diagnosis:opt(req.body?.diagnosis,1000),notes:opt(req.body?.notes,2000),sourceAttachmentId:opt(req.body?.sourceAttachmentId,200),parts:items(req.body?.parts,'parts'),services:items(req.body?.services,'services'),laborItems:items(req.body?.laborItems,'labor'),discount:req.body?.discount===undefined?undefined:nonneg(req.body.discount),financialComponents:financeComponents(req.body?.financialComponents)};const hasCostItems=Boolean(input.parts?.length||input.services?.length||input.laborItems?.length);if(hasCostItems&&!input.financialComponents?.length)throw new MaintenanceValidationError('Payment details required');res.status(201).json({item:await MaintenanceAuthorityService.createWorkOrder(p,input)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/work-orders/:id/start',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body||{});res.json({item:await MaintenanceAuthorityService.startWorkOrder(p,req.params.id)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/work-orders/:id/complete',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);res.json({item:await MaintenanceAuthorityService.completeWorkOrder(p,req.params.id,{exitKm:nonneg(req.body?.exitKm),categoryId:opt(req.body?.categoryId,200),dueDate:opt(req.body?.dueDate,10),installmentsCount:req.body?.installmentsCount===undefined?undefined:Number(req.body.installmentsCount),preventivePlanIds:ids(req.body?.preventivePlanIds)})});}catch(e){send(res,e);}});
  app.post('/api/maintenance/work-orders/:id/cancel',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);res.json({item:await MaintenanceAuthorityService.cancelWorkOrder(p,req.params.id,text(req.body?.reason,500))});}catch(e){send(res,e);}});

  app.get('/api/maintenance/suppliers',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{res.json({items:await MaintenanceAuthorityService.listSuppliers(p.companyId)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/suppliers',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreateSupplierInput={name:text(req.body?.name,200),document:text(req.body?.document,64),tradeName:opt(req.body?.tradeName,200),phone:opt(req.body?.phone,80),email:opt(req.body?.email,200),address:opt(req.body?.address,500),category:text(req.body?.category,120),notes:opt(req.body?.notes,1000)};res.status(201).json({item:await MaintenanceAuthorityService.createSupplier(p,input)});}catch(e){send(res,e);}});
  app.patch('/api/maintenance/suppliers/:id',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:UpdateSupplierInput={name:req.body?.name===undefined?undefined:text(req.body.name,200),document:req.body?.document===undefined?undefined:text(req.body.document,64),tradeName:nullable(req.body?.tradeName,200),phone:nullable(req.body?.phone,80),email:nullable(req.body?.email,200),address:nullable(req.body?.address,500),category:req.body?.category===undefined?undefined:text(req.body.category,120),status:status(req.body?.status),notes:nullable(req.body?.notes,1000)};if(Object.values(input).every(v=>v===undefined))throw new MaintenanceValidationError('No changes');res.json({item:await MaintenanceAuthorityService.updateSupplier(p,req.params.id,input)});}catch(e){send(res,e);}});

  app.get('/api/maintenance/parts',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{res.json({items:await MaintenanceAuthorityService.listParts(p.companyId)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/parts',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreatePartInput={code:text(req.body?.code,80),name:text(req.body?.name,200),description:opt(req.body?.description,500),manufacturer:opt(req.body?.manufacturer,200),category:text(req.body?.category,120),unit:text(req.body?.unit,30),currentCost:nonneg(req.body?.currentCost),minimumStock:nonneg(req.body?.minimumStock),currentStock:nonneg(req.body?.currentStock)};res.status(201).json({item:await MaintenanceAuthorityService.createPart(p,input)});}catch(e){send(res,e);}});
  app.patch('/api/maintenance/parts/:id',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:UpdatePartInput={code:req.body?.code===undefined?undefined:text(req.body.code,80),name:req.body?.name===undefined?undefined:text(req.body.name,200),description:nullable(req.body?.description,500),manufacturer:nullable(req.body?.manufacturer,200),category:req.body?.category===undefined?undefined:text(req.body.category,120),unit:req.body?.unit===undefined?undefined:text(req.body.unit,30),currentCost:req.body?.currentCost===undefined?undefined:nonneg(req.body.currentCost),minimumStock:req.body?.minimumStock===undefined?undefined:nonneg(req.body.minimumStock),currentStock:req.body?.currentStock===undefined?undefined:nonneg(req.body.currentStock),status:status(req.body?.status)};if(Object.values(input).every(v=>v===undefined))throw new MaintenanceValidationError('No changes');res.json({item:await MaintenanceAuthorityService.updatePart(p,req.params.id,input)});}catch(e){send(res,e);}});
}