import type { Express, Request, Response } from 'express';
import type { AuthenticatedPrincipal } from './auth';
import {
  MaintenancePreventiveAuthority,MaintenancePreventiveConflictError,MaintenancePreventiveNotFoundError,MaintenancePreventiveValidationError,
  type CreateMaintenancePlanInput,type CreateOilChangeInput,type CreateTireInput,type RotateTireInput,type UpdateMaintenancePlanInput,type UpdateTireInput,type RemoveTireInput,
} from './maintenancePreventiveAuthority';
import type { MaintenancePlanPriority, TireStatus } from '../types/entities';

type Action='VIEW_MAINTENANCE'|'MUTATE_MAINTENANCE';
const READ=new Set(['ADMIN','MANAGER','OPERATIONAL_MANAGER','FINANCIAL','FINANCIAL_MANAGER','OPERATIONAL','READONLY']);
const WRITE=new Set(['ADMIN','MANAGER','OPERATIONAL']);
const PROTECTED=new Set(['companyId','userId','userName','role','status','lastExecutionKm','lastExecutionDate','nextDueKm','nextDueDate','lastWorkOrderId','cycleSequence','createdBy','createdAt','updatedAt','removalDate','removalKm','removalReason','lastRotationDate','lastRotationKm']);
function actor(req:Request,res:Response,action:Action):AuthenticatedPrincipal|null{const p=(req as Request&{principal?:AuthenticatedPrincipal}).principal;if(!p){res.status(401).json({error:'Unauthorized: Authentication required'});return null;}const role=String(p.role||'').toUpperCase(),permissions=Array.isArray(p.permissions)?p.permissions:[],ok=permissions.includes('*')||permissions.includes(action)||(action==='VIEW_MAINTENANCE'?READ.has(role):WRITE.has(role));if(!ok){res.status(403).json({error:'Forbidden'});return null;}return p;}
function reject(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))throw new MaintenancePreventiveValidationError('Invalid payload');for(const key of Object.keys(body as Record<string,unknown>))if(PROTECTED.has(key))throw new MaintenancePreventiveValidationError(`Protected field: ${key}`);}
const text=(v:unknown,max=500):string=>{const s=typeof v==='string'?v.trim():'';if(!s||s.length>max)throw new MaintenancePreventiveValidationError('Invalid text');return s;};
const opt=(v:unknown,max=1000):string|undefined=>v===undefined||v===null||v===''?undefined:text(String(v),max);
const number=(v:unknown,min=0):number=>{const n=Number(v);if(!Number.isFinite(n)||n<min)throw new MaintenancePreventiveValidationError('Invalid number');return n;};
const integer=(v:unknown,min=0):number=>{const n=Number(v);if(!Number.isInteger(n)||n<min)throw new MaintenancePreventiveValidationError('Invalid integer');return n;};
const optionalInteger=(v:unknown,min=1):number|undefined=>v===undefined||v===null||v===''?undefined:integer(v,min);
const optionalNumber=(v:unknown,min=0):number|undefined=>v===undefined||v===null||v===''?undefined:number(v,min);
function planPriority(v:unknown):MaintenancePlanPriority|undefined{if(v===undefined)return undefined;const p=String(v) as MaintenancePlanPriority;if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(p))throw new MaintenancePreventiveValidationError('Invalid priority');return p;}
function removalStatus(v:unknown):Exclude<TireStatus,'ACTIVE'>{const s=String(v) as Exclude<TireStatus,'ACTIVE'>;if(!['REMOVED','REPLACED','DAMAGED'].includes(s))throw new MaintenancePreventiveValidationError('Invalid tire status');return s;}
function nullableText(v:unknown,max=1000):string|null|undefined{if(v===undefined)return undefined;if(v===null||v==='')return null;return text(String(v),max);}
function nullableInteger(v:unknown,min=1):number|null|undefined{if(v===undefined)return undefined;if(v===null||v==='')return null;return integer(v,min);}
function nullableNumber(v:unknown,min=0):number|null|undefined{if(v===undefined)return undefined;if(v===null||v==='')return null;return number(v,min);}
function send(res:Response,error:unknown){if(error instanceof MaintenancePreventiveValidationError){res.status(400).json({error:'Invalid preventive maintenance request'});return;}if(error instanceof MaintenancePreventiveNotFoundError){res.status(404).json({error:'Not found'});return;}if(error instanceof MaintenancePreventiveConflictError||String(error).includes('23505')){res.status(409).json({error:'Preventive maintenance conflict'});return;}console.error('AUTOERP_PREVENTIVE_MAINTENANCE_FAILURE',error);res.status(500).json({error:'Preventive maintenance operation failed'});}

export function registerMaintenancePreventiveRoutes(app:Express):void{
  app.get('/api/maintenance/plans',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{res.json({items:await MaintenancePreventiveAuthority.listPlans(p.companyId,typeof req.query.vehicleId==='string'?req.query.vehicleId:undefined)});}catch(e){send(res,e);}});
  app.get('/api/maintenance/plans/:id',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{const item=await MaintenancePreventiveAuthority.getPlan(p.companyId,req.params.id);if(!item)throw new MaintenancePreventiveNotFoundError();res.json({item});}catch(e){send(res,e);}});
  app.post('/api/maintenance/plans',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreateMaintenancePlanInput={vehicleId:text(req.body?.vehicleId,120),name:text(req.body?.name,200),maintenanceType:text(req.body?.maintenanceType,120),intervalKm:optionalInteger(req.body?.intervalKm),intervalDays:optionalInteger(req.body?.intervalDays),priority:planPriority(req.body?.priority),estimatedCost:optionalNumber(req.body?.estimatedCost),notes:opt(req.body?.notes,2000)};res.status(201).json({item:await MaintenancePreventiveAuthority.createPlan(p,input)});}catch(e){send(res,e);}});
  app.patch('/api/maintenance/plans/:id',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:UpdateMaintenancePlanInput={name:req.body?.name===undefined?undefined:text(req.body.name,200),maintenanceType:req.body?.maintenanceType===undefined?undefined:text(req.body.maintenanceType,120),intervalKm:nullableInteger(req.body?.intervalKm),intervalDays:nullableInteger(req.body?.intervalDays),priority:planPriority(req.body?.priority),estimatedCost:nullableNumber(req.body?.estimatedCost),notes:nullableText(req.body?.notes,2000)};res.json({item:await MaintenancePreventiveAuthority.updatePlan(p,req.params.id,input)});}catch(e){send(res,e);}});
  for(const action of ['pause','resume'] as const)app.post(`/api/maintenance/plans/:id/${action}`,async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{res.json({item:await MaintenancePreventiveAuthority.setPlanLifecycle(p,req.params.id,action)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/plans/:id/link-work-order',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);await MaintenancePreventiveAuthority.linkWorkOrder(p,req.params.id,text(req.body?.workOrderId,120));res.json({linked:true});}catch(e){send(res,e);}});

  app.get('/api/maintenance/oil-changes',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{res.json({items:await MaintenancePreventiveAuthority.listOilChanges(p.companyId,typeof req.query.vehicleId==='string'?req.query.vehicleId:undefined)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/oil-changes',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreateOilChangeInput={vehicleId:text(req.body?.vehicleId,120),workOrderId:opt(req.body?.workOrderId,120),km:integer(req.body?.km),date:text(req.body?.date,10),oilType:text(req.body?.oilType,120),oilBrand:text(req.body?.oilBrand,120),quantity:number(req.body?.quantity,0.001),filterChanged:Boolean(req.body?.filterChanged),nextKm:integer(req.body?.nextKm,1),nextDate:opt(req.body?.nextDate,10),supplierId:opt(req.body?.supplierId,120),notes:opt(req.body?.notes,2000)};res.status(201).json({item:await MaintenancePreventiveAuthority.createOilChange(p,input)});}catch(e){send(res,e);}});

  app.get('/api/maintenance/tires',async(req,res)=>{const p=actor(req,res,'VIEW_MAINTENANCE');if(!p)return;try{res.json({items:await MaintenancePreventiveAuthority.listTires(p.companyId,typeof req.query.vehicleId==='string'?req.query.vehicleId:undefined)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/tires',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:CreateTireInput={vehicleId:text(req.body?.vehicleId,120),position:text(req.body?.position,80),brand:text(req.body?.brand,120),model:text(req.body?.model,120),measure:opt(req.body?.measure,80),serialNumber:opt(req.body?.serialNumber,120),installationDate:text(req.body?.installationDate,10),installationKm:integer(req.body?.installationKm),treadDepth:optionalNumber(req.body?.treadDepth),cost:number(req.body?.cost),supplierId:opt(req.body?.supplierId,120),notes:opt(req.body?.notes,2000)};res.status(201).json({item:await MaintenancePreventiveAuthority.createTire(p,input)});}catch(e){send(res,e);}});
  app.patch('/api/maintenance/tires/:id',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:UpdateTireInput={position:req.body?.position===undefined?undefined:text(req.body.position,80),brand:req.body?.brand===undefined?undefined:text(req.body.brand,120),model:req.body?.model===undefined?undefined:text(req.body.model,120),measure:nullableText(req.body?.measure,80),serialNumber:nullableText(req.body?.serialNumber,120),treadDepth:nullableNumber(req.body?.treadDepth),cost:req.body?.cost===undefined?undefined:number(req.body.cost),supplierId:nullableText(req.body?.supplierId,120),notes:nullableText(req.body?.notes,2000)};res.json({item:await MaintenancePreventiveAuthority.updateTire(p,req.params.id,input)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/tires/:id/rotate',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:RotateTireInput={position:text(req.body?.position,80),km:integer(req.body?.km),date:text(req.body?.date,10),intervalKm:optionalInteger(req.body?.intervalKm),intervalDays:optionalInteger(req.body?.intervalDays)};res.json({item:await MaintenancePreventiveAuthority.rotateTire(p,req.params.id,input)});}catch(e){send(res,e);}});
  app.post('/api/maintenance/tires/:id/remove',async(req,res)=>{const p=actor(req,res,'MUTATE_MAINTENANCE');if(!p)return;try{reject(req.body);const input:RemoveTireInput={status:removalStatus(req.body?.status),km:integer(req.body?.km),date:text(req.body?.date,10),reason:text(req.body?.reason,500)};res.json({item:await MaintenancePreventiveAuthority.removeTire(p,req.params.id,input)});}catch(e){send(res,e);}});
}
