import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { UnitOfWork } from '../db/uow';
import { AuditAction } from '../types/enums';
import type { MaintenancePlan, MaintenancePlanPriority, OilChangeRecord, TireRecord, TireStatus } from '../types/entities';
import type { AuthenticatedPrincipal } from './auth';
import { maintenanceNextDue, projectMaintenancePlan } from '../domain/maintenance/maintenancePreventivePolicy';

export class MaintenancePreventiveValidationError extends Error{}
export class MaintenancePreventiveNotFoundError extends Error{}
export class MaintenancePreventiveConflictError extends Error{}

export interface CreateMaintenancePlanInput{vehicleId:string;name:string;maintenanceType:string;intervalKm?:number;intervalDays?:number;priority?:MaintenancePlanPriority;estimatedCost?:number;notes?:string;}
export interface UpdateMaintenancePlanInput{name?:string;maintenanceType?:string;intervalKm?:number|null;intervalDays?:number|null;priority?:MaintenancePlanPriority;estimatedCost?:number|null;notes?:string|null;}
export interface CreateOilChangeInput{vehicleId:string;workOrderId?:string;km:number;date:string;oilType:string;oilBrand:string;quantity:number;filterChanged:boolean;nextKm:number;nextDate?:string;supplierId?:string;notes?:string;}
export interface CreateTireInput{vehicleId:string;position:string;brand:string;model:string;measure?:string;serialNumber?:string;installationDate:string;installationKm:number;treadDepth?:number;cost:number;supplierId?:string;notes?:string;}
export interface UpdateTireInput{position?:string;brand?:string;model?:string;measure?:string|null;serialNumber?:string|null;treadDepth?:number|null;cost?:number;supplierId?:string|null;notes?:string|null;}
export interface RotateTireInput{position:string;km:number;date:string;intervalKm?:number;intervalDays?:number;}
export interface RemoveTireInput{status:Exclude<TireStatus,'ACTIVE'>;km:number;date:string;reason:string;}

const rows=(r:any):any[]=>Array.isArray(r?.rows)?r.rows:[];
const today=()=>new Date().toISOString().slice(0,10);
function text(v:unknown,field:string,max=500):string{const s=typeof v==='string'?v.trim():'';if(!s||s.length>max)throw new MaintenancePreventiveValidationError(`Invalid ${field}`);return s;}
function opt(v:unknown,max=1000):string|undefined{if(v===undefined||v===null||v==='')return undefined;const s=String(v).trim();if(!s||s.length>max)throw new MaintenancePreventiveValidationError('Invalid text');return s;}
function int(v:unknown,field:string,min=0):number{const n=Number(v);if(!Number.isInteger(n)||n<min)throw new MaintenancePreventiveValidationError(`Invalid ${field}`);return n;}
function pos(v:unknown,field:string):number{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new MaintenancePreventiveValidationError(`Invalid ${field}`);return n;}
function money(v:unknown,field:string):number{const n=Number(v);if(!Number.isFinite(n)||n<0)throw new MaintenancePreventiveValidationError(`Invalid ${field}`);return Math.round(n*100)/100;}
function date(v:unknown,field:string):string{const s=text(v,field,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new MaintenancePreventiveValidationError(`Invalid ${field}`);const d=new Date(`${s}T00:00:00Z`);if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)throw new MaintenancePreventiveValidationError(`Invalid ${field}`);return s;}
function priority(v:unknown):MaintenancePlanPriority{const p=String(v||'MEDIUM') as MaintenancePlanPriority;if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(p))throw new MaintenancePreventiveValidationError('Invalid priority');return p;}
async function audit(tx:any,p:AuthenticatedPrincipal,entityName:string,entityId:string,action:AuditAction,before:any,after:any){const now=new Date().toISOString();await tx.getAuditLogRepo().create({id:randomUUID(),companyId:p.companyId,entityName,entityId,action,previousState:before===undefined?undefined:JSON.stringify(before),newState:after===undefined?undefined:JSON.stringify(after),userId:p.userId,userName:p.name,timestamp:now});}
async function vehicle(tx:any,companyId:string,id:string,lock=false){const v=lock?await tx.getVehicleRepo().findByIdForCompanyWithLock(companyId,id):await tx.getVehicleRepo().findByIdForCompany(companyId,id);if(!v||v.isArchived)throw new MaintenancePreventiveNotFoundError('Veículo não encontrado');return v;}
async function supplier(tx:any,companyId:string,id?:string){if(!id)return;const s=await tx.getSupplierRepo().findByIdForCompany(companyId,id);if(!s||s.status!=='ACTIVE')throw new MaintenancePreventiveNotFoundError('Fornecedor não encontrado');}
async function advanceOdometer(tx:any,p:AuthenticatedPrincipal,v:any,km:number,recordDate:string,notes:string){if(km<v.currentKm)throw new MaintenancePreventiveConflictError('KM não pode regredir');if(km===v.currentKm)return;const now=new Date().toISOString();const updated=await tx.getVehicleRepo().updateForCompany(p.companyId,v.id,{currentKm:km,updatedAt:now});if(!updated)throw new MaintenancePreventiveNotFoundError('Veículo não encontrado');await tx.getKmRecordRepo().create({id:randomUUID(),companyId:p.companyId,vehicleId:v.id,driverId:v.currentDriverId,contractId:v.currentContractId,kmValue:km,recordDate,readingType:'MAINTENANCE',notes,createdAt:now});}

export class MaintenancePreventiveAuthority{
  static async listPlans(companyId:string,vehicleId?:string):Promise<MaintenancePlan[]>{return UnitOfWork.run(companyId,async tx=>{const plans=await tx.getMaintenancePlanRepo().findAllByCompany(companyId,vehicleId);const now=today();return await Promise.all(plans.map(async(p:MaintenancePlan)=>{const v=await vehicle(tx,companyId,p.vehicleId);return{...p,...projectMaintenancePlan(p,v.currentKm,now)};}));});}
  static async getPlan(companyId:string,id:string):Promise<MaintenancePlan|null>{return UnitOfWork.run(companyId,async tx=>{const p=await tx.getMaintenancePlanRepo().findByIdForCompany(companyId,id);if(!p)return null;const v=await vehicle(tx,companyId,p.vehicleId);return{...p,...projectMaintenancePlan(p,v.currentKm,today())};});}
  static async createPlan(p:AuthenticatedPrincipal,input:CreateMaintenancePlanInput):Promise<MaintenancePlan>{return UnitOfWork.run(p.companyId,async tx=>{const v=await vehicle(tx,p.companyId,text(input.vehicleId,'vehicleId',120),true);const intervalKm=input.intervalKm===undefined?undefined:int(input.intervalKm,'intervalKm',1),intervalDays=input.intervalDays===undefined?undefined:int(input.intervalDays,'intervalDays',1);if(intervalKm===undefined&&intervalDays===undefined)throw new MaintenancePreventiveValidationError('Plano exige intervalo por KM ou tempo');const baseDate=today(),next=maintenanceNextDue(v.currentKm,baseDate,intervalKm,intervalDays),now=new Date().toISOString();const item:MaintenancePlan={id:randomUUID(),companyId:p.companyId,vehicleId:v.id,name:text(input.name,'name',200),maintenanceType:text(input.maintenanceType,'maintenanceType',120).toUpperCase(),intervalKm,intervalDays,lastExecutionKm:v.currentKm,lastExecutionDate:baseDate,nextDueKm:next.nextDueKm,nextDueDate:next.nextDueDate,priority:priority(input.priority),estimatedCost:input.estimatedCost===undefined?undefined:money(input.estimatedCost,'estimatedCost'),status:'ACTIVE',notes:opt(input.notes,2000),cycleSequence:0,createdBy:p.userId,createdAt:now,updatedAt:now};const created=await tx.getMaintenancePlanRepo().create(item);await audit(tx,p,'MaintenancePlan',created.id,AuditAction.CREATE,undefined,created);return created;});}
  static async updatePlan(p:AuthenticatedPrincipal,id:string,input:UpdateMaintenancePlanInput):Promise<MaintenancePlan>{return UnitOfWork.run(p.companyId,async tx=>{const repo=tx.getMaintenancePlanRepo(),before=await repo.findByIdForCompanyWithLock(p.companyId,id);if(!before)throw new MaintenancePreventiveNotFoundError('Plano não encontrado');if(before.status==='COMPLETED')throw new MaintenancePreventiveConflictError('Plano concluído não pode ser editado');const intervalKm=input.intervalKm===null?undefined:input.intervalKm===undefined?before.intervalKm:int(input.intervalKm,'intervalKm',1),intervalDays=input.intervalDays===null?undefined:input.intervalDays===undefined?before.intervalDays:int(input.intervalDays,'intervalDays',1);if(before.status==='ACTIVE'&&intervalKm===undefined&&intervalDays===undefined)throw new MaintenancePreventiveValidationError('Plano ativo exige intervalo');const baseKm=before.lastExecutionKm??(await vehicle(tx,p.companyId,before.vehicleId)).currentKm,baseDate=before.lastExecutionDate??today(),next=maintenanceNextDue(baseKm,baseDate,intervalKm,intervalDays),updated:MaintenancePlan={...before,name:input.name===undefined?before.name:text(input.name,'name',200),maintenanceType:input.maintenanceType===undefined?before.maintenanceType:text(input.maintenanceType,'maintenanceType',120).toUpperCase(),intervalKm,intervalDays,nextDueKm:next.nextDueKm,nextDueDate:next.nextDueDate,priority:input.priority===undefined?before.priority:priority(input.priority),estimatedCost:input.estimatedCost===null?undefined:input.estimatedCost===undefined?before.estimatedCost:money(input.estimatedCost,'estimatedCost'),notes:input.notes===null?undefined:input.notes===undefined?before.notes:opt(input.notes,2000),updatedAt:new Date().toISOString()};const saved=await repo.save(p.companyId,id,updated);if(!saved)throw new MaintenancePreventiveNotFoundError('Plano não encontrado');await audit(tx,p,'MaintenancePlan',id,AuditAction.UPDATE,before,saved);return saved;});}
  static async setPlanLifecycle(p:AuthenticatedPrincipal,id:string,action:'pause'|'resume'):Promise<MaintenancePlan>{return UnitOfWork.run(p.companyId,async tx=>{const repo=tx.getMaintenancePlanRepo(),before=await repo.findByIdForCompanyWithLock(p.companyId,id);if(!before)throw new MaintenancePreventiveNotFoundError('Plano não encontrado');if(before.status==='COMPLETED')throw new MaintenancePreventiveConflictError('Plano concluído');if(action==='resume'&&!before.intervalKm&&!before.intervalDays)throw new MaintenancePreventiveConflictError('Plano sem intervalo');const updated={...before,status:(action==='pause'?'PAUSED':'ACTIVE') as MaintenancePlan['status'],updatedAt:new Date().toISOString()};const saved=await repo.save(p.companyId,id,updated);if(!saved)throw new MaintenancePreventiveNotFoundError('Plano não encontrado');await audit(tx,p,'MaintenancePlan',id,AuditAction.UPDATE,before,saved);return saved;});}
  static async linkWorkOrder(p:AuthenticatedPrincipal,planId:string,workOrderId:string):Promise<void>{return UnitOfWork.run(p.companyId,async tx=>{const plan=await tx.getMaintenancePlanRepo().findByIdForCompanyWithLock(p.companyId,planId);if(!plan)throw new MaintenancePreventiveNotFoundError('Plano não encontrado');if(plan.status!=='ACTIVE')throw new MaintenancePreventiveConflictError('Plano não está ativo');const raw=tx.getRawTransaction?.();const r=rows(await raw.execute(sql`SELECT id,vehicle_id,status,maintenance_plan_id FROM work_orders WHERE company_id=${p.companyId} AND id=${workOrderId} FOR UPDATE`))[0];if(!r)throw new MaintenancePreventiveNotFoundError('Ordem de serviço não encontrada');if(String(r.vehicle_id)!==plan.vehicleId)throw new MaintenancePreventiveConflictError('Plano e OS pertencem a veículos diferentes');if(['COMPLETED','CANCELLED'].includes(String(r.status)))throw new MaintenancePreventiveConflictError('OS não pode mais ser vinculada');if(r.maintenance_plan_id&&String(r.maintenance_plan_id)!==plan.id)throw new MaintenancePreventiveConflictError('OS já vinculada a outro plano');await raw.execute(sql`UPDATE work_orders SET maintenance_plan_id=${plan.id},updated_at=now() WHERE company_id=${p.companyId} AND id=${workOrderId}`);await audit(tx,p,'MaintenancePlan',plan.id,AuditAction.UPDATE,undefined,{event:'LINK_WORK_ORDER',workOrderId});});}

  static async listOilChanges(companyId:string,vehicleId?:string):Promise<OilChangeRecord[]>{return UnitOfWork.run(companyId,tx=>tx.getOilChangeRepo().findAllByCompany(companyId,vehicleId));}
  static async createOilChange(p:AuthenticatedPrincipal,input:CreateOilChangeInput):Promise<OilChangeRecord>{return UnitOfWork.run(p.companyId,async tx=>{const vehicleId=text(input.vehicleId,'vehicleId',120),v=await vehicle(tx,p.companyId,vehicleId,true),workOrderId=opt(input.workOrderId,120);if(workOrderId){const existing=await tx.getOilChangeRepo().findByWorkOrder(p.companyId,workOrderId);if(existing)return existing;const wo=await tx.getWorkOrderRepo().findByIdForCompanyWithLock(p.companyId,workOrderId);if(!wo)throw new MaintenancePreventiveNotFoundError('Ordem de serviço não encontrada');if(wo.vehicleId!==vehicleId||wo.status!=='COMPLETED'||wo.exitKm===undefined)throw new MaintenancePreventiveConflictError('OS incompatível com troca de óleo');if(Number(input.km)!==wo.exitKm)throw new MaintenancePreventiveConflictError('KM da troca deve corresponder à OS');}const km=int(input.km,'km'),recordDate=date(input.date,'date'),nextKm=int(input.nextKm,'nextKm',1);if(nextKm<=km)throw new MaintenancePreventiveValidationError('Próximo KM deve ser maior');const nextDate=input.nextDate?date(input.nextDate,'nextDate'):undefined;if(nextDate&&nextDate<recordDate)throw new MaintenancePreventiveValidationError('Próxima data inválida');await supplier(tx,p.companyId,input.supplierId);if(!workOrderId)await advanceOdometer(tx,p,v,km,recordDate,'Troca de óleo');const now=new Date().toISOString(),item:OilChangeRecord={id:randomUUID(),companyId:p.companyId,vehicleId,workOrderId,km,date:recordDate,oilType:text(input.oilType,'oilType',120),oilBrand:text(input.oilBrand,'oilBrand',120),quantity:pos(input.quantity,'quantity'),filterChanged:Boolean(input.filterChanged),nextKm,nextDate,supplierId:opt(input.supplierId,120),notes:opt(input.notes,2000),createdBy:p.userId,createdAt:now,updatedAt:now};const created=await tx.getOilChangeRepo().create(item);await audit(tx,p,'OilChangeRecord',created.id,AuditAction.CREATE,undefined,created);return created;});}

  static async listTires(companyId:string,vehicleId?:string):Promise<TireRecord[]>{return UnitOfWork.run(companyId,tx=>tx.getTireRepo().findAllByCompany(companyId,vehicleId));}
  static async createTire(p:AuthenticatedPrincipal,input:CreateTireInput):Promise<TireRecord>{return UnitOfWork.run(p.companyId,async tx=>{const vehicleId=text(input.vehicleId,'vehicleId',120),v=await vehicle(tx,p.companyId,vehicleId,true),km=int(input.installationKm,'installationKm'),recordDate=date(input.installationDate,'installationDate');if(km<v.currentKm)throw new MaintenancePreventiveConflictError('KM de instalação não pode regredir');await supplier(tx,p.companyId,input.supplierId);await advanceOdometer(tx,p,v,km,recordDate,'Instalação de pneu');const now=new Date().toISOString(),item:TireRecord={id:randomUUID(),companyId:p.companyId,vehicleId,position:text(input.position,'position',80).toUpperCase(),brand:text(input.brand,'brand',120),model:text(input.model,'model',120),measure:opt(input.measure,80),serialNumber:opt(input.serialNumber,120),installationDate:recordDate,installationKm:km,treadDepth:input.treadDepth===undefined?undefined:money(input.treadDepth,'treadDepth'),status:'ACTIVE',cost:money(input.cost,'cost'),supplierId:opt(input.supplierId,120),notes:opt(input.notes,2000),createdBy:p.userId,createdAt:now,updatedAt:now};const created=await tx.getTireRepo().create(item);await audit(tx,p,'TireRecord',created.id,AuditAction.CREATE,undefined,created);return created;});}
  static async updateTire(p:AuthenticatedPrincipal,id:string,input:UpdateTireInput):Promise<TireRecord>{return UnitOfWork.run(p.companyId,async tx=>{const repo=tx.getTireRepo(),before=await repo.findByIdForCompanyWithLock(p.companyId,id);if(!before)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');if(before.status!=='ACTIVE')throw new MaintenancePreventiveConflictError('Pneu removido não pode ser editado');await supplier(tx,p.companyId,input.supplierId===null?undefined:input.supplierId);const updated:TireRecord={...before,position:input.position===undefined?before.position:text(input.position,'position',80).toUpperCase(),brand:input.brand===undefined?before.brand:text(input.brand,'brand',120),model:input.model===undefined?before.model:text(input.model,'model',120),measure:input.measure===null?undefined:input.measure===undefined?before.measure:opt(input.measure,80),serialNumber:input.serialNumber===null?undefined:input.serialNumber===undefined?before.serialNumber:opt(input.serialNumber,120),treadDepth:input.treadDepth===null?undefined:input.treadDepth===undefined?before.treadDepth:money(input.treadDepth,'treadDepth'),cost:input.cost===undefined?before.cost:money(input.cost,'cost'),supplierId:input.supplierId===null?undefined:input.supplierId===undefined?before.supplierId:opt(input.supplierId,120),notes:input.notes===null?undefined:input.notes===undefined?before.notes:opt(input.notes,2000),updatedAt:new Date().toISOString()};const saved=await repo.save(p.companyId,id,updated);if(!saved)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');await audit(tx,p,'TireRecord',id,AuditAction.UPDATE,before,saved);return saved;});}
  static async rotateTire(p:AuthenticatedPrincipal,id:string,input:RotateTireInput):Promise<TireRecord>{return UnitOfWork.run(p.companyId,async tx=>{const repo=tx.getTireRepo(),before=await repo.findByIdForCompanyWithLock(p.companyId,id);if(!before)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');if(before.status!=='ACTIVE')throw new MaintenancePreventiveConflictError('Pneu não está ativo');const v=await vehicle(tx,p.companyId,before.vehicleId,true),km=int(input.km,'km'),recordDate=date(input.date,'date');if(km<v.currentKm||km<before.installationKm)throw new MaintenancePreventiveConflictError('KM de rodízio regressivo');await advanceOdometer(tx,p,v,km,recordDate,'Rodízio de pneus');const intervalKm=input.intervalKm===undefined?10000:int(input.intervalKm,'intervalKm',1),intervalDays=input.intervalDays===undefined?undefined:int(input.intervalDays,'intervalDays',1),updated:TireRecord={...before,position:text(input.position,'position',80).toUpperCase(),lastRotationDate:recordDate,lastRotationKm:km,nextRotationKm:km+intervalKm,nextRotationDate:intervalDays?maintenanceNextDue(km,recordDate,undefined,intervalDays).nextDueDate:before.nextRotationDate,updatedAt:new Date().toISOString()};const saved=await repo.save(p.companyId,id,updated);if(!saved)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');await audit(tx,p,'TireRecord',id,AuditAction.UPDATE,before,saved);return saved;});}
  static async removeTire(p:AuthenticatedPrincipal,id:string,input:RemoveTireInput):Promise<TireRecord>{return UnitOfWork.run(p.companyId,async tx=>{const repo=tx.getTireRepo(),before=await repo.findByIdForCompanyWithLock(p.companyId,id);if(!before)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');if(before.status!=='ACTIVE')return before;const v=await vehicle(tx,p.companyId,before.vehicleId,true),km=int(input.km,'km'),recordDate=date(input.date,'date');if(km<v.currentKm||km<before.installationKm)throw new MaintenancePreventiveConflictError('KM de remoção regressivo');await advanceOdometer(tx,p,v,km,recordDate,'Remoção de pneu');const status=String(input.status) as Exclude<TireStatus,'ACTIVE'>;if(!['REMOVED','REPLACED','DAMAGED'].includes(status))throw new MaintenancePreventiveValidationError('Status de remoção inválido');const updated:TireRecord={...before,status,removalDate:recordDate,removalKm:km,removalReason:text(input.reason,'reason',500),updatedAt:new Date().toISOString()};const saved=await repo.save(p.companyId,id,updated);if(!saved)throw new MaintenancePreventiveNotFoundError('Pneu não encontrado');await audit(tx,p,'TireRecord',id,AuditAction.UPDATE,before,saved);return saved;});}
}
