import type { Express, Request, Response } from 'express';
import type { AuthenticatedPrincipal } from './auth';
import {
  OperationalAuthorityService, OperationalConflictError, OperationalForbiddenError, OperationalNotFoundError,
  OperationalValidationError, type CreateOperationalIncidentInput, type CreateOperationalTaskInput,
  type IncidentTransitionInput, type TaskEventInput, type TaskTransitionInput,
} from './operationalAuthority';
import type { IncidentSeverity, IncidentStatus } from '../domain/incident-management/types';
import type { TaskPriority, TaskStatus } from '../domain/workflow/types';

const PROTECTED_KEYS = new Set(['companyId','company_id','userId','user_id','userName','role','permissions','createdBy','reportedBy','correlationId','idempotencyKey']);
function principal(req:Request):AuthenticatedPrincipal|undefined{return (req as Request&{principal?:AuthenticatedPrincipal}).principal;}
function requirePrincipal(req:Request,res:Response):AuthenticatedPrincipal|null{const item=principal(req);if(!item){res.status(401).json({error:'Unauthorized: Authentication required'});return null;}return item;}
function hasProtected(body:unknown):boolean{return Boolean(body&&typeof body==='object'&&!Array.isArray(body)&&Object.keys(body as Record<string,unknown>).some(key=>PROTECTED_KEYS.has(key)));}
function text(value:unknown,max=4000):string{const item=typeof value==='string'?value.trim():'';if(!item||item.length>max)throw new OperationalValidationError('Invalid operational request');return item;}
function optionalText(value:unknown,max=4000):string|undefined{if(value===undefined||value===null||value==='')return undefined;const item=String(value).trim();if(!item||item.length>max)throw new OperationalValidationError('Invalid operational request');return item;}
function idem(req:Request):string{const value=req.headers['x-idempotency-key'];if(typeof value!=='string')throw new OperationalValidationError('Missing idempotency key');return value;}
function uniqueViolation(error:unknown):boolean{let current:any=error;for(let i=0;i<6&&current;i++,current=current.cause)if(current.code==='23505')return true;return false;}
function sendError(res:Response,error:unknown):void{
  if(error instanceof OperationalValidationError){res.status(400).json({error:'Invalid operational request'});return;}
  if(error instanceof OperationalForbiddenError){res.status(403).json({error:'Forbidden'});return;}
  if(error instanceof OperationalNotFoundError){res.status(404).json({error:'Not found'});return;}
  if(error instanceof OperationalConflictError||uniqueViolation(error)){res.status(409).json({error:'Operational conflict'});return;}
  console.error('AUTOERP_OPERATIONAL_AUTHORITY_FAILURE',error);res.status(500).json({error:'Operational authority failure'});
}
function rejectProtected(req:Request):void{if(hasProtected(req.body))throw new OperationalValidationError('Protected identity field');}

export function registerOperationalRoutes(app:Express):void{
  app.get('/api/operations/tasks',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{const status=optionalText(req.query.status,40) as TaskStatus|undefined;const priority=optionalText(req.query.priority,10) as TaskPriority|undefined;const search=optionalText(req.query.search,200);res.json({items:await OperationalAuthorityService.listTasks(actor,{status,priority,search})});}catch(error){sendError(res,error);}});
  app.post('/api/operations/tasks',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);const input:CreateOperationalTaskInput={title:text(req.body?.title,300),description:text(req.body?.description,4000),category:text(req.body?.category,80) as CreateOperationalTaskInput['category'],priority:text(req.body?.priority,10) as CreateOperationalTaskInput['priority'],severity:text(req.body?.severity,20) as CreateOperationalTaskInput['severity'],sourceType:text(req.body?.sourceType,80) as CreateOperationalTaskInput['sourceType'],sourceId:text(req.body?.sourceId,300),entityType:text(req.body?.entityType,80) as CreateOperationalTaskInput['entityType'],entityId:text(req.body?.entityId,300),assignedUserId:optionalText(req.body?.assignedUserId,200),assignedTeam:optionalText(req.body?.assignedTeam,200),dueAt:optionalText(req.body?.dueAt,80)};res.status(201).json({item:await OperationalAuthorityService.createTask(actor,input,idem(req))});}catch(error){sendError(res,error);}});
  app.post('/api/operations/tasks/:id/transition',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);const input:TaskTransitionInput={status:text(req.body?.status,40) as TaskStatus,reason:optionalText(req.body?.reason,4000),assignedUserId:optionalText(req.body?.assignedUserId,200)};res.json({item:await OperationalAuthorityService.transitionTask(actor,text(req.params.id,200),input,idem(req))});}catch(error){sendError(res,error);}});
  app.post('/api/operations/tasks/:id/events',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);const input:TaskEventInput={type:text(req.body?.type,40) as TaskEventInput['type'],content:text(req.body?.content,5000),url:optionalText(req.body?.url,2000)};res.status(201).json({item:await OperationalAuthorityService.addTaskEvent(actor,text(req.params.id,200),input,idem(req))});}catch(error){sendError(res,error);}});

  app.get('/api/operations/incidents',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{const status=optionalText(req.query.status,40) as IncidentStatus|undefined;const severity=optionalText(req.query.severity,20) as IncidentSeverity|undefined;const search=optionalText(req.query.search,200);res.json({items:await OperationalAuthorityService.listIncidents(actor,{status,severity,search})});}catch(error){sendError(res,error);}});
  app.post('/api/operations/incidents',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);const input:CreateOperationalIncidentInput={title:text(req.body?.title,300),description:text(req.body?.description,5000),severity:text(req.body?.severity,20) as CreateOperationalIncidentInput['severity'],priority:text(req.body?.priority,10) as CreateOperationalIncidentInput['priority'],source:text(req.body?.source,80) as CreateOperationalIncidentInput['source'],category:text(req.body?.category,80) as CreateOperationalIncidentInput['category'],assignedTo:optionalText(req.body?.assignedTo,200),commanderId:optionalText(req.body?.commanderId,200),affectedModule:optionalText(req.body?.affectedModule,200),affectedEntityType:optionalText(req.body?.affectedEntityType,200),affectedEntityId:optionalText(req.body?.affectedEntityId,300),impactDescription:optionalText(req.body?.impactDescription,4000),slaDeadlineMinutes:req.body?.slaDeadlineMinutes===undefined?undefined:Number(req.body.slaDeadlineMinutes),fingerprint:optionalText(req.body?.fingerprint,300)};if(input.slaDeadlineMinutes!==undefined&&(!Number.isFinite(input.slaDeadlineMinutes)||input.slaDeadlineMinutes<=0||input.slaDeadlineMinutes>525600))throw new OperationalValidationError('Invalid SLA');res.status(201).json({item:await OperationalAuthorityService.createIncident(actor,input,idem(req))});}catch(error){sendError(res,error);}});
  app.post('/api/operations/incidents/:id/transition',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);const input:IncidentTransitionInput={status:text(req.body?.status,40) as IncidentStatus,comment:optionalText(req.body?.comment,4000),rootCause:optionalText(req.body?.rootCause,4000),resolutionSummary:optionalText(req.body?.resolutionSummary,4000)};res.json({item:await OperationalAuthorityService.transitionIncident(actor,text(req.params.id,200),input,idem(req))});}catch(error){sendError(res,error);}});
  app.post('/api/operations/incidents/:id/actions',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);res.status(201).json({item:await OperationalAuthorityService.addIncidentAction(actor,text(req.params.id,200),text(req.body?.action,120),optionalText(req.body?.comment,4000),idem(req))});}catch(error){sendError(res,error);}});

  app.get('/api/operations/executive/snapshot',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{res.json({snapshot:await OperationalAuthorityService.getExecutiveSnapshot(actor)});}catch(error){sendError(res,error);}});
  app.post('/api/operations/executive/quick-actions',async(req,res)=>{const actor=requirePrincipal(req,res);if(!actor)return;try{rejectProtected(req);res.json(await OperationalAuthorityService.executeQuickAction(actor,text(req.body?.actionType,80),text(req.body?.entityId,200),optionalText(req.body?.reason,4000),idem(req)));}catch(error){sendError(res,error);}});
}
