import type { Express,Request,Response } from 'express';
import type { AuthenticatedPrincipal } from './auth';
import { TelemetryAuthorityService,TelemetryConflictError,TelemetryNotFoundError,TelemetryValidationError,type TelemetryEventType,type TelemetryReviewDecision } from './telemetryAuthority';
import { TelemetryKmDivergenceAuthority } from './telemetryKmDivergenceAuthority';
import { TelemetryMaintenanceAdvisoryAuthority } from './telemetryMaintenanceAdvisoryAuthority';
import { TelemetryContractExcessKmAuthority } from './telemetryContractExcessKmAuthority';
import { TelemetryWebhookAuthenticationError,TelemetryWebhookAuthority,TelemetryWebhookReplayError } from './telemetryWebhookAuth';
type Action='VIEW_TELEMETRY'|'INGEST_TELEMETRY'|'REVIEW_TELEMETRY';
const readRoles=new Set(['ADMIN','MANAGER','OPERATIONAL_MANAGER','OPERATIONAL','READONLY']);
const writeRoles=new Set(['ADMIN','MANAGER','OPERATIONAL_MANAGER','OPERATIONAL']);
function principal(req:Request):AuthenticatedPrincipal|undefined{return (req as Request&{principal?:AuthenticatedPrincipal}).principal;}
function requirePrincipal(req:Request,res:Response,action:Action):AuthenticatedPrincipal|null{const actor=principal(req);if(!actor){res.status(401).json({error:'Unauthorized: Authentication required'});return null;}const explicit=Array.isArray(actor.permissions)&&(actor.permissions.includes('*')||actor.permissions.includes(action));const role=String(actor.role||'').toUpperCase();if(!explicit&&!(action==='VIEW_TELEMETRY'?readRoles:writeRoles).has(role)){res.status(403).json({error:'Forbidden'});return null;}return actor;}
function exact(value:unknown,allowed:string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new TelemetryValidationError('Invalid telemetry request');const item=value as Record<string,unknown>;if(Object.keys(item).some(key=>!allowed.includes(key)))throw new TelemetryValidationError('Protected telemetry field');return item;}
function send(res:Response,error:unknown):void{if(error instanceof TelemetryWebhookAuthenticationError){res.status(401).json({error:'Invalid telemetry webhook'});return;}if(error instanceof TelemetryWebhookReplayError){res.status(409).json({error:'Telemetry webhook replay'});return;}if(error instanceof TelemetryValidationError){res.status(400).json({error:'Invalid telemetry request'});return;}if(error instanceof TelemetryNotFoundError){res.status(404).json({error:'Not found'});return;}if(error instanceof TelemetryConflictError){res.status(409).json({error:'Telemetry conflict'});return;}console.error('AUTOERP_TELEMETRY_AUTHORITY_FAILURE',error instanceof Error?error.message:'Unknown telemetry failure');res.status(500).json({error:'Telemetry operation failed'});}
export function registerTelemetryRoutes(app:Express):void{
  app.post('/api/telemetry/webhooks/synthetic',async(req,res)=>{try{const body=exact(req.body,['trackerId','sourceEventId','eventType','occurredAt','payload']);const verified=TelemetryWebhookAuthority.verify({companyId:req.header('x-autoerp-company-id'),timestamp:req.header('x-autoerp-telemetry-timestamp'),nonce:req.header('x-autoerp-telemetry-nonce'),signature:req.header('x-autoerp-telemetry-signature')},body);await TelemetryWebhookAuthority.claimNonce(verified);const actor:AuthenticatedPrincipal={companyId:verified.companyId,userId:'telemetry-synthetic-webhook',name:'Synthetic Telemetry Webhook',role:'SYSTEM',permissions:['INGEST_TELEMETRY']};const result=await TelemetryAuthorityService.ingest(actor,{trackerId:body.trackerId as string,sourceEventId:body.sourceEventId as string,eventType:body.eventType as TelemetryEventType,occurredAt:body.occurredAt as string,payload:body.payload as Record<string,unknown>});res.status(result.created?202:200).json({accepted:true,created:result.created,status:result.item.status});}catch(error){send(res,error);}});
  app.post('/api/telemetry/events',async(req,res)=>{const actor=requirePrincipal(req,res,'INGEST_TELEMETRY');if(!actor)return;try{const body=exact(req.body,['trackerId','sourceEventId','eventType','occurredAt','payload']);const item=await TelemetryAuthorityService.ingest(actor,{trackerId:body.trackerId as string,sourceEventId:body.sourceEventId as string,eventType:body.eventType as TelemetryEventType,occurredAt:body.occurredAt as string,payload:body.payload as Record<string,unknown>});res.status(item.created?201:200).json(item);}catch(error){send(res,error);}});
  app.post('/api/trackers/:trackerId/telemetry/:eventId/review',async(req,res)=>{const actor=requirePrincipal(req,res,'REVIEW_TELEMETRY');if(!actor)return;try{const body=exact(req.body,['decision','reason']);res.json(await TelemetryAuthorityService.review(actor,req.params.trackerId,req.params.eventId,{decision:body.decision as TelemetryReviewDecision,reason:body.reason as string}));}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry/health',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{res.json({item:await TelemetryAuthorityService.health(actor.companyId,req.params.trackerId)});}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry/observability',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{res.json({item:await TelemetryAuthorityService.observability(actor.companyId,req.params.trackerId)});}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry/km-divergence',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{res.json({item:await TelemetryKmDivergenceAuthority.get(actor.companyId,req.params.trackerId)});}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry/maintenance-advisory',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{res.json({item:await TelemetryMaintenanceAdvisoryAuthority.get(actor.companyId,req.params.trackerId)});}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry/contract-excess-km',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{res.json({item:await TelemetryContractExcessKmAuthority.get(actor.companyId,req.params.trackerId)});}catch(error){send(res,error);}});
  app.get('/api/trackers/:trackerId/telemetry',async(req,res)=>{const actor=requirePrincipal(req,res,'VIEW_TELEMETRY');if(!actor)return;try{const raw=req.query.limit===undefined?50:Number(req.query.limit);const limit=Number.isInteger(raw)&&raw>0&&raw<=100?raw:50;res.json({items:await TelemetryAuthorityService.list(actor.companyId,req.params.trackerId,limit)});}catch(error){send(res,error);}});
}
