import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Droplets,Plus,RefreshCw,Route,Wrench} from 'lucide-react';
import {MaintenancePreventiveClient} from '../../api/maintenancePreventiveClient';
import type {MaintenancePlan,OilChangeRecord,TireRecord,Vehicle,WorkOrder} from '../../types/entities';
import type {MaintenancePlanTemplate} from '../../server/maintenancePlanTemplateAuthority';
import type {MaintenanceAlertRule} from '../../server/maintenanceRuleAuthority';
import {Badge,Button,Card,Input,ModalContainer} from '../ui';
import {MaintenanceSlaSummary} from './MaintenanceSlaSummary';

interface Props{vehicles:Vehicle[];workOrders:WorkOrder[];}
const today=()=>new Date().toISOString().slice(0,10);
function planBadge(p:MaintenancePlan){if(p.projectedStatus==='OVERDUE')return <Badge variant="danger">Vencida</Badge>;if(p.projectedStatus==='DUE')return <Badge variant="warning">Vence agora</Badge>;if(p.projectedStatus==='UPCOMING')return <Badge variant="warning">Próxima</Badge>;if(p.status==='PAUSED')return <Badge variant="neutral">Pausada</Badge>;return <Badge variant="success">Em dia</Badge>;}
function dueDetail(p:MaintenancePlan):string{const parts:string[]=[];if(p.remainingKm!==undefined)parts.push(p.remainingKm<0?`${Math.abs(p.remainingKm).toLocaleString('pt-BR')} km vencidos`:`faltam ${p.remainingKm.toLocaleString('pt-BR')} km`);if(p.remainingDays!==undefined)parts.push(p.remainingDays<0?`${Math.abs(p.remainingDays)} dia(s) vencidos`:`faltam ${p.remainingDays} dia(s)`);return parts.join(' • ');}
const CATEGORY_LABELS={ENGINE:'Motor',COOLING:'Arrefecimento',BRAKES:'Freios',TIRES_WHEELS:'Pneus e rodas',SUSPENSION_STEERING:'Suspensão e direção',TRANSMISSION:'Transmissão',ELECTRICAL:'Elétrica',AIR_CONDITIONING:'Ar-condicionado',SAFETY:'Segurança',GENERAL:'Geral'} as const;
const ACTION_LABELS={REPLACE:'Trocar',INSPECT:'Inspecionar',TEST:'Testar',MEASURE:'Medir',LUBRICATE:'Lubrificar',SERVICE:'Serviço'} as const;

export const MaintenancePreventivePanel:React.FC<Props>=({vehicles,workOrders})=>{
  const[templates,setTemplates]=useState<MaintenancePlanTemplate[]>([]),[plans,setPlans]=useState<MaintenancePlan[]>([]),[oils,setOils]=useState<OilChangeRecord[]>([]),[tires,setTires]=useState<TireRecord[]>([]),[globalRule,setGlobalRule]=useState<MaintenanceAlertRule|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const[ruleWarningKm,setRuleWarningKm]=useState('1000'),[ruleUrgentKm,setRuleUrgentKm]=useState('500'),[ruleWarningDays,setRuleWarningDays]=useState('15'),[ruleUrgentDays,setRuleUrgentDays]=useState('7'),[ruleToleranceKm,setRuleToleranceKm]=useState('0'),[ruleToleranceDays,setRuleToleranceDays]=useState('0');
  const[planVehicle,setPlanVehicle]=useState(''),[planName,setPlanName]=useState('Troca de óleo'),[planKm,setPlanKm]=useState('10000'),[planDays,setPlanDays]=useState('180');
  const[templateEditorOpen,setTemplateEditorOpen]=useState(false),[templateEditing,setTemplateEditing]=useState<MaintenancePlanTemplate|null>(null);
  const[templateName,setTemplateName]=useState(''),[templateCategory,setTemplateCategory]=useState<MaintenancePlanTemplate['category']>('GENERAL'),[templateAction,setTemplateAction]=useState<MaintenancePlanTemplate['actionType']>('INSPECT'),[templateKm,setTemplateKm]=useState(''),[templateDays,setTemplateDays]=useState(''),[templatePriority,setTemplatePriority]=useState<'LOW'|'MEDIUM'|'HIGH'|'CRITICAL'>('MEDIUM'),[templateCost,setTemplateCost]=useState(''),[templateActive,setTemplateActive]=useState(false),[templateNotes,setTemplateNotes]=useState('');
  const[oilVehicle,setOilVehicle]=useState(''),[oilKm,setOilKm]=useState(''),[oilType,setOilType]=useState('5W30'),[oilBrand,setOilBrand]=useState(''),[oilQty,setOilQty]=useState('4'),[oilNextKm,setOilNextKm]=useState(''),[oilWo,setOilWo]=useState('');
  const[tireVehicle,setTireVehicle]=useState(''),[tirePosition,setTirePosition]=useState('DIANTEIRO_ESQUERDO'),[tireBrand,setTireBrand]=useState(''),[tireModel,setTireModel]=useState(''),[tireKm,setTireKm]=useState(''),[tireCost,setTireCost]=useState('0');
  const label=(id:string)=>{const v=vehicles.find(x=>x.id===id);return v?`${v.plate} — ${v.brand} ${v.model}`:id;};
  const load=async()=>{setLoading(true);setError(null);try{const[tpl,p,o,t,r]=await Promise.all([MaintenancePreventiveClient.listTemplates(),MaintenancePreventiveClient.listPlans(),MaintenancePreventiveClient.listOilChanges(),MaintenancePreventiveClient.listTires(),MaintenancePreventiveClient.getGlobalRule()]);setTemplates(tpl);setPlans(p);setOils(o);setTires(t);setGlobalRule(r);setRuleWarningKm(String(r.warningKm));setRuleUrgentKm(String(r.urgentKm));setRuleWarningDays(String(r.warningDays));setRuleUrgentDays(String(r.urgentDays));setRuleToleranceKm(String(r.toleranceKm));setRuleToleranceDays(String(r.toleranceDays));const first=vehicles[0];if(first){if(!planVehicle)setPlanVehicle(first.id);if(!oilVehicle){setOilVehicle(first.id);setOilKm(String(first.currentKm));setOilNextKm(String(first.currentKm+10000));}if(!tireVehicle){setTireVehicle(first.id);setTireKm(String(first.currentKm));}}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar preventivas.');setTemplates([]);setPlans([]);setOils([]);setTires([]);setGlobalRule(null);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Operação preventiva falhou.');}finally{setBusy(false);}};
  const due=plans.filter(p=>p.projectedStatus==='DUE'||p.projectedStatus==='OVERDUE').length;
  const activeTires=tires.filter(t=>t.status==='ACTIVE').length;
  const completedForOil=useMemo(()=>workOrders.filter(w=>w.status==='COMPLETED'&&w.vehicleId===oilVehicle&&w.exitKm!==undefined),[workOrders,oilVehicle]);
  const createPlan=async(e:React.FormEvent)=>{e.preventDefault();await run(async()=>{await MaintenancePreventiveClient.createPlan({vehicleId:planVehicle,name:planName,maintenanceType:planName.toUpperCase().replace(/\s+/g,'_'),intervalKm:planKm?Number(planKm):undefined,intervalDays:planDays?Number(planDays):undefined,priority:'MEDIUM'});});};
  const openTemplateEditor=(t?:MaintenancePlanTemplate)=>{
    setTemplateEditing(t||null);setTemplateName(t?.name||'');setTemplateCategory(t?.category||'GENERAL');setTemplateAction(t?.actionType||'INSPECT');setTemplateKm(t?.intervalKm===undefined?'':String(t.intervalKm));setTemplateDays(t?.intervalDays===undefined?'':String(t.intervalDays));setTemplatePriority(t?.priority||'MEDIUM');setTemplateCost(t?.estimatedCost===undefined?'':String(t.estimatedCost));setTemplateActive(Boolean(t?.active));setTemplateNotes(t?.notes||'');setError(null);setTemplateEditorOpen(true);
  };
  const saveTemplate=async(e:React.FormEvent)=>{e.preventDefault();const intervalKm=templateKm.trim()===''?undefined:Number(templateKm),intervalDays=templateDays.trim()===''?undefined:Number(templateDays),estimatedCost=templateCost.trim()===''?undefined:Number(templateCost);
    if(!templateName.trim()){setError('Informe o nome do item de manutenção.');return;}
    if((intervalKm!==undefined&&(!Number.isInteger(intervalKm)||intervalKm<=0))||(intervalDays!==undefined&&(!Number.isInteger(intervalDays)||intervalDays<=0))){setError('Informe intervalos positivos em KM/dias.');return;}
    if(estimatedCost!==undefined&&(!Number.isFinite(estimatedCost)||estimatedCost<0)){setError('Informe um custo estimado válido.');return;}
    if(templateActive&&intervalKm===undefined&&intervalDays===undefined){setError('Para ativar o item, defina intervalo por KM ou tempo.');return;}
    await run(async()=>{if(templateEditing){await MaintenancePreventiveClient.updateTemplate(templateEditing.id,{name:templateName.trim(),category:templateCategory,actionType:templateAction,intervalKm:intervalKm??null,intervalDays:intervalDays??null,priority:templatePriority,estimatedCost:estimatedCost??null,active:templateActive,notes:templateNotes.trim()||null});}else{await MaintenancePreventiveClient.createTemplate({name:templateName.trim(),category:templateCategory,actionType:templateAction,intervalKm,intervalDays,priority:templatePriority,estimatedCost,active:templateActive,notes:templateNotes.trim()||undefined});}if(templateActive)await MaintenancePreventiveClient.applyTemplatesToFleet();setTemplateEditorOpen(false);setTemplateEditing(null);});
  };
  const saveGlobalRule=async(e:React.FormEvent)=>{e.preventDefault();const values=[ruleWarningKm,ruleUrgentKm,ruleWarningDays,ruleUrgentDays,ruleToleranceKm,ruleToleranceDays].map(Number);if(values.some(v=>!Number.isInteger(v)||v<0)){setError('Informe valores inteiros iguais ou maiores que zero no Banco de Regras.');return;}const[warningKm,urgentKm,warningDays,urgentDays,toleranceKm,toleranceDays]=values;if(warningKm<urgentKm||warningDays<urgentDays){setError('O aviso antecipado deve ser maior ou igual ao aviso urgente.');return;}await run(async()=>{await MaintenancePreventiveClient.updateGlobalRule({warningKm,urgentKm,warningDays,urgentDays,toleranceKm,toleranceDays,active:true});});};
  const createOil=async(e:React.FormEvent)=>{e.preventDefault();await run(async()=>{await MaintenancePreventiveClient.createOilChange({vehicleId:oilVehicle,workOrderId:oilWo||undefined,km:Number(oilKm),date:today(),oilType,oilBrand,quantity:Number(oilQty),filterChanged:true,nextKm:Number(oilNextKm)});});};
  const createTire=async(e:React.FormEvent)=>{e.preventDefault();await run(async()=>{await MaintenancePreventiveClient.createTire({vehicleId:tireVehicle,position:tirePosition,brand:tireBrand,model:tireModel,installationDate:today(),installationKm:Number(tireKm),cost:Number(tireCost)});});};
  const linkPlan=async(p:MaintenancePlan)=>{const candidates=workOrders.filter(w=>w.vehicleId===p.vehicleId&&!['COMPLETED','CANCELLED'].includes(w.status));if(!candidates.length){setError('Não há OS aberta para este veículo.');return;}const raw=window.prompt(`Informe número ou ID da OS:\n${candidates.map(w=>`${w.number} — ${w.id}`).join('\n')}`);if(!raw)return;const wo=candidates.find(w=>w.id===raw||w.number===raw);if(!wo){setError('OS não encontrada entre as opções elegíveis.');return;}await run(()=>MaintenancePreventiveClient.linkWorkOrder(p.id,wo.id));};
  const rotate=async(t:TireRecord)=>{const km=Number(window.prompt('KM do rodízio:',String(vehicles.find(v=>v.id===t.vehicleId)?.currentKm??t.installationKm)));if(!Number.isFinite(km))return;const position=window.prompt('Nova posição:',t.position);if(!position)return;await run(async()=>{await MaintenancePreventiveClient.rotateTire(t.id,{position,km,date:today(),intervalKm:10000});});};
  const remove=async(t:TireRecord)=>{const km=Number(window.prompt('KM da remoção:',String(vehicles.find(v=>v.id===t.vehicleId)?.currentKm??t.installationKm)));if(!Number.isFinite(km))return;const reason=window.prompt('Motivo da remoção:');if(!reason)return;await run(async()=>{await MaintenancePreventiveClient.removeTire(t.id,{status:'REMOVED',km,date:today(),reason});});};
  return <div className="space-y-4">
    <div className="flex items-center justify-between"><div><h3 className="font-semibold flex items-center gap-2"><Wrench className="w-4 h-4"/>Preventivas, óleo e pneus</h3><p className="text-xs text-slate-500">Autoridade server-side com KM canônico, ciclos preventivos e alertas persistentes.</p></div><Button size="sm" variant="ghost" onClick={()=>void load()} icon={<RefreshCw className="w-4 h-4"/>}>Atualizar</Button></div>
    {error&&<div className="p-3 rounded-xl border border-rose-200 bg-rose-50 text-rose-700 text-xs">{error}</div>}{loading&&<div className="p-6 text-center text-xs text-slate-500">Carregando...</div>}
    {!loading&&<>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Card padding="sm"><span className="text-[11px] text-slate-500">PLANOS ATIVOS</span><strong className="block text-2xl">{plans.filter(p=>p.status==='ACTIVE').length}</strong></Card><Card padding="sm"><span className="text-[11px] text-slate-500">VENCIDAS / DEVIDAS</span><strong className="block text-2xl text-amber-600">{due}</strong></Card><Card padding="sm"><span className="text-[11px] text-slate-500">TROCAS DE ÓLEO</span><strong className="block text-2xl">{oils.length}</strong></Card><Card padding="sm"><span className="text-[11px] text-slate-500">PNEUS ATIVOS</span><strong className="block text-2xl">{activeTires}</strong></Card></div>
      <MaintenanceSlaSummary vehicles={vehicles} workOrders={workOrders}/>
      <Card padding="md"><form onSubmit={saveGlobalRule} className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>Banco de Regras — alertas da frota</strong><p className="text-[11px] text-slate-500">Valores operacionais editáveis. Alterar aqui muda os próximos alertas sem alterar código.</p></div><Badge variant={globalRule?.configured?'success':'neutral'}>{globalRule?.configured?'Regra configurada':'Valores sugeridos'}</Badge></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-2"><Input type="number" min="0" value={ruleWarningKm} onChange={e=>setRuleWarningKm(e.target.value)} placeholder="Aviso KM"/><Input type="number" min="0" value={ruleUrgentKm} onChange={e=>setRuleUrgentKm(e.target.value)} placeholder="Urgente KM"/><Input type="number" min="0" value={ruleWarningDays} onChange={e=>setRuleWarningDays(e.target.value)} placeholder="Aviso dias"/><Input type="number" min="0" value={ruleUrgentDays} onChange={e=>setRuleUrgentDays(e.target.value)} placeholder="Urgente dias"/><Input type="number" min="0" value={ruleToleranceKm} onChange={e=>setRuleToleranceKm(e.target.value)} placeholder="Tolerância KM"/><Input type="number" min="0" value={ruleToleranceDays} onChange={e=>setRuleToleranceDays(e.target.value)} placeholder="Tolerância dias"/></div><div className="flex justify-end"><Button type="submit" size="sm" isLoading={busy}>Salvar regra global</Button></div></form></Card>
      <Card padding="none"><div className="p-3 flex flex-wrap items-center justify-between gap-2"><div><strong>Plano padrão da frota</strong><p className="text-[11px] text-slate-500">Configure uma vez. Itens ativos são projetados automaticamente pelo KM atual de cada veículo.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>openTemplateEditor()} icon={<Plus className="w-4 h-4"/>}>Novo item</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void run(async()=>{await MaintenancePreventiveClient.applyTemplatesToFleet();})}>Aplicar à frota</Button></div></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr><th className="p-3 text-left">Item</th><th className="p-3 text-left">Categoria / ação</th><th className="p-3 text-left">Intervalo KM</th><th className="p-3 text-left">Intervalo tempo</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Ação</th></tr></thead><tbody>{templates.map(t=><tr key={t.id} className="border-t"><td className="p-3"><strong>{t.name}</strong><div className="text-[10px] text-slate-500">{t.code}</div></td><td className="p-3"><div>{CATEGORY_LABELS[t.category]}</div><div className="text-[10px] text-slate-500">{ACTION_LABELS[t.actionType]}</div></td><td className="p-3 font-mono">{t.intervalKm===undefined?'Configurar':t.intervalKm.toLocaleString('pt-BR')+' km'}</td><td className="p-3 font-mono">{t.intervalDays===undefined?'—':t.intervalDays+' dias'}</td><td className="p-3"><Badge variant={t.active?'success':'neutral'}>{t.active?'Ativo':'Configurar'}</Badge></td><td className="p-3 text-right"><Button size="sm" variant="outline" disabled={busy} onClick={()=>openTemplateEditor(t)}>Editar</Button></td></tr>)}</tbody></table></div><div className="p-3 border-t text-[11px] text-slate-500">Os intervalos devem seguir a política da frota e o manual do fabricante. O ERP não impõe valores técnicos universais.</div></Card>
      <div className="grid lg:grid-cols-3 gap-3">
        <Card padding="md"><form onSubmit={createPlan} className="space-y-2"><h4 className="font-semibold flex gap-2"><AlertTriangle className="w-4 h-4"/>Novo plano</h4><select className="w-full p-2 border rounded-lg bg-transparent" value={planVehicle} onChange={e=>setPlanVehicle(e.target.value)} required>{vehicles.map(v=><option key={v.id} value={v.id}>{label(v.id)}</option>)}</select><Input value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="Item preventivo" required/><div className="grid grid-cols-2 gap-2"><Input type="number" min="1" value={planKm} onChange={e=>setPlanKm(e.target.value)} placeholder="Intervalo KM"/><Input type="number" min="1" value={planDays} onChange={e=>setPlanDays(e.target.value)} placeholder="Intervalo dias"/></div><Button type="submit" size="sm" isLoading={busy} icon={<Plus className="w-4 h-4"/>}>Criar plano</Button></form></Card>
        <Card padding="md"><form onSubmit={createOil} className="space-y-2"><h4 className="font-semibold flex gap-2"><Droplets className="w-4 h-4"/>Registrar óleo</h4><select className="w-full p-2 border rounded-lg bg-transparent" value={oilVehicle} onChange={e=>{setOilVehicle(e.target.value);const v=vehicles.find(x=>x.id===e.target.value);if(v){setOilKm(String(v.currentKm));setOilNextKm(String(v.currentKm+10000));setOilWo('');}}} required>{vehicles.map(v=><option key={v.id} value={v.id}>{label(v.id)}</option>)}</select><select className="w-full p-2 border rounded-lg bg-transparent" value={oilWo} onChange={e=>{setOilWo(e.target.value);const w=completedForOil.find(x=>x.id===e.target.value);if(w?.exitKm!==undefined){setOilKm(String(w.exitKm));setOilNextKm(String(w.exitKm+10000));}}}><option value="">Sem OS vinculada</option>{completedForOil.map(w=><option key={w.id} value={w.id}>{w.number} — {w.exitKm} km</option>)}</select><div className="grid grid-cols-2 gap-2"><Input type="number" value={oilKm} onChange={e=>setOilKm(e.target.value)} placeholder="KM" required/><Input type="number" value={oilNextKm} onChange={e=>setOilNextKm(e.target.value)} placeholder="Próximo KM" required/></div><div className="grid grid-cols-2 gap-2"><Input value={oilType} onChange={e=>setOilType(e.target.value)} placeholder="Tipo" required/><Input value={oilBrand} onChange={e=>setOilBrand(e.target.value)} placeholder="Marca" required/></div><Input type="number" min="0.001" step="0.001" value={oilQty} onChange={e=>setOilQty(e.target.value)} placeholder="Quantidade" required/><Button type="submit" size="sm" isLoading={busy}>Registrar troca</Button></form></Card>
        <Card padding="md"><form onSubmit={createTire} className="space-y-2"><h4 className="font-semibold flex gap-2"><Wrench className="w-4 h-4"/>Instalar pneu</h4><select className="w-full p-2 border rounded-lg bg-transparent" value={tireVehicle} onChange={e=>{setTireVehicle(e.target.value);const v=vehicles.find(x=>x.id===e.target.value);if(v)setTireKm(String(v.currentKm));}} required>{vehicles.map(v=><option key={v.id} value={v.id}>{label(v.id)}</option>)}</select><Input value={tirePosition} onChange={e=>setTirePosition(e.target.value)} placeholder="Posição" required/><div className="grid grid-cols-2 gap-2"><Input value={tireBrand} onChange={e=>setTireBrand(e.target.value)} placeholder="Marca" required/><Input value={tireModel} onChange={e=>setTireModel(e.target.value)} placeholder="Modelo" required/></div><div className="grid grid-cols-2 gap-2"><Input type="number" value={tireKm} onChange={e=>setTireKm(e.target.value)} placeholder="KM instalação" required/><Input type="number" min="0" step="0.01" value={tireCost} onChange={e=>setTireCost(e.target.value)} placeholder="Custo" required/></div><Button type="submit" size="sm" isLoading={busy}>Instalar pneu</Button></form></Card>
      </div>
      <Card padding="none"><div className="p-3 font-semibold">Planos preventivos</div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr><th className="p-3 text-left">Veículo</th><th className="p-3 text-left">Plano</th><th className="p-3 text-left">Próximo</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Ações</th></tr></thead><tbody>{plans.map(p=><tr key={p.id} className="border-t"><td className="p-3">{label(p.vehicleId)}</td><td className="p-3"><strong>{p.name}</strong><div className="text-slate-500">{p.maintenanceType}</div></td><td className="p-3 font-mono">{p.nextDueKm!==undefined?`${p.nextDueKm.toLocaleString('pt-BR')} km`:''}{p.nextDueKm!==undefined&&p.nextDueDate?' • ':''}{p.nextDueDate||''}</td><td className="p-3">{planBadge(p)}<div className="text-[10px] text-slate-500 mt-1">{dueDetail(p)}</div></td><td className="p-3"><div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={()=>void linkPlan(p)} icon={<Route className="w-3.5 h-3.5"/>}>Vincular OS</Button>{p.status==='ACTIVE'?<Button size="sm" variant="ghost" onClick={()=>void run(async()=>{await MaintenancePreventiveClient.pausePlan(p.id);})}>Pausar</Button>:p.status==='PAUSED'?<Button size="sm" onClick={()=>void run(async()=>{await MaintenancePreventiveClient.resumePlan(p.id);})}>Retomar</Button>:null}</div></td></tr>)}</tbody></table></div></Card>
      <div className="grid lg:grid-cols-2 gap-3"><Card padding="none"><div className="p-3 font-semibold">Histórico de óleo</div>{oils.slice(0,12).map(o=><div key={o.id} className="p-3 border-t text-xs flex justify-between"><span>{label(o.vehicleId)} • {o.oilBrand} {o.oilType}</span><span className="font-mono">{o.km.toLocaleString('pt-BR')} → {o.nextKm.toLocaleString('pt-BR')} km</span></div>)}</Card><Card padding="none"><div className="p-3 font-semibold">Pneus</div>{tires.slice(0,16).map(t=><div key={t.id} className="p-3 border-t text-xs flex items-center justify-between gap-2"><div><strong>{label(t.vehicleId)}</strong><div className="text-slate-500">{t.position} • {t.brand} {t.model} • {t.status}</div></div>{t.status==='ACTIVE'&&<div className="flex gap-1"><Button size="sm" variant="ghost" onClick={()=>void rotate(t)}>Rodízio</Button><Button size="sm" variant="danger" onClick={()=>void remove(t)}>Remover</Button></div>}</div>)}</Card></div>
    </>}
    {templateEditorOpen&&<ModalContainer isOpen={templateEditorOpen} onClose={()=>{if(!busy)setTemplateEditorOpen(false);}} title={templateEditing?'Editar item do plano':'Novo item do plano'} maxWidth="md"><form onSubmit={saveTemplate} className="space-y-4">
      <div><label className="mb-1 block text-xs font-semibold">Nome do item *</label><Input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="Ex.: Limpeza de bicos" required/></div>
      <div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-semibold">Categoria</label><select className="w-full rounded-lg border border-slate-300 bg-transparent p-2 text-sm dark:border-slate-700" value={templateCategory} onChange={e=>setTemplateCategory(e.target.value as MaintenancePlanTemplate['category'])}>{Object.entries(CATEGORY_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div><label className="mb-1 block text-xs font-semibold">Ação padrão</label><select className="w-full rounded-lg border border-slate-300 bg-transparent p-2 text-sm dark:border-slate-700" value={templateAction} onChange={e=>setTemplateAction(e.target.value as MaintenancePlanTemplate['actionType'])}>{Object.entries(ACTION_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div>
      <div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-semibold">Intervalo KM</label><Input type="number" min="1" value={templateKm} onChange={e=>setTemplateKm(e.target.value)} placeholder="Ex.: 10000"/></div><div><label className="mb-1 block text-xs font-semibold">Intervalo em dias</label><Input type="number" min="1" value={templateDays} onChange={e=>setTemplateDays(e.target.value)} placeholder="Ex.: 180"/></div></div>
      <div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-semibold">Prioridade</label><select className="w-full rounded-lg border border-slate-300 bg-transparent p-2 text-sm dark:border-slate-700" value={templatePriority} onChange={e=>setTemplatePriority(e.target.value as 'LOW'|'MEDIUM'|'HIGH'|'CRITICAL')}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></div><div><label className="mb-1 block text-xs font-semibold">Custo estimado</label><Input type="number" min="0" step="0.01" value={templateCost} onChange={e=>setTemplateCost(e.target.value)} placeholder="Opcional"/></div></div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={templateActive} onChange={e=>setTemplateActive(e.target.checked)}/>Ativo para a frota</label>
      <div><label className="mb-1 block text-xs font-semibold">Observações</label><textarea className="min-h-20 w-full rounded-lg border border-slate-300 bg-transparent p-2 text-sm dark:border-slate-700" value={templateNotes} onChange={e=>setTemplateNotes(e.target.value)} placeholder="Observações opcionais"/></div>
      <div className="flex justify-end gap-2"><Button type="button" variant="ghost" disabled={busy} onClick={()=>setTemplateEditorOpen(false)}>Cancelar</Button><Button type="submit" isLoading={busy}>Salvar item</Button></div>
    </form></ModalContainer>}
  </div>;
};
