import {
  MOVEFLEX_CONTRACT_01_TEMPLATE_KEY,
  MOVEFLEX_CONTRACT_01_TEMPLATE_MARKDOWN,
  MOVEFLEX_CONTRACT_01_TEMPLATE_TITLE,
} from './moveflexContract01Template';
import {
  MOVEFLEX_CONTRACT_02_TEMPLATE_KEY,
  MOVEFLEX_CONTRACT_02_TEMPLATE_MARKDOWN,
  MOVEFLEX_CONTRACT_02_TEMPLATE_TITLE,
} from './moveflexContract02Template';

export {
  MOVEFLEX_CONTRACT_01_TEMPLATE_KEY,
  MOVEFLEX_CONTRACT_01_TEMPLATE_MARKDOWN,
  MOVEFLEX_CONTRACT_01_TEMPLATE_TITLE,
  MOVEFLEX_CONTRACT_02_TEMPLATE_KEY,
  MOVEFLEX_CONTRACT_02_TEMPLATE_MARKDOWN,
  MOVEFLEX_CONTRACT_02_TEMPLATE_TITLE,
};

export const MOVEFLEX_BUILT_IN_CONTRACT_TEMPLATES = [
  {
    templateKey: MOVEFLEX_CONTRACT_01_TEMPLATE_KEY,
    title: MOVEFLEX_CONTRACT_01_TEMPLATE_TITLE,
    contentMarkdown: MOVEFLEX_CONTRACT_01_TEMPLATE_MARKDOWN,
  },
  {
    templateKey: MOVEFLEX_CONTRACT_02_TEMPLATE_KEY,
    title: MOVEFLEX_CONTRACT_02_TEMPLATE_TITLE,
    contentMarkdown: MOVEFLEX_CONTRACT_02_TEMPLATE_MARKDOWN,
  },
] as const;

// Compatibilidade: o Contrato 01 continua sendo o modelo padrão dos fluxos existentes.
export const MOVEFLEX_DEFAULT_TEMPLATE_KEY = MOVEFLEX_CONTRACT_01_TEMPLATE_KEY;
export const MOVEFLEX_DEFAULT_TEMPLATE_TITLE = MOVEFLEX_CONTRACT_01_TEMPLATE_TITLE;
export const MOVEFLEX_DEFAULT_CONTRACT_TEMPLATE_MARKDOWN = MOVEFLEX_CONTRACT_01_TEMPLATE_MARKDOWN;

export function moveFlexBlankContractText(): string {
  return MOVEFLEX_DEFAULT_CONTRACT_TEMPLATE_MARKDOWN.replace(/{{\s*[a-zA-Z0-9.]+\s*}}/g, '____________________________');
}
