import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import React from 'react';
import TestRenderer from 'react-test-renderer';
import { FleetComplianceManagement } from '../FleetComplianceManagement';
import { AuthContext } from '../../../hooks/useAuth';
import { TrackerClient, safeTrackerPortalUrl } from '../../../api/trackerClient';
import { DocumentClient } from '../../../api/documentClient';
import { InsuranceClient } from '../../../api/insuranceClient';
import { VehicleClient } from '../../../api/vehicleClient';
import { MaintenanceClient } from '../../../api/maintenanceClient';
import { TrafficTicketClient } from '../../../api/trafficTicketClient';
import { AttachmentClient } from '../../../api/attachmentClient';

const { act } = TestRenderer;
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
(globalThis as any).document = { body: { style: {} }, documentElement: { style: {} }, querySelector: () => null };
(globalThis as any).window = { addEventListener() {}, removeEventListener() {}, confirm: () => true };
(globalThis as any).alert = (message: string) => { throw new Error(message); };
const tracker: any = { id:'tracker-a',companyId:'tenant-a',vehicleId:'vehicle-a',equipmentModel:'Simple',imei:'123456789012345',monthlyCost:65,installationDate:'2026-09-01',supplierId:'financial-supplier',status:'ACTIVE',providerName:'Operational provider',providerContact:'support@example.test',portalUrl:'https://provider.example.test/portal',createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z' };
const realList=TrackerClient.list,realCreate=TrackerClient.create,realFetch=globalThis.fetch;
let sent:any;
// Exercise the actual API client serialization and response mapping without network.
globalThis.fetch=async (_url,init) => { sent=init?.body ? JSON.parse(String(init.body)) : undefined; return new Response(JSON.stringify(init?.method==='POST'?{item:tracker}:{items:[tracker]}),{status:200,headers:{'content-type':'application/json'}}); };
const {id,companyId,status,createdAt,updatedAt,...request}=tracker;
const created=await realCreate.call(TrackerClient,request);
assert.equal(sent.providerName,tracker.providerName);assert.equal(sent.providerContact,tracker.providerContact);assert.equal(sent.portalUrl,tracker.portalUrl);
const [read]=await realList.call(TrackerClient);assert.equal(read.providerName,created.providerName);assert.equal(read.providerContact,created.providerContact);assert.equal(read.portalUrl,created.portalUrl);
for(const url of ['javascript:alert(1)','data:text/html,test','file:///tmp/test','ftp://example.test','https:example.test','https://','bad'])assert.equal(safeTrackerPortalUrl(url),undefined);
assert.equal(safeTrackerPortalUrl('http://provider.example.test/portal'),'http://provider.example.test/portal');
globalThis.fetch=realFetch;
DocumentClient.list=async()=>[];DocumentClient.alertSettings=async()=>({redDays:7,yellowDays:15}) as any;
InsuranceClient.list=async()=>[];InsuranceClient.listExpenseCategories=async()=>[];
VehicleClient.list=async()=>[{id:'vehicle-a',plate:'ABC1D23',brand:'Brand',model:'Model'}] as any;
MaintenanceClient.listSuppliers=async()=>[{id:'financial-supplier',name:'Financial supplier',status:'ACTIVE'}] as any;
TrafficTicketClient.categories=async()=>[];AttachmentClient.list=async()=>[];
TrackerClient.list=async()=>[tracker];TrackerClient.listExpenseCategories=async()=>[{id:'category-a',name:'Tracker expense',type:'EXPENSE'}];
TrackerClient.create=async(payload)=>{sent=payload;return tracker;};
for(const method of ['listTelemetry','getTelemetryHealth','getTelemetryObservability','reviewTelemetry'] as const)(TrackerClient as any)[method]=async()=>{throw new Error('Operational UI called telemetry');};
const text=(node:any):string=>typeof node==='string'?node:Array.isArray(node)?node.map(text).join(' '):node?.children?text(node.children):'';
const user:any={id:'admin',companyId:'tenant-a',name:'Admin',role:'ADMIN',permissions:['*']};
for(const trackerOnly of [false,true]){
  let tree:any;
  await act(async()=>{tree=TestRenderer.create(<AuthContext.Provider value={{user,authMode:'server-session',logout:async()=>{}}}><FleetComplianceManagement initialTab="trackers" trackerOnly={trackerOnly}/></AuthContext.Provider>);});
  const visible=text(tree.toJSON());assert(visible.includes('Operational provider'));assert(visible.includes('support@example.test'));
  assert(!/Telemetria|Consultar eventos|Saúde:|Confirmar divergência|Descartar falso positivo/i.test(visible));
  const link=tree.root.findAllByType('a').find((node:any)=>text(node.props.children)==='Abrir Portal de Rastreamento');assert(link);assert.equal(link.props.href,tracker.portalUrl);assert.equal(link.props.target,'_blank');assert.equal(link.props.rel,'noopener noreferrer');
  await act(async()=>{tree.root.findAllByType('button').find((node:any)=>text(node.props.children).includes('Novo Rastreador')).props.onClick();});
  const change=async(label:string,value:string)=>{await act(async()=>{const field=tree.root.findAllByType('label').find((node:any)=>text(node.props.children).startsWith(label));assert(field,'missing field '+label);field.findAll((node:any)=>node.type==='input'||node.type==='select')[0].props.onChange({target:{value}});});};
  await change('Veículo *','vehicle-a');await change('Modelo *','Simple');await change('IMEI *','123456789012345');await change('Instalação *','2026-09-01');
  await change('Empresa de rastreamento','New provider');await change('Contato','contact@example.test');await change('URL do portal','javascript:alert(1)');
  sent=undefined;await act(async()=>{await tree.root.findByType('form').props.onSubmit({preventDefault(){}});});assert.equal(sent,undefined,'unsafe portal submitted');
  await change('URL do portal','https://new.example.test/portal');await change('Mensalidade','65');await change('Fornecedor','financial-supplier');await change('Categoria','category-a');
  await act(async()=>{await tree.root.findByType('form').props.onSubmit({preventDefault(){}});});
  assert.equal(sent.providerName,'New provider');assert.equal(sent.providerContact,'contact@example.test');assert.equal(sent.portalUrl,'https://new.example.test/portal');assert.equal(sent.supplierId,'financial-supplier');assert.equal(sent.monthlyCost,65);assert.equal(sent.categoryId,'category-a');
  await act(async()=>{tree.unmount();});
}
const app=readFileSync('src/App.tsx','utf8');assert(!app.includes('TelemetryKmDivergenceOverview'));assert(!app.includes('TelemetrySanitizedLocationOverview'));
const routes=readFileSync('src/server/trackerRoutes.ts','utf8');assert(!routes.includes('telemetryRoutes'));assert(!routes.includes('telemetryAuthority'));
console.log('GAP 5 tracker client, form, safe portal and frozen telemetry UI: PASS');
