import React,{useEffect,useMemo,useState}from'react';
import { DocumentClient } from '../../api/documentClient';
import { InsuranceClient,type InsuranceExpenseCategory } from '../../api/insuranceClient';
import { VehicleClient } from '../../api/vehicleClient';
import { TrackerClient,type TrackerExpenseCategory } from '../../api/trackerClient';
import { MaintenanceClient } from '../../api/maintenanceClient';
import { FileUpload } from '../documents/FileUpload';
import { AttachmentList } from '../documents/AttachmentList';
import type { DocumentRecord,Insurance,Supplier,Tracker,Vehicle } from '../../types/entities';
import { DocumentStatus } from '../../types/enums';
import { ShieldCheck,Radio,Plus,Trash2 } from 'lucide-react';
import { Card,Button,Badge,Input,ModalContainer } from '../ui';
import { formatCurrencyBRL } from '../../shared/utils/currency';

export const FleetComplianceManagement:React.FC=()=>{
  const[documents,setDocuments]=useState<DocumentRecord[]>([]),[insurances,setInsurances]=useState<Insurance[]>([]),[trackers,setTrackers]=useState<Tracker[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]);
  const[trackerCategories,setTrackerCategories]=useState<TrackerExpenseCategory[]>([]),[insuranceCategories,setInsuranceCategories]=useState<InsuranceExpenseCategory[]>([]);
  const[activeTab,setActiveTab]=useState<'documents'|'insurances'|'trackers'>('documents'),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const[isDocModalOpen,setIsDocModalOpen]=useState(false),[isInsModalOpen,setIsInsModalOpen]=useState(false),[isTrackerModalOpen,setIsTrackerModalOpen]=useState(false);
  const[trackerAttachmentRefresh,setTrackerAttachmentRefresh]=useState(0);

  const[docVehicleId,setDocVehicleId]=useState(''),[docType,setDocType]=useState('CRLV'),[docNumber,setDocNumber]=useState(''),[docExpDate,setDocExpDate]=useState(''),[docCost,setDocCost]=useState(''),[docNotes,setDocNotes]=useState(''),[docReferenceYear,setDocReferenceYear]=useState(String(new Date().getFullYear())),[docAttachmentId,setDocAttachmentId]=useState('');
  const[docGeneratePayable,setDocGeneratePayable]=useState(true);
  const[insVehicleId,setInsVehicleId]=useState(''),[insCompany,setInsCompany]=useState(''),[insPolicy,setInsPolicy]=useState(''),[insCoverage,setInsCoverage]=useState('Cobertura Completa'),[insDeductible,setInsDeductible]=useState(''),[insPremium,setInsPremium]=useState(''),[insInstallments,setInsInstallments]=useState('1'),[insStartDate,setInsStartDate]=useState(''),[insEndDate,setInsEndDate]=useState(''),[insBroker,setInsBroker]=useState(''),[insBrokerPhone,setInsBrokerPhone]=useState(''),[insCategoryId,setInsCategoryId]=useState('');
  const[trkVehicleId,setTrkVehicleId]=useState(''),[trkModel,setTrkModel]=useState('Concox GT06'),[trkImei,setTrkImei]=useState(''),[trkCarrier,setTrkCarrier]=useState('Vivo M2M'),[trkChip,setTrkChip]=useState(''),[trkCost,setTrkCost]=useState('65'),[trkDate,setTrkDate]=useState(new Date().toISOString().slice(0,10)),[trkSupplierId,setTrkSupplierId]=useState(''),[trkCategoryId,setTrkCategoryId]=useState(''),[trkNotes,setTrkNotes]=useState('');

  const supplierById=useMemo(()=>new Map(suppliers.map(item=>[item.id,item.name])),[suppliers]);
  const loadData=async()=>{setLoading(true);setError('');try{const[docsList,insList,trkList,vehList,supplierList,trkCats,insCats]=await Promise.all([DocumentClient.list({subjectType:'VEHICLE'}),InsuranceClient.list(),TrackerClient.list(),VehicleClient.list(),MaintenanceClient.listSuppliers(),TrackerClient.listExpenseCategories(),InsuranceClient.listExpenseCategories()]);setDocuments(docsList);setInsurances(insList);setTrackers(trkList);setVehicles(vehList.filter(v=>!v.isArchived));setSuppliers(supplierList.filter(s=>s.status==='ACTIVE'));setTrackerCategories(trkCats);setInsuranceCategories(insCats);}catch(err){console.error('Erro ao carregar conformidade',err);setError(err instanceof Error?err.message:'Falha ao carregar conformidade.');}finally{setLoading(false);}};
  useEffect(()=>{void loadData();},[]);
  const getVehiclePlate=(id:string)=>{const v=vehicles.find(item=>item.id===id);return v?`${v.plate} (${v.brand} ${v.model})`:id;};
  const resetDoc=()=>{setDocVehicleId('');setDocNumber('');setDocExpDate('');setDocCost('');setDocNotes('');setDocAttachmentId('');};
  const resetIns=()=>{setInsVehicleId('');setInsCompany('');setInsPolicy('');setInsDeductible('');setInsPremium('');setInsInstallments('1');setInsStartDate('');setInsEndDate('');setInsBroker('');setInsBrokerPhone('');setInsCategoryId('');};
  const resetTrk=()=>{setTrkVehicleId('');setTrkImei('');setTrkChip('');setTrkSupplierId('');setTrkCategoryId('');setTrkNotes('');};

  const handleCreateDocument=async(e:React.FormEvent)=>{e.preventDefault();try{await DocumentClient.create({subjectType:'VEHICLE',subjectId:docVehicleId,documentType:docType,documentNumber:docNumber||undefined,referenceYear:docReferenceYear?Number(docReferenceYear):undefined,expirationDate:docExpDate,attachmentId:docAttachmentId||undefined,cost:docCost?Number(docCost):0,notes:docNotes||undefined,generatePayable:docGeneratePayable});setIsDocModalOpen(false);resetDoc();await loadData();}catch(err:any){alert(err.message||'Erro ao criar documento.');}};
  const handleCreateInsurance=async(e:React.FormEvent)=>{e.preventDefault();const premium=Number(insPremium||0);if(premium>0&&!insCategoryId){alert('Selecione a categoria financeira do seguro.');return;}try{await InsuranceClient.create({vehicleId:insVehicleId,insuranceCompany:insCompany,policyNumber:insPolicy,coverageDetails:insCoverage,deductibleAmount:Number(insDeductible||0),totalPremiumAmount:premium,installmentsCount:Number(insInstallments||1),startDate:insStartDate,endDate:insEndDate,brokerName:insBroker||undefined,brokerPhone:insBrokerPhone||undefined,categoryId:premium>0?insCategoryId:undefined});setIsInsModalOpen(false);resetIns();await loadData();}catch(err:any){alert(err.message||'Erro ao cadastrar seguro.');}};
  const cancelInsurance=async(ins:Insurance)=>{if(ins.status!=='ACTIVE')return;const reason=prompt('Motivo do cancelamento da apólice:','Apólice substituída');if(!reason?.trim())return;try{await InsuranceClient.cancel(ins.id,reason.trim());await loadData();}catch(err:any){alert(err.message||'Erro ao cancelar seguro.');}};
  const handleCreateTracker=async(e:React.FormEvent)=>{e.preventDefault();const monthlyCost=Number(trkCost||0);if(monthlyCost>0&&!trkCategoryId){alert('Selecione a categoria financeira da mensalidade.');return;}try{await TrackerClient.create({vehicleId:trkVehicleId,equipmentModel:trkModel,imei:trkImei,chipCarrier:trkCarrier||undefined,chipNumber:trkChip||undefined,monthlyCost,installationDate:trkDate,supplierId:trkSupplierId||undefined,categoryId:monthlyCost>0?trkCategoryId:undefined,notes:trkNotes||undefined});setIsTrackerModalOpen(false);resetTrk();await loadData();}catch(err:any){alert(err.message||'Erro ao cadastrar rastreador.');}};
  const removeTracker=async(item:Tracker)=>{const reason=prompt('Motivo da remoção/substituição:','Equipamento removido');if(!reason?.trim())return;try{await TrackerClient.remove(item.id,reason.trim());await loadData();}catch(err:any){alert(err.message||'Erro ao remover rastreador.');}};

  const validDocs=documents.filter(d=>d.complianceStatus===DocumentStatus.VALID).length,expiringDocs=documents.filter(d=>d.complianceStatus===DocumentStatus.EXPIRING_SOON).length,expiredDocs=documents.filter(d=>d.complianceStatus===DocumentStatus.EXPIRED).length,activeIns=insurances.filter(i=>i.status==='ACTIVE').length,activeTrk=trackers.filter(t=>t.status==='ACTIVE').length;
  if(loading)return <div className="p-8 text-sm text-slate-500">Carregando conformidade...</div>;
  return <div className="p-4 sm:p-6 space-y-6 max-w-7xl mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h2 className="text-xl font-bold flex items-center gap-2"><ShieldCheck className="w-6 h-6 text-emerald-600"/>Conformidade, Documentos, Seguros & Rastreamento</h2><p className="text-xs text-slate-500 mt-1">Documentos, seguros e rastreadores usam autoridade autenticada do servidor.</p></div><div className="flex gap-2 flex-wrap"><Button size="sm" onClick={()=>setIsDocModalOpen(true)}><Plus className="w-4 h-4"/>Novo Documento</Button><Button variant="outline" size="sm" onClick={()=>setIsInsModalOpen(true)}><ShieldCheck className="w-4 h-4"/>Novo Seguro</Button><Button variant="outline" size="sm" onClick={()=>setIsTrackerModalOpen(true)}><Radio className="w-4 h-4"/>Novo Rastreador</Button></div></div>
    {error&&<div className="rounded-lg border border-rose-300 bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}
    <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">{[['Documentos Válidos',validDocs],['Próx. Vencimento',expiringDocs],['Vencidos',expiredDocs],['Seguros Ativos',activeIns],['Rastreadores GPS',activeTrk]].map(([label,value])=><div key={String(label)} className="p-3.5 bg-white dark:bg-slate-900 border rounded-xl"><span className="text-xs text-slate-400 block">{label}</span><strong className="text-xl font-mono">{value}</strong></div>)}</div>
    <div className="flex gap-2 border-b pb-2">{(['documents','insurances','trackers'] as const).map(tab=><button key={tab} onClick={()=>setActiveTab(tab)} className={`px-4 py-2 rounded-lg text-xs font-semibold ${activeTab===tab?'bg-blue-600 text-white':'text-slate-600 hover:bg-slate-100'}`}>{tab==='documents'?`Documentos (${documents.length})`:tab==='insurances'?`Seguros (${insurances.length})`:`Rastreadores (${trackers.length})`}</button>)}</div>
    <Card padding="md">
      {activeTab==='documents'&&<div className="space-y-4"><h3 className="text-sm font-bold">Documentação Veicular</h3>{documents.length===0?<p className="py-8 text-center text-xs text-slate-500">Nenhum documento cadastrado.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-3">Veículo</th><th className="p-3">Tipo</th><th className="p-3">Vencimento</th><th className="p-3">Custo</th><th className="p-3">Status</th><th className="p-3">Ação</th></tr></thead><tbody>{documents.map(doc=><tr key={doc.id} className="border-b"><td className="p-3 font-mono">{getVehiclePlate(doc.subjectId)}</td><td className="p-3">{doc.documentType}</td><td className="p-3">{doc.expirationDate||'-'}</td><td className="p-3">{formatCurrencyBRL(doc.cost||0)}</td><td className="p-3"><Badge variant={doc.complianceStatus===DocumentStatus.VALID?'success':doc.complianceStatus===DocumentStatus.EXPIRED?'danger':'warning'}>{doc.complianceStatus}</Badge></td><td className="p-3"><button onClick={async()=>{if(confirm('Arquivar documento?')){await DocumentClient.archive(doc.id);await loadData();}}}><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>}</div>}
      {activeTab==='insurances'&&<div className="space-y-4"><div><h3 className="text-sm font-bold">Apólices de Seguro — autoridade do servidor</h3><p className="text-xs text-slate-500">Criação da apólice, parcelas do CP e auditoria são atômicas. Cancelamento e expiração são estados distintos.</p></div>{insurances.length===0?<p className="py-8 text-center text-xs text-slate-500">Nenhuma apólice cadastrada.</p>:<div className="grid md:grid-cols-2 gap-4">{insurances.map(ins=><div key={ins.id} className="p-4 border rounded-xl space-y-3"><div className="flex justify-between gap-2"><strong>{ins.insuranceCompany}</strong><Badge variant={ins.status==='ACTIVE'?'success':ins.status==='EXPIRED'?'danger':'secondary'}>{ins.status}</Badge></div><p className="text-xs text-slate-500">{getVehiclePlate(ins.vehicleId)} • Apólice {ins.policyNumber}</p><div className="grid grid-cols-2 text-xs"><span>Prêmio: {formatCurrencyBRL(ins.totalPremiumAmount)}</span><span>Franquia: {formatCurrencyBRL(ins.deductibleAmount)}</span><span>Parcelas: {ins.installmentsCount}</span><span>Fim: {ins.endDate}</span></div><FileUpload entityType="Insurance" entityId={ins.id} documentType="INSURANCE_POLICY" multiple={true}/><AttachmentList entityType="Insurance" entityId={ins.id}/>{ins.status==='ACTIVE'&&<Button size="sm" variant="outline" onClick={()=>void cancelInsurance(ins)}>Cancelar apólice</Button>}</div>)}</div>}</div>}
      {activeTab==='trackers'&&<div className="space-y-4"><div><h3 className="text-sm font-bold">Rastreadores GPS — autoridade do servidor</h3><p className="text-xs text-slate-500">Instalação, identificação do equipamento e evidências usam a authority autenticada já promovida.</p></div>{trackers.length===0?<p className="py-8 text-center text-xs text-slate-500">Nenhum rastreador cadastrado.</p>:<div className="grid md:grid-cols-2 gap-4">{trackers.map(tr=><div key={tr.id} className="p-4 border rounded-xl space-y-3"><div className="flex justify-between gap-2"><strong>{tr.equipmentModel||'Rastreador GPS'}</strong><Badge variant={tr.status==='ACTIVE'?'success':tr.status==='REMOVED'?'danger':'secondary'}>{tr.status}</Badge></div><p className="text-xs text-slate-500">{getVehiclePlate(tr.vehicleId)} • IMEI {tr.imei||tr.serialNumber||'-'}</p><div className="grid grid-cols-2 gap-2 text-xs"><span>Mensalidade: {formatCurrencyBRL(tr.monthlyCost||0)}</span><span>Fornecedor: {tr.supplierId?supplierById.get(tr.supplierId)||tr.supplierId:'-'}</span><span>Instalação: {tr.installationDate||'-'}</span><span>Operadora: {tr.chipCarrier||'-'}</span></div><div className="space-y-2"><p className="text-xs font-semibold">Evidências do rastreador</p><FileUpload entityType="Tracker" entityId={tr.id} documentType="TRACKER_EVIDENCE" multiple={true} onUploadComplete={()=>setTrackerAttachmentRefresh(value=>value+1)}/><div key={`${tr.id}-${trackerAttachmentRefresh}`}><AttachmentList entityType="Tracker" entityId={tr.id}/></div></div>{tr.status!=='REMOVED'&&<Button size="sm" variant="outline" onClick={()=>void removeTracker(tr)}>Remover</Button>}</div>)}</div>}</div>}
    </Card>

    <ModalContainer isOpen={isDocModalOpen} onClose={()=>setIsDocModalOpen(false)} title="Cadastrar Documento" subtitle="Documento server-authoritative vinculado ao veículo."><form onSubmit={handleCreateDocument} className="space-y-4 text-xs"><label>Veículo *<select value={docVehicleId} onChange={e=>{setDocVehicleId(e.target.value);setDocAttachmentId('');}} className="w-full p-2.5 border rounded-lg" required><option value="">Selecione...</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} - {v.brand} {v.model}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>Tipo<select value={docType} onChange={e=>setDocType(e.target.value)} className="w-full p-2.5 border rounded-lg"><option>CRLV</option><option>IPVA</option><option>LICENCIAMENTO</option><option>VISTORIA</option><option>LAUDO</option><option>OUTROS</option></select></label><label>Nº Documento<Input value={docNumber} onChange={e=>setDocNumber(e.target.value)}/></label><label>Vencimento *<Input type="date" value={docExpDate} onChange={e=>setDocExpDate(e.target.value)} required/></label><label>Custo<Input type="number" step="0.01" value={docCost} onChange={e=>setDocCost(e.target.value)}/></label><label>Ano referência<Input type="number" value={docReferenceYear} onChange={e=>setDocReferenceYear(e.target.value)}/></label></div>{docVehicleId&&<FileUpload entityType="Vehicle" entityId={docVehicleId} documentType={docType} onUploadComplete={a=>setDocAttachmentId(a.id)}/>}<label className="flex gap-2"><input type="checkbox" checked={docGeneratePayable} onChange={e=>setDocGeneratePayable(e.target.checked)}/>Gerar Conta a Pagar</label><label>Observações<textarea value={docNotes} onChange={e=>setDocNotes(e.target.value)} className="w-full p-2.5 border rounded-lg"/></label><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setIsDocModalOpen(false)}>Cancelar</Button><Button type="submit">Salvar</Button></div></form></ModalContainer>

    <ModalContainer isOpen={isInsModalOpen} onClose={()=>setIsInsModalOpen(false)} title="Cadastrar Apólice de Seguro" subtitle="Apólice e parcelas financeiras serão persistidas na mesma transação."><form onSubmit={handleCreateInsurance} className="space-y-4 text-xs"><label>Veículo *<select value={insVehicleId} onChange={e=>setInsVehicleId(e.target.value)} className="w-full p-2.5 border rounded-lg" required><option value="">Selecione...</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} - {v.brand} {v.model}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>Seguradora *<Input value={insCompany} onChange={e=>setInsCompany(e.target.value)} required/></label><label>Apólice *<Input value={insPolicy} onChange={e=>setInsPolicy(e.target.value)} required/></label><label>Cobertura *<Input value={insCoverage} onChange={e=>setInsCoverage(e.target.value)} required/></label><label>Prêmio total<Input type="number" min="0" step="0.01" value={insPremium} onChange={e=>setInsPremium(e.target.value)}/></label><label>Franquia<Input type="number" min="0" step="0.01" value={insDeductible} onChange={e=>setInsDeductible(e.target.value)}/></label><label>Parcelas<Input type="number" min="1" max="60" value={insInstallments} onChange={e=>setInsInstallments(e.target.value)}/></label><label>Início *<Input type="date" value={insStartDate} onChange={e=>setInsStartDate(e.target.value)} required/></label><label>Fim *<Input type="date" value={insEndDate} onChange={e=>setInsEndDate(e.target.value)} required/></label><label>Corretor<Input value={insBroker} onChange={e=>setInsBroker(e.target.value)}/></label><label>Telefone corretor<Input value={insBrokerPhone} onChange={e=>setInsBrokerPhone(e.target.value)}/></label><label>Categoria financeira {Number(insPremium||0)>0?'*':''}<select value={insCategoryId} onChange={e=>setInsCategoryId(e.target.value)} className="w-full p-2.5 border rounded-lg"><option value="">Selecione...</option>{insuranceCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setIsInsModalOpen(false)}>Cancelar</Button><Button type="submit">Salvar Seguro</Button></div></form></ModalContainer>

    <ModalContainer isOpen={isTrackerModalOpen} onClose={()=>setIsTrackerModalOpen(false)} title="Vincular Rastreador GPS" subtitle="Tracker e recorrência financeira persistidos na mesma transação."><form onSubmit={handleCreateTracker} className="space-y-4 text-xs"><label>Veículo *<select value={trkVehicleId} onChange={e=>setTrkVehicleId(e.target.value)} className="w-full p-2.5 border rounded-lg" required><option value="">Selecione...</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} - {v.brand} {v.model}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>Modelo *<Input value={trkModel} onChange={e=>setTrkModel(e.target.value)} required/></label><label>IMEI *<Input value={trkImei} onChange={e=>setTrkImei(e.target.value)} required/></label><label>Operadora<Input value={trkCarrier} onChange={e=>setTrkCarrier(e.target.value)}/></label><label>Chip<Input value={trkChip} onChange={e=>setTrkChip(e.target.value)}/></label><label>Mensalidade<Input type="number" min="0" step="0.01" value={trkCost} onChange={e=>setTrkCost(e.target.value)}/></label><label>Instalação *<Input type="date" value={trkDate} onChange={e=>setTrkDate(e.target.value)} required/></label><label>Fornecedor<select value={trkSupplierId} onChange={e=>setTrkSupplierId(e.target.value)} className="w-full p-2.5 border rounded-lg"><option value="">Sem fornecedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Categoria {Number(trkCost||0)>0?'*':''}<select value={trkCategoryId} onChange={e=>setTrkCategoryId(e.target.value)} className="w-full p-2.5 border rounded-lg"><option value="">Selecione...</option>{trackerCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label>Observações<textarea value={trkNotes} onChange={e=>setTrkNotes(e.target.value)} className="w-full p-2.5 border rounded-lg"/></label><div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setIsTrackerModalOpen(false)}>Cancelar</Button><Button type="submit">Instalar Rastreador</Button></div></form></ModalContainer>
  </div>;
};
