import { requestGuardedClose } from '../../app/unsavedChangesAuthority';
import React,{useEffect,useMemo,useState}from'react';
import { Sparkles,FileText } from 'lucide-react';
import { DocumentAiClient,type DocumentAiExtraction } from '../../api/documentAiClient';
import type { Vehicle } from '../../types/entities';
import { Button,Input,ModalContainer } from '../ui';
import { FileUpload } from '../documents/FileUpload';
import { documentAiFieldLabel } from '../documents/documentAiFieldLabels';

export interface VehicleDocumentAiDraft{vehicleId:string;attachmentId:string;documentType:'IPVA'|'LICENCIAMENTO'|'VISTORIA'|'LAUDO';documentNumber:string;referenceYear:string;issueDate:string;expirationDate:string;cost:string;notes:string;}
interface Props{isOpen:boolean;vehicles:Vehicle[];onClose:()=>void;onUseDraft:(draft:VehicleDocumentAiDraft)=>void;}
const value=(v:unknown)=>v===undefined||v===null?'':String(v);
export const VehicleDocumentAiAssistModal:React.FC<Props>=({isOpen,vehicles,onClose,onUseDraft})=>{
 const[vehicleId,setVehicleId]=useState(''),[documentType,setDocumentType]=useState<'IPVA'|'LICENCIAMENTO'|'VISTORIA'|'LAUDO'>('IPVA'),[attachmentId,setAttachmentId]=useState(''),[extraction,setExtraction]=useState<DocumentAiExtraction|null>(null),[draft,setDraft]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const reset=()=>{setVehicleId('');setDocumentType('IPVA');setAttachmentId('');setExtraction(null);setDraft({});setBusy(false);setError('');};
 useEffect(()=>{if(!isOpen)reset();},[isOpen]);
 useEffect(()=>{if(!isOpen||!extraction||!['PENDING','PROCESSING'].includes(extraction.status))return;const timer=window.setInterval(()=>{void DocumentAiClient.list().then(items=>{const current=items.find(item=>item.id===extraction.id||item.attachmentId===attachmentId);if(current)setExtraction(current);}).catch(()=>undefined);},4000);return()=>window.clearInterval(timer);},[isOpen,extraction?.id,extraction?.status,attachmentId]);
 useEffect(()=>{if(extraction?.status==='REVIEW_REQUIRED')setDraft(Object.fromEntries(Object.entries(extraction.proposedFields).map(([k,v])=>[k,value(v)])));},[extraction?.id,extraction?.status]);
 const selectedVehicle=useMemo(()=>vehicles.find(v=>v.id===vehicleId),[vehicles,vehicleId]);
 const uploaded=async(att:any)=>{setAttachmentId(att.id);setBusy(true);setError('');try{setExtraction(await DocumentAiClient.create({attachmentId:att.id,idempotencyKey:'vehicle-document-ai:'+documentType+':'+att.id}));}catch(err:unknown){setError(err instanceof Error?err.message:'Não foi possível iniciar a leitura do documento.');}finally{setBusy(false);}};
 const approve=async()=>{if(!extraction||extraction.status!=='REVIEW_REQUIRED'||!vehicleId||!attachmentId)return;setBusy(true);setError('');try{const corrections:Record<string,unknown>={};for(const[k,original]of Object.entries(extraction.proposedFields)){const candidate=draft[k]??'';if(String(original??'')!==candidate)corrections[k]=candidate;}await DocumentAiClient.review(extraction.id,{decision:'APPROVE',corrections,notes:documentType+' revisado para preenchimento assistido do documento'});const merged={...extraction.proposedFields,...corrections};const notes=[merged.installmentNumber?'Parcela identificada pela IA: '+value(merged.installmentNumber):'',merged.odometer?'KM identificado pela IA: '+value(merged.odometer):'',merged.issuerName?'Emissor: '+value(merged.issuerName):'',merged.result?'Resultado: '+value(merged.result):''].filter(Boolean).join(' · ');onUseDraft({vehicleId,attachmentId,documentType,documentNumber:value(merged.documentNumber),referenceYear:value(merged.taxYear||merged.referenceYear),issueDate:value(merged.issueDate).slice(0,10),expirationDate:value(merged.dueDate||merged.expirationDate).slice(0,10),cost:value(merged.amount),notes});onClose();}catch(err:unknown){setError(err instanceof Error?err.message:'Não foi possível aprovar os dados do documento.');}finally{setBusy(false);}};
 if(!isOpen)return null;
 const fields=extraction?.status==='REVIEW_REQUIRED'?Object.entries(extraction.proposedFields):[];
 return <ModalContainer isOpen={isOpen} onClose={onClose} title="Ler documento com IA" maxWidth="lg"><div className="space-y-4">
  <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200"><strong className="flex items-center gap-2"><Sparkles className="h-4 w-4"/>Preenchimento assistido</strong><p className="mt-1">A IA extrai somente os campos compatíveis com o tipo selecionado. Você revisa antes de usar. Gerar Conta a Pagar e categoria financeira continuam manuais.</p></div>
  <div><label className="mb-1 block text-xs font-semibold">Veículo *</label><select className="w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm dark:border-slate-700 dark:bg-slate-900" value={vehicleId} onChange={e=>{setVehicleId(e.target.value);setAttachmentId('');setExtraction(null);setDraft({});}} disabled={busy||Boolean(attachmentId)}><option value="">Selecione o veículo</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} — {v.brand} {v.model}</option>)}</select></div>
  <div><label className="mb-1 block text-xs font-semibold">Tipo de documento *</label><select className="w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm dark:border-slate-700 dark:bg-slate-900" value={documentType} onChange={e=>{setDocumentType(e.target.value as 'IPVA'|'LICENCIAMENTO'|'VISTORIA'|'LAUDO');setAttachmentId('');setExtraction(null);setDraft({});}} disabled={busy||Boolean(attachmentId)}><option value="IPVA">IPVA</option><option value="LICENCIAMENTO">Licenciamento</option><option value="VISTORIA">Vistoria</option><option value="LAUDO">Laudo</option></select></div>
  {vehicleId&&!attachmentId&&<FileUpload entityType="Vehicle" entityId={vehicleId} documentType={documentType} onUploadComplete={uploaded}/>} 
  {attachmentId&&<div className="rounded-lg border p-3 text-xs"><strong>Documento original anexado</strong><p className="mt-1 text-slate-500">{selectedVehicle?.plate} · anexo {attachmentId}</p></div>}
  {extraction&&['PENDING','PROCESSING'].includes(extraction.status)&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Analisando documento… atualização automática.</div>}
  {extraction?.status==='FAILED'&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">A leitura falhou. Tente novamente com um documento mais legível.</div>}
  {extraction?.status==='REVIEW_REQUIRED'&&<div className="space-y-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-emerald-600"/><strong className="text-sm">Revise os dados encontrados</strong></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{fields.map(([key,original])=><Input key={key} label={documentAiFieldLabel(key)} value={draft[key]??value(original)} onChange={e=>setDraft(cur=>({...cur,[key]:e.target.value}))}/>)}</div></div>}
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}
  <div className="flex justify-end gap-2"><Button variant="ghost" onClick={(event)=>requestGuardedClose(event,onClose)} disabled={busy}>Cancelar</Button>{extraction?.status==='REVIEW_REQUIRED'&&<Button onClick={()=>void approve()} isLoading={busy}>Usar dados no Documento</Button>}</div>
 </div></ModalContainer>;
};