import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ListTodo, Loader2, Plus, RefreshCw, Search } from 'lucide-react';
import { OperationalAuthorityClient } from '../../api/operationalAuthorityClient';
import type { Task, TaskCategory, TaskPriority, TaskSeverity, TaskStatus } from '../../domain/workflow/types';
import { useAuth } from '../../hooks/useAuth';

interface OperationalTasksViewProps {
  companyId?: string;
  onNavigate?: (tab: string) => void;
  incidents?: unknown[];
  pendings?: unknown[];
}

const ACTIVE = new Set<TaskStatus>(['OPEN','ASSIGNED','IN_PROGRESS','BLOCKED','WAITING_VALIDATION','REOPENED']);
const PRIORITY_CLASS:Record<TaskPriority,string>={P0:'bg-red-100 text-red-800',P1:'bg-orange-100 text-orange-800',P2:'bg-blue-100 text-blue-800',P3:'bg-slate-100 text-slate-700'};
function nextStatus(status:TaskStatus):TaskStatus|null{switch(status){case'OPEN':case'ASSIGNED':case'REOPENED':return'IN_PROGRESS';case'BLOCKED':return'IN_PROGRESS';case'IN_PROGRESS':return'COMPLETED';case'WAITING_VALIDATION':return'COMPLETED';case'COMPLETED':return'CLOSED';case'CLOSED':case'CANCELLED':return'REOPENED';default:return null;}}
function actionLabel(status:TaskStatus):string{const next=nextStatus(status);if(!next)return'Sem ação';return ({IN_PROGRESS:status==='BLOCKED'?'Desbloquear':'Iniciar',COMPLETED:'Concluir',CLOSED:'Fechar',REOPENED:'Reabrir'} as Record<string,string>)[next]||next;}

export const OperationalTasksView:React.FC<OperationalTasksViewProps>=({onNavigate})=>{
  const {user}=useAuth();
  const [items,setItems]=useState<Task[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null);
  const [search,setSearch]=useState('');
  const [priority,setPriority]=useState<'ALL'|TaskPriority>('ALL');
  const [status,setStatus]=useState<'ACTIVE'|'DONE'|'ALL'>('ACTIVE');
  const [creating,setCreating]=useState(false);
  const [busyId,setBusyId]=useState<string|null>(null);
  const [form,setForm]=useState<{title:string;description:string;category:TaskCategory;priority:TaskPriority;severity:TaskSeverity;dueAt:string}>({title:'',description:'',category:'OPERATIONAL_GENERAL',priority:'P2',severity:'MEDIUM',dueAt:''});

  const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await OperationalAuthorityClient.listTasks());}catch(err){setItems([]);setError(err instanceof Error?err.message:'Falha ao carregar tarefas');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>items.filter(item=>{if(search&&!(item.title+' '+item.description).toLowerCase().includes(search.toLowerCase()))return false;if(priority!=='ALL'&&item.priority!==priority)return false;if(status==='ACTIVE'&&!ACTIVE.has(item.status))return false;if(status==='DONE'&&!['COMPLETED','CLOSED'].includes(item.status))return false;return true;}),[items,search,priority,status]);
  const activeCount=items.filter(item=>ACTIVE.has(item.status)).length,blockedCount=items.filter(item=>item.status==='BLOCKED').length,overdueCount=items.filter(item=>ACTIVE.has(item.status)&&new Date(item.dueAt).getTime()<Date.now()).length;

  async function createTask(event:React.FormEvent){event.preventDefault();setError(null);setBusyId('new');try{const dueAt=form.dueAt?new Date(form.dueAt).toISOString():undefined;const created=await OperationalAuthorityClient.createTask({title:form.title,description:form.description,category:form.category,priority:form.priority,severity:form.severity,sourceType:'MANUAL',sourceId:crypto.randomUUID(),entityType:'SYSTEM',entityId:'operations',dueAt});setItems(current=>[created,...current]);setCreating(false);setForm({title:'',description:'',category:'OPERATIONAL_GENERAL',priority:'P2',severity:'MEDIUM',dueAt:''});}catch(err){setError(err instanceof Error?err.message:'Falha ao criar tarefa');}finally{setBusyId(null);}}
  async function advance(item:Task){const target=nextStatus(item.status);if(!target)return;setBusyId(item.id);setError(null);try{const reason=item.status==='BLOCKED'?'Bloqueio removido via Central de Tarefas':`Transição ${item.status} → ${target} por ${user.name}`;const updated=await OperationalAuthorityClient.transitionTask(item.id,{status:target,reason});setItems(current=>current.map(value=>value.id===updated.id?updated:value));}catch(err){setError(err instanceof Error?err.message:'Falha ao atualizar tarefa');}finally{setBusyId(null);}}
  async function block(item:Task){const reason=window.prompt('Motivo do bloqueio:')?.trim();if(!reason)return;setBusyId(item.id);setError(null);try{const updated=await OperationalAuthorityClient.transitionTask(item.id,{status:'BLOCKED',reason});setItems(current=>current.map(value=>value.id===updated.id?updated:value));}catch(err){setError(err instanceof Error?err.message:'Falha ao bloquear tarefa');}finally{setBusyId(null);}}

  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ListTodo className="h-6 w-6 text-blue-600"/><h1 className="text-2xl font-bold text-slate-900">Tarefas Operacionais</h1></div><p className="mt-1 text-sm text-slate-500">Autoridade server-side • sessão: {user.name}</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-medium"><RefreshCw className="h-4 w-4"/>Atualizar</button><button onClick={()=>setCreating(value=>!value)} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Nova tarefa</button></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-slate-500">Ativas</div><div className="mt-1 text-2xl font-bold">{activeCount}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-slate-500">Bloqueadas</div><div className="mt-1 text-2xl font-bold text-orange-600">{blockedCount}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-slate-500">Vencidas</div><div className="mt-1 text-2xl font-bold text-red-600">{overdueCount}</div></div></div>
    {creating&&<form onSubmit={createTask} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-2"><input required maxLength={300} value={form.title} onChange={event=>setForm({...form,title:event.target.value})} placeholder="Título da tarefa" className="rounded-lg border px-3 py-2"/><div className="grid grid-cols-3 gap-2"><select value={form.priority} onChange={event=>setForm({...form,priority:event.target.value as TaskPriority})} className="rounded-lg border px-2 py-2"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select><select value={form.severity} onChange={event=>setForm({...form,severity:event.target.value as TaskSeverity})} className="rounded-lg border px-2 py-2"><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><input type="datetime-local" value={form.dueAt} onChange={event=>setForm({...form,dueAt:event.target.value})} className="rounded-lg border px-2 py-2"/></div><textarea required maxLength={4000} value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="Descrição" className="min-h-24 rounded-lg border px-3 py-2 md:col-span-2"/><div className="flex gap-2 md:col-span-2"><button disabled={busyId==='new'} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busyId==='new'?'Criando...':'Criar tarefa'}</button><button type="button" onClick={()=>setCreating(false)} className="rounded-lg border px-4 py-2 text-sm">Cancelar</button></div></form>}
    {error&&<div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-4 w-4"/>{error}</div>}
    <div className="flex flex-wrap gap-3 rounded-xl border bg-white p-3"><label className="flex min-w-64 flex-1 items-center gap-2 rounded-lg border px-3"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar tarefa" className="w-full py-2 outline-none"/></label><select value={priority} onChange={event=>setPriority(event.target.value as 'ALL'|TaskPriority)} className="rounded-lg border px-3 py-2"><option value="ALL">Todas prioridades</option><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select><select value={status} onChange={event=>setStatus(event.target.value as typeof status)} className="rounded-lg border px-3 py-2"><option value="ACTIVE">Ativas</option><option value="DONE">Concluídas</option><option value="ALL">Todas</option></select></div>
    {loading?<div className="flex items-center justify-center gap-2 rounded-xl border bg-white p-12 text-slate-500"><Loader2 className="h-5 w-5 animate-spin"/>Carregando autoridade de tarefas...</div>:filtered.length===0?<div className="rounded-xl border bg-white p-12 text-center text-slate-500"><CheckCircle2 className="mx-auto mb-2 h-8 w-8 text-emerald-500"/>Nenhuma tarefa neste filtro.</div>:<div className="space-y-3">{filtered.map(item=><article key={item.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${PRIORITY_CLASS[item.priority]}`}>{item.priority}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium">{item.status}</span><span className="text-xs text-slate-400">{item.category}</span></div><h2 className="mt-2 font-semibold text-slate-900">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.description}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span>Vencimento: {new Date(item.dueAt).toLocaleString('pt-BR')}</span>{item.assignedUserId&&<span>Responsável: {item.assignedUserId}</span>}<span>Correlação: {item.correlationId.slice(0,8)}</span></div>{item.blockedReason&&<p className="mt-2 rounded bg-orange-50 p-2 text-xs text-orange-700">Bloqueio: {item.blockedReason}</p>}</div><div className="flex gap-2">{item.status==='IN_PROGRESS'&&<button disabled={busyId===item.id} onClick={()=>void block(item)} className="rounded-lg border border-orange-200 px-3 py-2 text-sm text-orange-700 disabled:opacity-50">Bloquear</button>}{nextStatus(item.status)&&<button disabled={busyId===item.id} onClick={()=>void advance(item)} className="rounded-lg border px-3 py-2 text-sm font-medium disabled:opacity-50">{busyId===item.id?'Processando...':actionLabel(item.status)}</button>}</div></div>{onNavigate&&item.entityType!=='SYSTEM'&&<button onClick={()=>onNavigate(item.entityType.toLowerCase())} className="mt-3 text-xs font-medium text-blue-600">Abrir entidade relacionada</button>}</article>)}</div>}
  </div>;
};
