import React,{useEffect,useMemo,useState} from 'react';
import { Filter,Plus,RefreshCw,Route,X } from 'lucide-react';
import { TollPassageClient,type TollPassage,type TollPassageListFilters,type TollPassageStatus } from '../../api/tollPassageClient';
import { VehicleClient } from '../../api/vehicleClient';
import { DriverClient } from '../../api/driverClient';
import type { Driver,Vehicle } from '../../types/entities';

const statusLabel:Record<TollPassageStatus,string>={PENDING:'Pendente',PAID:'Pago',OVERDUE:'Vencido',CONTESTED:'Contestado'};
const statusClass:Record<TollPassageStatus,string>={PENDING:'bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300',PAID:'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-300',OVERDUE:'bg-rose-100 text-rose-800 dark:bg-rose-950/50 dark:text-rose-300',CONTESTED:'bg-slate-200 text-slate-700 dark:bg-slate-800 dark:text-slate-300'};
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function nowLocal():string{const date=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return date.toISOString().slice(0,16);}

export const TollPassagesManagement:React.FC=()=>{
  const[items,setItems]=useState<TollPassage[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const[statusFilter,setStatusFilter]=useState<TollPassageStatus|''>(''),[vehicleFilter,setVehicleFilter]=useState(''),[driverFilter,setDriverFilter]=useState(''),[concessionaireFilter,setConcessionaireFilter]=useState(''),[occurredFrom,setOccurredFrom]=useState(''),[occurredTo,setOccurredTo]=useState('');
  const[plate,setPlate]=useState(''),[concessionaire,setConcessionaire]=useState(''),[road,setRoad]=useState(''),[tollPoint,setTollPoint]=useState(''),[occurredAt,setOccurredAt]=useState(nowLocal()),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState(''),[sourceReference,setSourceReference]=useState(''),[notes,setNotes]=useState('');
  const vehicleById=useMemo(()=>new Map(vehicles.map(vehicle=>[vehicle.id,vehicle])),[vehicles]);
  const driverById=useMemo(()=>new Map(drivers.map(driver=>[driver.id,driver])),[drivers]);
  const currentFilters=():TollPassageListFilters=>({vehicleId:vehicleFilter||undefined,driverId:driverFilter||undefined,status:statusFilter||undefined,concessionaire:concessionaireFilter.trim()||undefined,occurredFrom:occurredFrom||undefined,occurredTo:occurredTo||undefined});
  const load=async(filters:TollPassageListFilters=currentFilters())=>{setLoading(true);setError('');try{const[passages,vehicleList,driverList]=await Promise.all([TollPassageClient.list(filters),VehicleClient.list(),DriverClient.list()]);setItems(passages);setVehicles(vehicleList);setDrivers(driverList);}catch(err){setError(err instanceof Error?err.message:'Não foi possível carregar os pedágios.');}finally{setLoading(false);}};
  useEffect(()=>{void load({});},[]);
  const clearFilters=()=>{setStatusFilter('');setVehicleFilter('');setDriverFilter('');setConcessionaireFilter('');setOccurredFrom('');setOccurredTo('');void load({});};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');setNotice('');try{const numericAmount=Number(String(amount).replace(',','.'));if(!Number.isFinite(numericAmount)||numericAmount<=0)throw new Error('Informe um valor válido.');const timestamp=new Date(occurredAt);if(!Number.isFinite(timestamp.getTime()))throw new Error('Informe data e hora válidas.');const result=await TollPassageClient.create({plate:plate.trim().toUpperCase(),concessionaire:concessionaire.trim(),road:road.trim(),tollPoint:tollPoint.trim(),occurredAt:timestamp.toISOString(),amount:numericAmount,dueDate:dueDate||undefined,status:'PENDING',source:'MANUAL',sourceReference:sourceReference.trim()||undefined,notes:notes.trim()||undefined});setNotice(result.created?'Passagem registrada. Contrato e motorista foram resolvidos pelo servidor quando havia vínculo único para a data/hora.':'Esta passagem já estava registrada; nenhum duplicado foi criado.');setPlate('');setConcessionaire('');setRoad('');setTollPoint('');setOccurredAt(nowLocal());setAmount('');setDueDate('');setSourceReference('');setNotes('');await load();}catch(err){setError(err instanceof Error?err.message:'Não foi possível registrar a passagem.');}finally{setSaving(false);}};
  return <div className="p-4 sm:p-6 space-y-5">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><div className="flex items-center gap-2"><Route className="w-5 h-5"/><h1 className="text-xl font-semibold">Pedágios / Free Flow</h1></div><p className="text-sm text-slate-500 mt-1">Registro operacional manual. Nenhuma cobrança financeira é criada nesta etapa.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 text-sm hover:bg-slate-100 dark:hover:bg-slate-900 disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Atualizar</button></div>
    {error&&<div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-300">{error}</div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-300">{notice}</div>}
    <form onSubmit={submit} className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 space-y-4"><div className="flex items-center gap-2"><Plus className="w-4 h-4"/><h2 className="font-semibold">Registrar passagem manual</h2></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
      <label className="text-sm">Placa<input value={plate} onChange={e=>setPlate(e.target.value)} required maxLength={8} placeholder="ABC1D23" className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 uppercase"/></label>
      <label className="text-sm">Concessionária<input value={concessionaire} onChange={e=>setConcessionaire(e.target.value)} required maxLength={200} className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Rodovia<input value={road} onChange={e=>setRoad(e.target.value)} required maxLength={200} className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Pórtico / praça<input value={tollPoint} onChange={e=>setTollPoint(e.target.value)} required maxLength={300} className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Data e hora<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)} required className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Valor<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required placeholder="0,00" className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Vencimento<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
      <label className="text-sm">Referência da origem<input value={sourceReference} onChange={e=>setSourceReference(e.target.value)} maxLength={300} placeholder="Opcional" className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label>
    </div><label className="text-sm block">Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={4000} rows={2} className="mt-1 w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2"/></label><div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Motorista, contrato, tenant e chave de idempotência não são enviados pelo formulário; o servidor deriva esses vínculos.</p><button disabled={saving} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-50">{saving?'Salvando...':'Registrar passagem'}</button></div></form>
    <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="p-4 space-y-3 border-b border-slate-200 dark:border-slate-800"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Histórico de passagens</h2><p className="text-xs text-slate-500">{items.length} registro(s) encontrado(s)</p></div><div className="flex items-center gap-2 text-sm text-slate-500"><Filter className="w-4 h-4"/>Filtros server-side</div></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-6 gap-2">
      <select value={vehicleFilter} onChange={e=>setVehicleFilter(e.target.value)} className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"><option value="">Todos os veículos</option>{vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.plate} — {vehicle.brand} {vehicle.model}</option>)}</select>
      <select value={driverFilter} onChange={e=>setDriverFilter(e.target.value)} className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"><option value="">Todos os motoristas</option>{drivers.map(driver=><option key={driver.id} value={driver.id}>{driver.fullName}</option>)}</select>
      <select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as TollPassageStatus|'')} className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"><option value="">Todos os status</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
      <input value={concessionaireFilter} onChange={e=>setConcessionaireFilter(e.target.value)} maxLength={200} placeholder="Concessionária" aria-label="Filtrar por concessionária" className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"/>
      <input type="date" value={occurredFrom} onChange={e=>setOccurredFrom(e.target.value)} aria-label="Passagens a partir de" className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"/>
      <input type="date" value={occurredTo} onChange={e=>setOccurredTo(e.target.value)} aria-label="Passagens até" className="rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"/>
    </div><div className="flex justify-end gap-2"><button type="button" onClick={clearFilters} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 text-sm disabled:opacity-50"><X className="w-4 h-4"/>Limpar</button><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 dark:bg-slate-100 px-3 py-2 text-sm font-medium text-white dark:text-slate-900 disabled:opacity-50"><Filter className="w-4 h-4"/>Aplicar filtros</button></div></div>
      {loading?<div className="p-8 text-center text-sm text-slate-500">Carregando...</div>:items.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhuma passagem encontrada.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-950/40 text-left text-xs text-slate-500"><tr><th className="px-4 py-3">Data/hora</th><th className="px-4 py-3">Veículo</th><th className="px-4 py-3">Local</th><th className="px-4 py-3">Valor</th><th className="px-4 py-3">Vínculo</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{items.map(item=>{const vehicle=vehicleById.get(item.vehicleId),driver=item.driverId?driverById.get(item.driverId):undefined;return <tr key={item.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-3 whitespace-nowrap">{new Date(item.occurredAt).toLocaleString('pt-BR')}</td><td className="px-4 py-3 font-medium">{vehicle?.plate||item.vehicleId}{vehicle&&(vehicle.brand||vehicle.model)&&<div className="text-xs font-normal text-slate-500">{vehicle.brand} {vehicle.model}</div>}</td><td className="px-4 py-3"><div>{item.road} — {item.tollPoint}</div><div className="text-xs text-slate-500">{item.concessionaire}</div></td><td className="px-4 py-3 whitespace-nowrap">{money.format(item.amount)}</td><td className="px-4 py-3 text-xs"><div>{item.contractId?`Contrato ${item.contractId}`:'Sem contrato único'}</div><div className="text-slate-500">{driver?.fullName||(item.driverId?`Motorista ${item.driverId}`:'Sem motorista derivado')}</div></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${statusClass[item.status]}`}>{statusLabel[item.status]}</span></td></tr>;})}</tbody></table></div>}
    </section>
  </div>;
};
