import { sql } from 'drizzle-orm';
import type { MaintenancePlan, OilChangeRecord, TireRecord } from '../../types/entities';

const rows=(r:any):any[]=>Array.isArray(r?.rows)?r.rows:[];
const dateOnly=(v:unknown):string|undefined=>v===null||v===undefined||v===''?undefined:(v instanceof Date?v.toISOString().slice(0,10):String(v).slice(0,10));
const iso=(v:unknown):string=>v instanceof Date?v.toISOString():typeof v==='string'?v:new Date(String(v)).toISOString();
const opt=(v:unknown):string|undefined=>v===null||v===undefined||v===''?undefined:String(v);
const num=(v:unknown):number|undefined=>v===null||v===undefined||v===''?undefined:Number(v);

function mapPlan(r:any):MaintenancePlan{return{id:String(r.id),companyId:String(r.company_id),vehicleId:String(r.vehicle_id),templateId:opt(r.template_id),name:String(r.name),maintenanceType:String(r.maintenance_type),intervalKm:num(r.interval_km),intervalDays:num(r.interval_days),lastExecutionKm:num(r.last_execution_km),lastExecutionDate:dateOnly(r.last_execution_date),nextDueKm:num(r.next_due_km),nextDueDate:dateOnly(r.next_due_date),priority:String(r.priority) as MaintenancePlan['priority'],estimatedCost:num(r.estimated_cost),status:String(r.status) as MaintenancePlan['status'],notes:opt(r.notes),lastWorkOrderId:opt(r.last_work_order_id),cycleSequence:Number(r.cycle_sequence||0),createdBy:String(r.created_by),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
function mapOil(r:any):OilChangeRecord{return{id:String(r.id),companyId:String(r.company_id),vehicleId:String(r.vehicle_id),workOrderId:opt(r.work_order_id),km:Number(r.km),date:dateOnly(r.date)!,oilType:String(r.oil_type),oilBrand:String(r.oil_brand),quantity:Number(r.quantity),filterChanged:Boolean(r.filter_changed),nextKm:Number(r.next_km),nextDate:dateOnly(r.next_date),supplierId:opt(r.supplier_id),attachmentId:opt(r.attachment_id),notes:opt(r.notes),createdBy:opt(r.created_by),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}
function mapTire(r:any):TireRecord{return{id:String(r.id),companyId:String(r.company_id),vehicleId:String(r.vehicle_id),position:String(r.position),brand:String(r.brand),model:String(r.model),measure:opt(r.measure),serialNumber:opt(r.serial_number),installationDate:dateOnly(r.installation_date)!,installationKm:Number(r.installation_km),treadDepth:num(r.tread_depth),status:String(r.status) as TireRecord['status'],lastRotationDate:dateOnly(r.last_rotation_date),lastRotationKm:num(r.last_rotation_km),nextRotationDate:dateOnly(r.next_rotation_date),nextRotationKm:num(r.next_rotation_km),removalDate:dateOnly(r.removal_date),removalKm:num(r.removal_km),removalReason:opt(r.removal_reason),cost:Number(r.cost||0),supplierId:opt(r.supplier_id),attachmentId:opt(r.attachment_id),notes:opt(r.notes),createdBy:opt(r.created_by),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)};}

export class PostgresMaintenancePlanRepository{
  constructor(private readonly tx:any){}
  async findAllByCompany(companyId:string,vehicleId?:string):Promise<MaintenancePlan[]>{const r=vehicleId?await this.tx.execute(sql`SELECT * FROM maintenance_plans WHERE company_id=${companyId} AND vehicle_id=${vehicleId} ORDER BY priority DESC,name,id`):await this.tx.execute(sql`SELECT * FROM maintenance_plans WHERE company_id=${companyId} ORDER BY priority DESC,name,id`);return rows(r).map(mapPlan);}
  async findByIdForCompany(companyId:string,id:string):Promise<MaintenancePlan|null>{const r=await this.tx.execute(sql`SELECT * FROM maintenance_plans WHERE company_id=${companyId} AND id=${id} LIMIT 1`);return rows(r)[0]?mapPlan(rows(r)[0]):null;}
  async findByIdForCompanyWithLock(companyId:string,id:string):Promise<MaintenancePlan|null>{const r=await this.tx.execute(sql`SELECT * FROM maintenance_plans WHERE company_id=${companyId} AND id=${id} FOR UPDATE`);return rows(r)[0]?mapPlan(rows(r)[0]):null;}
  async create(x:MaintenancePlan):Promise<MaintenancePlan>{const r=await this.tx.execute(sql`INSERT INTO maintenance_plans(id,company_id,vehicle_id,name,maintenance_type,interval_km,interval_days,last_execution_km,last_execution_date,next_due_km,next_due_date,priority,estimated_cost,status,notes,last_work_order_id,cycle_sequence,created_by,created_at,updated_at) VALUES(${x.id},${x.companyId},${x.vehicleId},${x.name},${x.maintenanceType},${x.intervalKm??null},${x.intervalDays??null},${x.lastExecutionKm??null},${x.lastExecutionDate??null},${x.nextDueKm??null},${x.nextDueDate??null},${x.priority},${x.estimatedCost??null},${x.status},${x.notes??null},${x.lastWorkOrderId??null},${x.cycleSequence},${x.createdBy},${x.createdAt},${x.updatedAt}) RETURNING *`);return mapPlan(rows(r)[0]);}
  async save(companyId:string,id:string,x:MaintenancePlan):Promise<MaintenancePlan|null>{const r=await this.tx.execute(sql`UPDATE maintenance_plans SET name=${x.name},maintenance_type=${x.maintenanceType},interval_km=${x.intervalKm??null},interval_days=${x.intervalDays??null},last_execution_km=${x.lastExecutionKm??null},last_execution_date=${x.lastExecutionDate??null},next_due_km=${x.nextDueKm??null},next_due_date=${x.nextDueDate??null},priority=${x.priority},estimated_cost=${x.estimatedCost??null},status=${x.status},notes=${x.notes??null},last_work_order_id=${x.lastWorkOrderId??null},cycle_sequence=${x.cycleSequence},updated_at=${x.updatedAt} WHERE company_id=${companyId} AND id=${id} RETURNING *`);return rows(r)[0]?mapPlan(rows(r)[0]):null;}
}

export class PostgresOilChangeRepository{
  constructor(private readonly tx:any){}
  async findAllByCompany(companyId:string,vehicleId?:string):Promise<OilChangeRecord[]>{const r=vehicleId?await this.tx.execute(sql`SELECT * FROM oil_change_records WHERE company_id=${companyId} AND vehicle_id=${vehicleId} ORDER BY date DESC,km DESC,id DESC`):await this.tx.execute(sql`SELECT * FROM oil_change_records WHERE company_id=${companyId} ORDER BY date DESC,km DESC,id DESC`);return rows(r).map(mapOil);}
  async findByWorkOrder(companyId:string,workOrderId:string):Promise<OilChangeRecord|null>{const r=await this.tx.execute(sql`SELECT * FROM oil_change_records WHERE company_id=${companyId} AND work_order_id=${workOrderId} LIMIT 1`);return rows(r)[0]?mapOil(rows(r)[0]):null;}
  async create(x:OilChangeRecord):Promise<OilChangeRecord>{const r=await this.tx.execute(sql`INSERT INTO oil_change_records(id,company_id,vehicle_id,work_order_id,km,date,oil_type,oil_brand,quantity,filter_changed,next_km,next_date,supplier_id,attachment_id,notes,created_by,created_at,updated_at) VALUES(${x.id},${x.companyId},${x.vehicleId},${x.workOrderId??null},${x.km},${x.date},${x.oilType},${x.oilBrand},${String(x.quantity)},${x.filterChanged},${x.nextKm},${x.nextDate??null},${x.supplierId??null},${x.attachmentId??null},${x.notes??null},${x.createdBy??x.companyId},${x.createdAt},${x.updatedAt}) RETURNING *`);return mapOil(rows(r)[0]);}
}

export class PostgresTireRepository{
  constructor(private readonly tx:any){}
  async findAllByCompany(companyId:string,vehicleId?:string):Promise<TireRecord[]>{const r=vehicleId?await this.tx.execute(sql`SELECT * FROM tire_records WHERE company_id=${companyId} AND vehicle_id=${vehicleId} ORDER BY status,position,id`):await this.tx.execute(sql`SELECT * FROM tire_records WHERE company_id=${companyId} ORDER BY status,vehicle_id,position,id`);return rows(r).map(mapTire);}
  async findByIdForCompanyWithLock(companyId:string,id:string):Promise<TireRecord|null>{const r=await this.tx.execute(sql`SELECT * FROM tire_records WHERE company_id=${companyId} AND id=${id} FOR UPDATE`);return rows(r)[0]?mapTire(rows(r)[0]):null;}
  async create(x:TireRecord):Promise<TireRecord>{const r=await this.tx.execute(sql`INSERT INTO tire_records(id,company_id,vehicle_id,position,brand,model,measure,serial_number,installation_date,installation_km,tread_depth,status,last_rotation_date,last_rotation_km,next_rotation_date,next_rotation_km,removal_date,removal_km,removal_reason,cost,supplier_id,attachment_id,notes,created_by,created_at,updated_at) VALUES(${x.id},${x.companyId},${x.vehicleId},${x.position},${x.brand},${x.model},${x.measure??null},${x.serialNumber??null},${x.installationDate},${x.installationKm},${x.treadDepth??null},${x.status},${x.lastRotationDate??null},${x.lastRotationKm??null},${x.nextRotationDate??null},${x.nextRotationKm??null},${x.removalDate??null},${x.removalKm??null},${x.removalReason??null},${String(x.cost)},${x.supplierId??null},${x.attachmentId??null},${x.notes??null},${x.createdBy??x.companyId},${x.createdAt},${x.updatedAt}) RETURNING *`);return mapTire(rows(r)[0]);}
  async save(companyId:string,id:string,x:TireRecord):Promise<TireRecord|null>{const r=await this.tx.execute(sql`UPDATE tire_records SET position=${x.position},brand=${x.brand},model=${x.model},measure=${x.measure??null},serial_number=${x.serialNumber??null},tread_depth=${x.treadDepth??null},status=${x.status},last_rotation_date=${x.lastRotationDate??null},last_rotation_km=${x.lastRotationKm??null},next_rotation_date=${x.nextRotationDate??null},next_rotation_km=${x.nextRotationKm??null},removal_date=${x.removalDate??null},removal_km=${x.removalKm??null},removal_reason=${x.removalReason??null},cost=${String(x.cost)},supplier_id=${x.supplierId??null},attachment_id=${x.attachmentId??null},notes=${x.notes??null},updated_at=${x.updatedAt} WHERE company_id=${companyId} AND id=${id} RETURNING *`);return rows(r)[0]?mapTire(rows(r)[0]):null;}
}
