from pathlib import Path

Path('src/api/__tests__/driverClientTestRunner.ts').write_text(r'''import { DriverApiError,DriverClient } from '../driverClient';
import { DriverStatus,DocumentStatus } from '../../types/enums';
const driver={id:'drv-1',companyId:'company-a',fullName:'João da Silva',cpf:'52998224725',birthDate:'1990-01-01',phone:'11999999999',whatsapp:'11999999999',address:{street:'Rua A',number:'10',neighborhood:'Centro',city:'São Paulo',state:'SP',zipCode:'01001000'},cnhNumber:'12345678',cnhCategory:'B',cnhExpiration:'2099-12-31',cnhStatus:DocumentStatus.VALID,appPlatforms:['Uber'],status:DriverStatus.ACTIVE,isArchived:false,createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'};
export class DriverClientTestRunner{static async runAllTests(){const original=globalThis.fetch;let passed=0;const tests:Array<()=>Promise<void>>=[];
tests.push(async()=>{let c:RequestCredentials|undefined;globalThis.fetch=(async(_i:any,init?:RequestInit)=>{c=init?.credentials;return new Response(JSON.stringify({items:[driver]}),{status:200});}) as typeof fetch;const x=await DriverClient.list();if(x.length!==1||c!=='include')throw new Error('LIST');});
tests.push(async()=>{globalThis.fetch=(async()=>new Response(JSON.stringify({item:driver}),{status:200})) as typeof fetch;if((await DriverClient.get('drv 1')).id!=='drv-1')throw new Error('GET');});
tests.push(async()=>{let body:any={};globalThis.fetch=(async(_i:any,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({item:driver}),{status:201});}) as typeof fetch;await DriverClient.create({fullName:'João da Silva',cpf:'52998224725',birthDate:'1990-01-01',phone:'11999999999',address:driver.address,cnhNumber:'12345678',cnhCategory:'B',cnhExpiration:'2099-12-31'});for(const k of ['companyId','userId','userName','role','status','isArchived','currentVehicleId','currentContractId','healthAndEmergency'])if(k in body)throw new Error('create leak '+k);});
tests.push(async()=>{let body:any={};globalThis.fetch=(async(_i:any,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({item:{...driver,phone:'11888888888'}}),{status:200});}) as typeof fetch;await DriverClient.update('drv-1',{phone:'11888888888'});if(body.phone!=='11888888888')throw new Error('UPDATE');for(const k of ['companyId','status','isArchived','healthAndEmergency'])if(k in body)throw new Error('update leak '+k);});
tests.push(async()=>{let body:any={};globalThis.fetch=(async(_i:any,init?:RequestInit)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({item:{...driver,status:DriverStatus.BLOCKED}}),{status:200});}) as typeof fetch;await DriverClient.changeStatus('drv-1',DriverStatus.BLOCKED,'Motivo');if(body.status!==DriverStatus.BLOCKED||body.reason!=='Motivo')throw new Error('STATUS');});
tests.push(async()=>{let method='';globalThis.fetch=(async(_i:any,init?:RequestInit)=>{method=String(init?.method);return new Response(JSON.stringify({item:{...driver,status:DriverStatus.ARCHIVED,isArchived:true}}),{status:200});}) as typeof fetch;const x=await DriverClient.archive('drv-1');if(method!=='POST'||!x.isArchived)throw new Error('ARCHIVE');});
tests.push(async()=>{globalThis.fetch=(async()=>new Response(JSON.stringify({error:'Unauthorized'}),{status:401})) as typeof fetch;let e:unknown;try{await DriverClient.list();}catch(x){e=x;}if(!(e instanceof DriverApiError)||e.status!==401)throw new Error('401');});
tests.push(async()=>{globalThis.fetch=(async()=>new Response(JSON.stringify({error:'Forbidden'}),{status:403})) as typeof fetch;let e:unknown;try{await DriverClient.archive('drv-1');}catch(x){e=x;}if(!(e instanceof DriverApiError)||e.status!==403)throw new Error('403');});
tests.push(async()=>{globalThis.fetch=(async()=>new Response(JSON.stringify({item:{...driver,status:'ROOT'}}),{status:200})) as typeof fetch;let failed=false;try{await DriverClient.get('drv-1');}catch{failed=true;}if(!failed)throw new Error('bad status');});
tests.push(async()=>{globalThis.fetch=(async()=>new Response(JSON.stringify({items:[{...driver,address:null}]}),{status:200})) as typeof fetch;let failed=false;try{await DriverClient.list();}catch{failed=true;}if(!failed)throw new Error('bad address');});
try{for(const t of tests){await t();passed++;}}finally{globalThis.fetch=original;}const result={passed,failed:tests.length-passed,total:tests.length};console.log(`DriverClient ${passed}/${tests.length} PASS`);return result;}}
if(process.argv[1]?.includes('driverClientTestRunner'))DriverClientTestRunner.runAllTests().then(r=>{if(r.failed)process.exit(1);}).catch(e=>{console.error(e);process.exit(1);});
''',encoding='utf-8')
