import fs from 'node:fs';
import { spawn } from 'node:child_process';
import { Pool } from 'pg';
import { hashPassword } from '../src/server/password';

const adminUrl='postgres://postgres:postgres@127.0.0.1:5432/autoerp_ci';
const appUrl='postgres://autoerp_i2_app:autoerp_i2_pass@127.0.0.1:5432/autoerp_ci';
const base='http://127.0.0.1:3000';
const password='StrongPass123!';
const payload={fullName:'João da Silva',cpf:'52998224725',rg:'123456789',birthDate:'1990-01-01',phone:'11999999999',whatsapp:'11999999999',email:'joao@example.test',address:{street:'Rua A',number:'10',neighborhood:'Centro',city:'São Paulo',state:'SP',zipCode:'01001000'},cnhNumber:'12345678',cnhCategory:'B',cnhExpiration:'2099-12-31',appPlatforms:['Uber','99'],notes:'I2'};

async function seed(){const db=new Pool({connectionString:adminUrl});for(const f of ['drizzle/0000_milky_invisible_woman.sql','drizzle/0001_rls_and_audit.sql','drizzle/0002_phase1_final_hardening.sql','drizzle/0003_auth_credentials.sql','drizzle/0004_payment_methods_rls_permissive.sql','drizzle/0005_financial_periods_rls_permissive.sql','drizzle/0006_security_deposit_authority.sql','drizzle/0007_driver_health_profiles.sql','drizzle/0008_vehicle_core_authority.sql','drizzle/0009_vehicle_km_authority.sql'])await db.query(fs.readFileSync(f,'utf8'));
await db.query(`INSERT INTO companies(id,document,name,status) VALUES ('company-i2-a','31313131000131','I2 A','ACTIVE'),('company-i2-b','32323232000132','I2 B','ACTIVE')`);
await db.query(`INSERT INTO drivers(id,company_id,name,cpf,cnh,active) VALUES ('legacy-driver','company-i2-a','Legacy Driver','11144477735','87654321',false)`);
const m10=fs.readFileSync('drizzle/0010_driver_core_authority.sql','utf8');await db.query(m10);let q=await db.query(`SELECT status,active,phone,cnh_category,is_archived FROM drivers WHERE id='legacy-driver'`);if(q.rowCount!==1||q.rows[0].status!=='INACTIVE'||q.rows[0].active!==false||q.rows[0].phone!==''||q.rows[0].cnh_category!=='B'||q.rows[0].is_archived!==false)throw new Error('legacy backfill failed');await db.query(`UPDATE drivers SET status='BLOCKED' WHERE id='legacy-driver'`);await db.query(m10);q=await db.query(`SELECT status FROM drivers WHERE id='legacy-driver'`);if(q.rows[0].status!=='BLOCKED')throw new Error('migration rerun overwrote status');console.log('I2_MIGRATION_BACKFILL=PASS');
await db.query(`INSERT INTO users(id,company_id,name,email,role,active,permissions) VALUES ('i2-admin-a','company-i2-a','Admin I2 A','admin-a@i2.test','ADMIN',true,ARRAY['*']),('i2-readonly-a','company-i2-a','Readonly I2 A','readonly-a@i2.test','READONLY',true,ARRAY[]::text[]),('i2-admin-b','company-i2-b','Admin I2 B','admin-b@i2.test','ADMIN',true,ARRAY['*'])`);const hashes=await Promise.all([password,password,password].map(hashPassword));for(const [c,u,h] of [['company-i2-a','i2-admin-a',hashes[0]],['company-i2-a','i2-readonly-a',hashes[1]],['company-i2-b','i2-admin-b',hashes[2]]])await db.query('INSERT INTO user_credentials(company_id,user_id,password_hash) VALUES ($1,$2,$3)',[c,u,h]);
await db.query(`CREATE ROLE autoerp_i2_app LOGIN PASSWORD 'autoerp_i2_pass'`);await db.query(`GRANT USAGE ON SCHEMA public TO autoerp_i2_app`);await db.query(`GRANT SELECT ON companies,users,user_credentials TO autoerp_i2_app`);await db.query(`GRANT SELECT,INSERT,UPDATE ON drivers,driver_health_profiles TO autoerp_i2_app`);await db.query(`GRANT SELECT ON vehicles TO autoerp_i2_app`);await db.query(`GRANT INSERT ON audit_logs TO autoerp_i2_app`);await db.end();}
async function login(document:string,email:string){const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({companyDocument:document,email,password})});if(r.status!==200)throw new Error(`login ${email} ${r.status} ${await r.text()}`);const c=r.headers.get('set-cookie');if(!c)throw new Error('cookie missing');return c.split(';')[0];}
async function req(method:string,path:string,cookie?:string,body?:unknown){return fetch(base+path,{method,headers:{...(cookie?{cookie}:{}),...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});}

async function main(){await seed();let logs='';const server=spawn('node',['dist/server.mjs'],{env:{...process.env,NODE_ENV:'production',USE_PGLITE:'false',ALLOW_MOCK_AUTH:'false',DATABASE_URL:appUrl,JWT_SECRET:'security-2i2-secret-at-least-32-bytes',JWT_ISSUER:'autoerp-ci',JWT_AUDIENCE:'autoerp-users'},stdio:['ignore','pipe','pipe']});server.stdout?.on('data',d=>logs+=String(d));server.stderr?.on('data',d=>logs+=String(d));try{for(let i=0;i<40;i++){try{if((await fetch(base+'/api/auth/me')).status===401)break;}catch{}if(i===39)throw new Error('server not ready '+logs);await new Promise(r=>setTimeout(r,500));}
let r=await req('GET','/api/drivers');if(r.status!==401)throw new Error(`no-session list ${r.status}`);r=await req('POST','/api/drivers',undefined,payload);if(r.status!==401)throw new Error(`no-session create ${r.status}`);console.log('I2_NO_SESSION=PASS');
const adminA=await login('31313131000131','admin-a@i2.test');const readonlyA=await login('31313131000131','readonly-a@i2.test');const adminB=await login('32323232000132','admin-b@i2.test');
r=await req('POST','/api/drivers',adminA,{...payload,companyId:'company-i2-b',userId:'forged',userName:'Forged',role:'ADMIN',status:'ARCHIVED',isArchived:true,currentVehicleId:'evil-vehicle',currentContractId:'evil-contract',healthAndEmergency:{bloodType:'AB+'}});if(r.status!==201)throw new Error(`create A ${r.status} ${await r.text()}`);const a=(await r.json()).item;if(a.companyId!=='company-i2-a'||a.status!=='ACTIVE'||a.isArchived!==false||a.currentVehicleId||a.currentContractId||a.healthAndEmergency)throw new Error('create authority failed');console.log('I2_CREATE_SERVER_AUTHORITY=PASS');
r=await req('POST','/api/drivers',adminB,payload);if(r.status!==201)throw new Error(`same identifiers other tenant ${r.status} ${await r.text()}`);const b=(await r.json()).item;if(b.companyId!=='company-i2-b')throw new Error('tenant B create');console.log('I2_TENANT_UNIQUENESS=PASS');
r=await req('GET','/api/drivers',adminA);let body=await r.json();if(r.status!==200||body.items.some((x:any)=>x.companyId!=='company-i2-a')||body.items.some((x:any)=>x.id===b.id))throw new Error('list tenant leak');r=await req('GET',`/api/drivers/${b.id}`,adminA);if(r.status!==404)throw new Error(`cross tenant get ${r.status}`);console.log('I2_TENANT_ISOLATION=PASS');
r=await req('GET','/api/drivers',readonlyA);if(r.status!==200)throw new Error('readonly list');r=await req('POST','/api/drivers',readonlyA,{...payload,cpf:'12345678909',cnhNumber:'23456789'});if(r.status!==403)throw new Error(`readonly create ${r.status}`);r=await req('PATCH',`/api/drivers/${a.id}`,readonlyA,{phone:'11888888888'});if(r.status!==403)throw new Error(`readonly edit ${r.status}`);r=await req('POST',`/api/drivers/${a.id}/archive`,readonlyA);if(r.status!==403)throw new Error(`readonly archive ${r.status}`);console.log('I2_READONLY_RBAC=PASS');
r=await req('POST','/api/drivers',adminA,{...payload,cnhNumber:'23456789'});if(r.status!==409)throw new Error(`duplicate cpf ${r.status}`);r=await req('POST','/api/drivers',adminA,{...payload,cpf:'12345678909'});if(r.status!==409)throw new Error(`duplicate cnh ${r.status}`);console.log('I2_DUPLICATE_409=PASS');
for(const bad of [{...payload,fullName:'A',cpf:'12345678909',cnhNumber:'23456789'},{...payload,cpf:'00000000000',cnhNumber:'23456789'},{...payload,cpf:'12345678909',cnhNumber:'11111111'},{...payload,cpf:'12345678909',cnhNumber:'23456789',birthDate:'2999-01-01'},{...payload,cpf:'12345678909',cnhNumber:'23456789',phone:''},{...payload,cpf:'12345678909',cnhNumber:'23456789',cnhExpiration:'2099-02-30'}]){r=await req('POST','/api/drivers',adminA,bad);if(r.status!==400)throw new Error(`validation expected 400 got ${r.status}`);}console.log('I2_VALIDATION=PASS');
r=await req('POST','/api/drivers',adminA,{...payload,cpf:'12345678909',cnhNumber:'23456789',fullName:'Expired Driver',cnhExpiration:'2000-01-01'});if(r.status!==201)throw new Error(`expired create ${r.status}`);const expired=(await r.json()).item;if(expired.status!=='BLOCKED')throw new Error('expired CNH not blocked');r=await req('PATCH',`/api/drivers/${expired.id}/status`,adminA,{status:'ACTIVE',reason:'Tentativa'});if(r.status!==400)throw new Error(`expired unblock ${r.status}`);console.log('I2_EXPIRED_CNH_BLOCK=PASS');
r=await req('PATCH',`/api/drivers/${a.id}`,adminA,{status:'BLOCKED'});if(r.status!==400)throw new Error(`generic status mutation ${r.status}`);r=await req('PATCH',`/api/drivers/${a.id}`,adminA,{companyId:'company-i2-b'});if(r.status!==400)throw new Error(`generic company mutation ${r.status}`);r=await req('PATCH',`/api/drivers/${a.id}`,adminA,{phone:'11888888888'});if(r.status!==200||(await r.json()).item.phone!=='11888888888')throw new Error('valid patch');console.log('I2_PATCH_AUTHORITY=PASS');
r=await req('PATCH',`/api/drivers/${a.id}/status`,adminA,{status:'BLOCKED'});if(r.status!==400)throw new Error('block without reason');r=await req('PATCH',`/api/drivers/${a.id}/status`,adminA,{status:'BLOCKED',reason:'Atraso documental'});if(r.status!==200||(await r.json()).item.status!=='BLOCKED')throw new Error('block');r=await req('PATCH',`/api/drivers/${a.id}/status`,adminA,{status:'ACTIVE',reason:'Regularizado'});if(r.status!==200||(await r.json()).item.status!=='ACTIVE')throw new Error('unblock');console.log('I2_STATUS=PASS');
const db=new Pool({connectionString:adminUrl});await db.query(`INSERT INTO vehicles(id,company_id,plate,renavam,brand,model,status,current_driver_id,current_contract_id) VALUES ('i2-veh-a','company-i2-a','I2A1B23','77777777777','Fiat','Argo','RENTED',$1,'contract-server')`,[a.id]);r=await req('GET',`/api/drivers/${a.id}`,adminA);body=await r.json();if(r.status!==200||body.item.currentVehicleId!=='i2-veh-a'||body.item.currentContractId!=='contract-server')throw new Error('server Vehicle enrichment');console.log('I2_SERVER_LINK_ENRICHMENT=PASS');
r=await req('GET','/api/drivers/does-not-exist/health',adminA);if(r.status!==404)throw new Error(`orphan health GET ${r.status}`);r=await req('PUT','/api/drivers/does-not-exist/health',adminA,{health:{bloodType:'O+'}});if(r.status!==404)throw new Error(`orphan health PUT ${r.status}`);r=await req('PUT',`/api/drivers/${b.id}/health`,adminA,{health:{bloodType:'O+'}});if(r.status!==404)throw new Error(`cross tenant health PUT ${r.status}`);let q=await db.query(`SELECT count(*)::int c FROM driver_health_profiles WHERE driver_id IN ('does-not-exist',$1)`,[b.id]);if(q.rows[0].c!==0)throw new Error('orphan/cross health profile created');r=await req('GET',`/api/drivers/${a.id}/health`,adminA);if(r.status!==200)throw new Error(`health GET existing ${r.status}`);r=await req('PUT',`/api/drivers/${a.id}/health`,adminA,{health:{bloodType:'O+',emergencyContactName:'Maria'}});if(r.status!==200||(await r.json()).health.bloodType!=='O+')throw new Error('health PUT existing');console.log('I2_HEALTH_CORE_EXISTENCE=PASS');
q=await db.query(`SELECT user_id,changes FROM audit_logs WHERE company_id='company-i2-a' AND entity_type='Driver' ORDER BY timestamp`);if((q.rowCount||0)<4||q.rows.some(x=>x.user_id!=='i2-admin-a'))throw new Error('audit principal mismatch');const audit=JSON.stringify(q.rows);if(!audit.includes('Admin I2 A')||audit.includes('Forged'))throw new Error('browser audit identity leak');console.log('I2_AUDIT_PRINCIPAL=PASS');
await db.query(`CREATE OR REPLACE FUNCTION i2_fail_driver_audit() RETURNS trigger AS $$ BEGIN IF NEW.entity_type='Driver' THEN RAISE EXCEPTION 'forced driver audit failure'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`);await db.query(`CREATE TRIGGER i2_fail_driver_audit_trigger BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION i2_fail_driver_audit()`);r=await req('PATCH',`/api/drivers/${a.id}`,adminA,{phone:'11777777777'});if(r.status<500)throw new Error(`forced audit failure ${r.status}`);await db.query(`DROP TRIGGER i2_fail_driver_audit_trigger ON audit_logs`);await db.query(`DROP FUNCTION i2_fail_driver_audit()`);q=await db.query('SELECT phone FROM drivers WHERE id=$1',[a.id]);if(q.rows[0].phone!=='11888888888')throw new Error('Driver mutation survived audit failure');console.log('I2_ATOMIC_AUDIT_ROLLBACK=PASS');
r=await req('POST',`/api/drivers/${a.id}/archive`,adminA);if(r.status!==200)throw new Error(`archive ${r.status}`);const archived=(await r.json()).item;if(archived.status!=='ARCHIVED'||archived.isArchived!==true)throw new Error('archive response');q=await db.query('SELECT status,is_archived,active FROM drivers WHERE id=$1',[a.id]);if(q.rowCount!==1||q.rows[0].status!=='ARCHIVED'||q.rows[0].is_archived!==true||q.rows[0].active!==false)throw new Error('soft archive db');r=await req('GET',`/api/drivers/${a.id}`,adminA);if(r.status!==404)throw new Error('archived driver exposed');console.log('I2_SOFT_ARCHIVE=PASS');
q=await db.query(`SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='drivers'`);if(q.rowCount!==1||!q.rows[0].relrowsecurity||!q.rows[0].relforcerowsecurity)throw new Error('Driver RLS/FORCE missing');q=await db.query(`SELECT permissive,qual,with_check FROM pg_policies WHERE tablename='drivers' AND policyname='tenant_isolation_dr'`);if(q.rowCount!==1||q.rows[0].permissive!=='PERMISSIVE'||!q.rows[0].qual||!q.rows[0].with_check)throw new Error('Driver RLS policy missing');await db.end();
const appDb=new Pool({connectionString:appUrl});const client=await appDb.connect();try{await client.query('BEGIN');await client.query(`SELECT set_config('app.current_tenant','company-i2-a',true)`);q=await client.query(`SELECT DISTINCT company_id FROM drivers`);if(q.rows.some(x=>x.company_id!=='company-i2-a'))throw new Error('direct Driver RLS read leak');await client.query('ROLLBACK');await client.query('BEGIN');await client.query(`SELECT set_config('app.current_tenant','company-i2-a',true)`);let blocked=false;try{await client.query(`INSERT INTO drivers(id,company_id,name,cpf,cnh,active,status,app_platforms) VALUES ('forged-i2','company-i2-b','Forged','93541134780','34567890',true,'ACTIVE',ARRAY['Uber'])`);}catch{blocked=true;}await client.query('ROLLBACK');if(!blocked)throw new Error('Driver WITH CHECK accepted foreign tenant');}finally{client.release();await appDb.end();}console.log('I2_POSTGRES16_RLS=PASS');
}finally{server.kill('SIGTERM');}}
main().catch(e=>{console.error('I2_VALIDATION_FATAL',e);process.exit(2);});
