import React, { useState, useEffect, useCallback, Dispatch, SetStateAction } from 'react';
import {
  ContaReceber,
  ContaPagar,
  CategoriaFinanceira,
  FormaPagamentoItem,
  RegistroInadimplenciaContato,
  Contrato,
  Veiculo,
  Motorista,
  Manutencao,
  Documento,
  Apolice,
  Rastreador,
  Pagamento
} from '../types';
import {
  initialContasReceber,
  initialContasPagar,
  initialCategoriasFinanceiras,
  initialFormasPagamento
} from '../data';

export function useFinanceiroSystem(
  contratos: Contrato[],
  veiculos: Veiculo[],
  motoristas: Motorista[],
  manutencoes: Manutencao[],
  documentos: Documento[],
  apolices: Apolice[],
  rastreadores: Rastreador[],
  pagamentos: Pagamento[],
  onUpdatePagamentos?: Dispatch<SetStateAction<Pagamento[]>>
) {
  // 1. Core Reactive States initialized from LocalStorage
  const [contasReceber, setContasReceber] = useState<ContaReceber[]>(() => {
    const local = localStorage.getItem('auto_erp_contas_receber_v2');
    if (local) {
      try { return JSON.parse(local); } catch (e) { console.error(e); }
    }
    return initialContasReceber as ContaReceber[];
  });

  const [transacoes, setTransacoes] = useState<any[]>(() => {
    const saved = localStorage.getItem('auto_erp_transacoes_v1');
    return saved ? JSON.parse(saved) : [];
  });

  const [contasPagar, setContasPagar] = useState<ContaPagar[]>(() => {
    const local = localStorage.getItem('auto_erp_contas_pagar_v2');
    if (local) {
      try { return JSON.parse(local); } catch (e) { console.error(e); }
    }
    return initialContasPagar as ContaPagar[];
  });

  const [categorias, setCategorias] = useState<CategoriaFinanceira[]>(() => {
    const local = localStorage.getItem('auto_erp_categorias_fin_v2');
    if (local) {
      try { return JSON.parse(local); } catch (e) { console.error(e); }
    }
    return initialCategoriasFinanceiras as CategoriaFinanceira[];
  });

  const [formasPagamento, setFormasPagamento] = useState<FormaPagamentoItem[]>(() => {
    const local = localStorage.getItem('auto_erp_formas_pagamento_v2');
    if (local) {
      try { return JSON.parse(local); } catch (e) { console.error(e); }
    }
    return initialFormasPagamento as FormaPagamentoItem[];
  });

  const [historicoInadimplencia, setHistoricoInadimplencia] = useState<RegistroInadimplenciaContato[]>(() => {
    const local = localStorage.getItem('auto_erp_historico_inadimplencia_v2');
    if (local) {
      try { return JSON.parse(local); } catch (e) { console.error(e); }
    }
    return [];
  });

  // Save to LocalStorage
  useEffect(() => {
    localStorage.setItem('auto_erp_contas_receber_v2', JSON.stringify(contasReceber));
  }, [contasReceber]);
  
  useEffect(() => {
    localStorage.setItem('auto_erp_transacoes_v1', JSON.stringify(transacoes));
  }, [transacoes]);

  useEffect(() => {
    localStorage.setItem('auto_erp_contas_pagar_v2', JSON.stringify(contasPagar));
  }, [contasPagar]);

  useEffect(() => {
    localStorage.setItem('auto_erp_categorias_fin_v2', JSON.stringify(categorias));
  }, [categorias]);

  useEffect(() => {
    localStorage.setItem('auto_erp_formas_pagamento_v2', JSON.stringify(formasPagamento));
  }, [formasPagamento]);

  useEffect(() => {
    localStorage.setItem('auto_erp_historico_inadimplencia_v2', JSON.stringify(historicoInadimplencia));
  }, [historicoInadimplencia]);

  // One-time deduplication to clean up duplicates generated by previous buggy auto-sync
  useEffect(() => {
    const hasDeduplicated = localStorage.getItem('auto_erp_v2_dedup_done_v1');
    if (!hasDeduplicated) {
      setContasReceber(prev => {
        const map = new Map<string, ContaReceber>();
        prev.forEach(cr => {
          if (cr.origemTipo && cr.origemTipo !== 'manual') {
            const key = `${cr.origemTipo}-${cr.origemId}-${cr.dataVencimento}-${cr.valorFinal}`;
            if (!map.has(key)) map.set(key, cr);
          } else {
            map.set(cr.id, cr);
          }
        });
        return Array.from(map.values());
      });

      setContasPagar(prev => {
        const map = new Map<string, ContaPagar>();
        prev.forEach(cp => {
          if (cp.origemTipo && cp.origemTipo !== 'manual') {
            const key = `${cp.origemTipo}-${cp.origemId}-${cp.dataVencimento}-${cp.valorFinal}`;
            if (!map.has(key)) map.set(key, cp);
          } else {
            map.set(cp.id, cp);
          }
        });
        return Array.from(map.values());
      });
      
      localStorage.setItem('auto_erp_v2_dedup_done_v1', 'true');
    }
  }, []);

  // 2. INTEGRAÇÃO AUTOMÁTICA UNIFICADA E RESILIENTE
  // A sincronização via useEffect foi desativada e substituída 
  // por chamadas diretas no App.tsx para prevenir duplicidades 
  // e respeitar a REGRA DE UMA ÚNICA ORIGEM.
  // (Sincronizações de Contratos, Manutenções, Seguros, Rastreadores, IPVA, etc.)

  // Atualizador de status por data (Vencidos vs Em Aberto)
  useEffect(() => {
    const todayStr = new Date().toISOString().split('T')[0];

    setContasReceber(prev => {
      let changed = false;
      const updated = prev.map(r => {
        if (r.status === 'Recebido' || r.status === 'Cancelado' || r.status === 'Renegociado') return r;
        const shouldBeOverdue = r.dataVencimento < todayStr;
        if (shouldBeOverdue && r.status !== 'Vencido') {
          changed = true;
          return { ...r, status: 'Vencido' as const };
        } else if (!shouldBeOverdue && r.status === 'Vencido' && r.saldoDevedor === r.valorFinal) {
          changed = true;
          return { ...r, status: 'Em aberto' as const };
        }
        return r;
      });
      return changed ? updated : prev;
    });

    setContasPagar(prev => {
      let changed = false;
      const updated = prev.map(p => {
        if (p.status === 'Pago' || p.status === 'Cancelado' || p.status === 'Contestação' || p.status === 'Renegociado') return p;
        const shouldBeOverdue = p.dataVencimento < todayStr;
        if (shouldBeOverdue && p.status !== 'Vencido') {
          changed = true;
          return { ...p, status: 'Vencido' as const };
        } else if (!shouldBeOverdue && p.status === 'Vencido' && p.saldoDevedor === p.valorFinal) {
          changed = true;
          return { ...p, status: 'Em aberto' as const };
        }
        return p;
      });
      return changed ? updated : prev;
    });
  }, []);

  // 3. AÇÕES CONTAS A RECEBER
  const registrarRecebimento = useCallback((
    id: string,
    valorPagoInput: number,
    forma: string,
    dataRecebimento: string,
    desconto = 0,
    juros = 0,
    multa = 0,
    obs = ''
  ) => {
    setContasReceber(prev => prev.map(item => {
      if (item.id !== id) return item;

      const valorCalculado = (item.valorOriginal - desconto) + juros + multa;
      const novoTotalRecebido = item.valorRecebido + valorPagoInput;
      const novoSaldo = Math.max(0, valorCalculado - novoTotalRecebido);

      let novoStatus: ContaReceber['status'] = 'Recebido';
      if (novoSaldo > 0) {
        novoStatus = 'Parcialmente recebido';
      }

      const historicoNovo = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: novoSaldo === 0 ? 'Recebido Total' : 'Recebido Parcial',
          valorAnterior: item.saldoDevedor,
          valorNovo: novoSaldo,
          observacao: `Pagamento R$ ${valorPagoInput.toFixed(2)} via ${forma}. Obs: ${obs}`
        }
      ];

      return {
        ...item,
        desconto,
        juros,
        multa,
        valorFinal: valorCalculado,
        valorRecebido: novoTotalRecebido,
        saldoDevedor: novoSaldo,
        formaPagamento: forma,
        dataRealRecebimento: dataRecebimento,
        status: novoStatus,
        observacoes: obs ? `${item.observacoes || ''}\n[Recebimento]: ${obs}` : item.observacoes,
        historico: historicoNovo
      };
    }));
  }, []);

  const estornarRecebimento = useCallback((id: string, motivo: string) => {
    setContasReceber(prev => prev.map(item => {
      if (item.id !== id) return item;

      const todayStr = new Date().toISOString().split('T')[0];
      const isOverdue = item.dataVencimento < todayStr;

      const historicoNovo = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Administrador Financeiro',
          acao: 'Estorno',
          valorAnterior: item.valorRecebido,
          valorNovo: 0,
          observacao: `Estorno realizado. Motivo: ${motivo}`
        }
      ];

      return {
        ...item,
        valorRecebido: 0,
        saldoDevedor: item.valorFinal,
        status: isOverdue ? 'Vencido' : 'Em aberto',
        dataRealRecebimento: undefined,
        historico: historicoNovo
      };
    }));
  }, []);

  const addContaReceber = useCallback((nova: Omit<ContaReceber, 'id' | 'numeroLancamento'>) => {
    setContasReceber(prev => {
      const launchNum = `REC-${new Date().getFullYear()}-${String(prev.length + 1).padStart(3, '0')}`;
      const item: ContaReceber = {
        ...nova,
        id: `rec-manual-${Date.now()}`,
        numeroLancamento: launchNum,
        historico: [
          {
            id: `h-${Date.now()}`,
            dataHora: new Date().toLocaleString('pt-BR'),
            usuario: 'Operador Financeiro',
            acao: 'Criado',
            observacao: 'Lançamento de conta a receber cadastrado manualmente'
          }
        ]
      };
      return [item, ...prev];
    });
  }, []);

  const editContaReceber = useCallback((id: string, dados: Partial<ContaReceber>) => {
    setContasReceber(prev => prev.map(item => {
      if (item.id !== id) return item;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: 'Editado',
          observacao: 'Dados do lançamento atualizados'
        }
      ];

      return { ...item, ...dados, historico: hist };
    }));
  }, []);

  const cancelContaReceber = useCallback((id: string, motivo: string) => {
    setContasReceber(prev => prev.map(item => {
      if (item.id !== id) return item;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: 'Cancelado',
          observacao: `Lançamento cancelado. Motivo: ${motivo}`
        }
      ];

      return { ...item, status: 'Cancelado', historico: hist };
    }));
  }, []);

  const renegociarContaReceber = useCallback((id: string, novoVencimento: string, novoValor: number, obs: string) => {
    setContasReceber(prev => prev.map(item => {
      if (item.id !== id) return item;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: 'Renegociado',
          valorAnterior: item.valorFinal,
          valorNovo: novoValor,
          observacao: `Renegociado para vencimento ${novoVencimento.split('-').reverse().join('/')}. ${obs}`
        }
      ];

      return {
        ...item,
        valorOriginal: novoValor,
        valorFinal: novoValor,
        saldoDevedor: Math.max(0, novoValor - item.valorRecebido),
        dataVencimento: novoVencimento,
        status: 'Renegociado',
        historico: hist
      };
    }));
  }, []);

  // 4. AÇÕES CONTAS A PAGAR
  const registrarPagamentoDespesa = useCallback((
    id: string,
    valorPagoInput: number,
    forma: string,
    dataPagamento: string,
    desconto = 0,
    juros = 0,
    multa = 0,
    obs = ''
  ) => {
    setContasPagar(prev => prev.map(item => {
      if (item.id !== id) return item;

      const valorCalculado = (item.valorOriginal - desconto) + juros + multa;
      const novoTotalPago = item.valorPago + valorPagoInput;
      const novoSaldo = Math.max(0, valorCalculado - novoTotalPago);

      let novoStatus: ContaPagar['status'] = 'Pago';
      if (novoSaldo > 0) {
        novoStatus = 'Parcialmente pago';
      }

      const historicoNovo = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: novoSaldo === 0 ? 'Pago Total' : 'Pago Parcial',
          valorAnterior: item.saldoDevedor,
          valorNovo: novoSaldo,
          observacao: `Pagamento de despesa R$ ${valorPagoInput.toFixed(2)} via ${forma}. Obs: ${obs}`
        }
      ];

      return {
        ...item,
        desconto,
        juros,
        multa,
        valorFinal: valorCalculado,
        valorPago: novoTotalPago,
        saldoDevedor: novoSaldo,
        formaPagamento: forma,
        dataRealPagamento: dataPagamento,
        status: novoStatus,
        observacoes: obs ? `${item.observacoes || ''}\n[Pagamento]: ${obs}` : item.observacoes,
        historico: historicoNovo
      };
    }));
  }, []);

  const estornarPagamentoDespesa = useCallback((id: string, motivo: string) => {
    setContasPagar(prev => prev.map(item => {
      if (item.id !== id) return item;

      const todayStr = new Date().toISOString().split('T')[0];
      const isOverdue = item.dataVencimento < todayStr;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Administrador Financeiro',
          acao: 'Estorno',
          valorAnterior: item.valorPago,
          valorNovo: 0,
          observacao: `Estorno de pagamento de despesa. Motivo: ${motivo}`
        }
      ];

      return {
        ...item,
        valorPago: 0,
        saldoDevedor: item.valorFinal,
        status: isOverdue ? 'Vencido' : 'Em aberto',
        dataRealPagamento: undefined,
        historico: hist
      };
    }));
  }, []);

  const addContaPagar = useCallback((nova: Omit<ContaPagar, 'id' | 'numeroLancamento'>) => {
    setContasPagar(prev => {
      const launchNum = `PAG-${new Date().getFullYear()}-${String(prev.length + 1).padStart(3, '0')}`;
      const item: ContaPagar = {
        ...nova,
        id: `pag-manual-${Date.now()}`,
        numeroLancamento: launchNum,
        historico: [
          {
            id: `h-${Date.now()}`,
            dataHora: new Date().toLocaleString('pt-BR'),
            usuario: 'Operador Financeiro',
            acao: 'Criado',
            observacao: 'Conta a pagar criada manualmente'
          }
        ]
      };
      return [item, ...prev];
    });
  }, []);

  const editContaPagar = useCallback((id: string, dados: Partial<ContaPagar>) => {
    setContasPagar(prev => prev.map(item => {
      if (item.id !== id) return item;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: 'Editado',
          observacao: 'Despesa alterada'
        }
      ];

      return { ...item, ...dados, historico: hist };
    }));
  }, []);

  const cancelContaPagar = useCallback((id: string, motivo: string) => {
    setContasPagar(prev => prev.map(item => {
      if (item.id !== id) return item;

      const hist = [
        ...(item.historico || []),
        {
          id: `h-${Date.now()}`,
          dataHora: new Date().toLocaleString('pt-BR'),
          usuario: 'Operador Financeiro',
          acao: 'Cancelado',
          observacao: `Despesa cancelada. Motivo: ${motivo}`
        }
      ];

      return { ...item, status: 'Cancelado', historico: hist };
    }));
  }, []);

  // 5. REGISTRO DE CONTATO / ACORDO DE INADIMPLÊNCIA
  const addContatoInadimplencia = useCallback((reg: Omit<RegistroInadimplenciaContato, 'id' | 'dataHora' | 'usuario'>) => {
    const item: RegistroInadimplenciaContato = {
      ...reg,
      id: `inad-cont-${Date.now()}`,
      dataHora: new Date().toLocaleString('pt-BR'),
      usuario: 'Equipe de Cobrança'
    };
    setHistoricoInadimplencia(prev => [item, ...prev]);
  }, []);

  // 6. CATEGORIAS E FORMAS DE PAGAMENTO
  const addCategoria = useCallback((cat: Omit<CategoriaFinanceira, 'id'>) => {
    setCategorias(prev => [...prev, { ...cat, id: `cat-custom-${Date.now()}` }]);
  }, []);

  const addFormaPagamento = useCallback((forma: Omit<FormaPagamentoItem, 'id'>) => {
    setFormasPagamento(prev => [...prev, { ...forma, id: `fp-custom-${Date.now()}` }]);
  }, []);

  const toggleFormaPagamento = useCallback((id: string) => {
    setFormasPagamento(prev => prev.map(f => f.id === id ? { ...f, ativa: !f.ativa } : f));
  }, []);

  const resetFinanceiro = useCallback((newReceber: ContaReceber[] = [], newPagar: ContaPagar[] = []) => {
    setContasReceber(newReceber);
    setContasPagar(newPagar);
    localStorage.setItem('auto_erp_contas_receber_v2', JSON.stringify(newReceber));
    localStorage.setItem('auto_erp_contas_pagar_v2', JSON.stringify(newPagar));
  }, []);

  return {
    contasReceber,
    contasPagar,
    categorias,
    formasPagamento,
    historicoInadimplencia,

    // Actions
    setContasReceber,
    setContasPagar,
    resetFinanceiro,
    registrarRecebimento,
    estornarRecebimento,
    addContaReceber,
    editContaReceber,
    cancelContaReceber,
    renegociarContaReceber,

    registrarPagamentoDespesa,
    estornarPagamentoDespesa,
    addContaPagar,
    editContaPagar,
    cancelContaPagar,

    addContatoInadimplencia,
    addCategoria,
    addFormaPagamento,
    toggleFormaPagamento
  };
}
