import express from 'express';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {sql} from 'drizzle-orm';
import {db} from '../../db';
import {registerMaintenanceRoutes} from '../maintenanceRoutes';
import {MaintenanceAuthorityService} from '../maintenanceAuthority';
import {MaintenancePreventiveAuthority} from '../maintenancePreventiveAuthority';
import {materializeMaintenanceAlerts} from '../maintenancePreventiveAlerts';
import {addDaysIso,projectMaintenancePlan} from '../../domain/maintenance/maintenancePreventivePolicy';
import type {AuthenticatedPrincipal} from '../auth';
import type {MaintenancePlan} from '../../types/entities';

const require=createRequire(import.meta.url);const{Client}=require('pg') as typeof import('pg');
const companyA='security-2j2-company-a',companyB='security-2j2-company-b',adminA='security-2j2-admin-a',readonlyA='security-2j2-readonly-a',vehicleA='security-2j2-vehicle-a',vehicleB='security-2j2-vehicle-b',categoryA='security-2j2-maint-category-a',roleName='security_2j2_rls_user',rolePassword='security-j2-test-password';
const admin:AuthenticatedPrincipal={companyId:companyA,userId:adminA,name:'J2 Admin',role:'ADMIN',permissions:['*']};
const viewer:AuthenticatedPrincipal={companyId:companyA,userId:readonlyA,name:'J2 Viewer',role:'READONLY',permissions:[]};
function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(m);}const rows=(r:any):any[]=>Array.isArray(r?.rows)?r.rows:[];async function one(q:any){return rows(await db.execute(q))[0];}
async function seed(){await db.execute(sql`INSERT INTO companies(id,name,status,created_at,updated_at) VALUES(${companyA},'J2 A','ACTIVE',now(),now()),(${companyB},'J2 B','ACTIVE',now(),now()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO users(id,company_id,name,email,role,active,created_at,updated_at) VALUES(${adminA},${companyA},'J2 Admin','j2-admin@example.test','ADMIN',true,now(),now()),(${readonlyA},${companyA},'J2 Viewer','j2-viewer@example.test','READONLY',true,now(),now()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO vehicles(id,company_id,plate,renavam,status,current_km,created_at,updated_at) VALUES(${vehicleA},${companyA},'J2A2A02','J2REN-A','AVAILABLE',10000,now(),now()),(${vehicleB},${companyB},'J2B2B02','J2REN-B','AVAILABLE',20000,now(),now()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO financial_categories(id,company_id,name,type,active,created_at,updated_at) VALUES(${categoryA},${companyA},'Manutenção J2','EXPENSE',true,now(),now()) ON CONFLICT(id) DO NOTHING`);}
async function httpSecurity(){const app=express();app.use(express.json());app.use((req,_res,next)=>{const who=req.header('x-test-principal');if(who==='admin')(req as any).principal=admin;if(who==='readonly')(req as any).principal=viewer;next();});registerMaintenanceRoutes(app);const server=createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',()=>r()));const a=server.address();if(!a||typeof a==='string')throw new Error('address');const base=`http://127.0.0.1:${a.port}`;try{let r=await fetch(`${base}/api/maintenance/plans`);assert(r.status===401,`no-session ${r.status}`);r=await fetch(`${base}/api/maintenance/plans`,{method:'POST',headers:{'content-type':'application/json','x-test-principal':'readonly'},body:JSON.stringify({vehicleId:vehicleA,name:'X',maintenanceType:'X',intervalKm:1000})});assert(r.status===403,`readonly ${r.status}`);r=await fetch(`${base}/api/maintenance/plans`,{method:'POST',headers:{'content-type':'application/json','x-test-principal':'admin'},body:JSON.stringify({vehicleId:vehicleA,name:'X',maintenanceType:'X',intervalKm:1000,status:'ACTIVE'})});assert(r.status===400,`forged status ${r.status}`);}finally{await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));}}
function projectionFixture(nextDueKm?:number,nextDueDate?:string):MaintenancePlan{return{id:'p',companyId:companyA,vehicleId:vehicleA,name:'Plano',maintenanceType:'TEST',intervalKm:1000,lastExecutionKm:10000,lastExecutionDate:'2026-01-01',nextDueKm,nextDueDate,priority:'MEDIUM',status:'ACTIVE',cycleSequence:0,createdBy:adminA,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};}
function policyTests(){assert(addDaysIso('2026-12-31',1)==='2027-01-01','year rollover failed');for(const[days,stage]of[[90,'D90'],[60,'D60'],[30,'D30'],[15,'D15'],[7,'D7'],[0,'DUE_TODAY'],[-1,'POST_DUE']] as const){const due=addDaysIso('2026-08-20',Math.max(0,days));const value=days<0?'2026-08-19':due;assert(projectMaintenancePlan(projectionFixture(undefined,value),10000,'2026-08-20').projectedStage===stage,`date stage ${stage}`);}for(const[remaining,stage]of[[1000,'KM1000'],[500,'KM500'],[0,'DUE_KM'],[-1,'OVERDUE_KM']] as const)assert(projectMaintenancePlan(projectionFixture(10000+remaining),10000,'2026-08-20').projectedStage===stage,`km stage ${stage}`);}
async function core(){let rejected=false;try{await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Inválido',maintenanceType:'TEST'});}catch{rejected=true;}assert(rejected,'plan without interval accepted');rejected=false;try{await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleB,name:'Cross',maintenanceType:'TEST',intervalKm:1000});}catch{rejected=true;}assert(rejected,'cross-tenant vehicle accepted');
  const plan=await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Óleo preventivo',maintenanceType:'OIL',intervalKm:5000,intervalDays:30,priority:'HIGH'});assert(plan.lastExecutionKm===10000&&plan.nextDueKm===15000,'initial plan schedule wrong');
  const wo=await MaintenanceAuthorityService.createWorkOrder(admin,{number:'OS-J2-001',vehicleId:vehicleA,entryKm:10000,description:'Preventiva J2'});await MaintenanceAuthorityService.startWorkOrder(admin,wo.id);await MaintenancePreventiveAuthority.linkWorkOrder(admin,plan.id,wo.id);
  const beforeKm=Number((await one(sql`SELECT count(*)::int count FROM vehicle_km_records WHERE company_id=${companyA} AND vehicle_id=${vehicleA} AND reading_type='MAINTENANCE'`))?.count||0);
  const [a,b]=await Promise.all([MaintenanceAuthorityService.completeWorkOrder(admin,wo.id,{exitKm:10100,categoryId:categoryA,dueDate:'2026-09-20'}),MaintenanceAuthorityService.completeWorkOrder(admin,wo.id,{exitKm:10100,categoryId:categoryA,dueDate:'2026-09-20'})]);assert(a.status==='COMPLETED'&&b.status==='COMPLETED','completion did not converge');
  const advanced=await one(sql`SELECT last_execution_km,next_due_km,last_work_order_id,cycle_sequence FROM maintenance_plans WHERE id=${plan.id}`);assert(Number(advanced.last_execution_km)===10100&&Number(advanced.next_due_km)===15100&&advanced.last_work_order_id===wo.id&&Number(advanced.cycle_sequence)===1,'plan did not advance exactly once');
  await MaintenanceAuthorityService.completeWorkOrder(admin,wo.id,{exitKm:10100,categoryId:categoryA,dueDate:'2026-09-20'});assert(Number((await one(sql`SELECT cycle_sequence FROM maintenance_plans WHERE id=${plan.id}`)).cycle_sequence)===1,'retry advanced plan twice');
  const oil1=await MaintenancePreventiveAuthority.createOilChange(admin,{vehicleId:vehicleA,workOrderId:wo.id,km:10100,date:'2026-08-20',oilType:'5W30',oilBrand:'Teste',quantity:4,filterChanged:true,nextKm:20100});const oil2=await MaintenancePreventiveAuthority.createOilChange(admin,{vehicleId:vehicleA,workOrderId:wo.id,km:10100,date:'2026-08-20',oilType:'5W30',oilBrand:'Teste',quantity:4,filterChanged:true,nextKm:20100});assert(oil1.id===oil2.id,'linked oil retry duplicated');assert(Number((await one(sql`SELECT count(*)::int count FROM oil_change_records WHERE company_id=${companyA} AND work_order_id=${wo.id}`)).count)===1,'oil duplicate persisted');const afterOilKm=Number((await one(sql`SELECT count(*)::int count FROM vehicle_km_records WHERE company_id=${companyA} AND vehicle_id=${vehicleA} AND reading_type='MAINTENANCE'`))?.count||0);assert(afterOilKm===beforeKm+1,'linked oil duplicated maintenance KM record');
  rejected=false;try{await MaintenancePreventiveAuthority.createOilChange(admin,{vehicleId:vehicleA,km:10000,date:'2026-08-20',oilType:'5W30',oilBrand:'X',quantity:4,filterChanged:false,nextKm:20000});}catch{rejected=true;}assert(rejected,'regressive oil km accepted');
  const tire=await MaintenancePreventiveAuthority.createTire(admin,{vehicleId:vehicleA,position:'FL',brand:'Pirelli',model:'P1',installationDate:'2026-08-20',installationKm:10100,cost:500});const rotated=await MaintenancePreventiveAuthority.rotateTire(admin,tire.id,{position:'RL',km:10100,date:'2026-08-20',intervalKm:10000});assert(rotated.position==='RL'&&rotated.nextRotationKm===20100,'tire rotation failed');const removed=await MaintenancePreventiveAuthority.removeTire(admin,tire.id,{status:'REMOVED',km:10100,date:'2026-08-20',reason:'Fim de vida'});assert(removed.status==='REMOVED'&&removed.removalKm===10100,'tire removal failed');
  return plan;
}
async function multiPlanExecution(){
  const planA=await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Correia antecipada',maintenanceType:'TIMING_BELT',intervalKm:5000,priority:'HIGH'});
  const planB=await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Bomba antecipada',maintenanceType:'WATER_PUMP',intervalKm:7000,priority:'HIGH'});
  const planLegacy=await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Tensor não executado',maintenanceType:'TENSIONER',intervalKm:9000,priority:'MEDIUM'});
  const beforeA=await one(sql`SELECT cycle_sequence,next_due_km FROM maintenance_plans WHERE id=${planA.id}`);
  const beforeB=await one(sql`SELECT cycle_sequence,next_due_km FROM maintenance_plans WHERE id=${planB.id}`);
  const beforeLegacy=await one(sql`SELECT cycle_sequence,next_due_km FROM maintenance_plans WHERE id=${planLegacy.id}`);
  const wo=await MaintenanceAuthorityService.createWorkOrder(admin,{number:'OS-J2-MULTI-001',vehicleId:vehicleA,entryKm:10100,description:'Preventivas antecipadas múltiplas'});
  await MaintenanceAuthorityService.startWorkOrder(admin,wo.id);
  await MaintenancePreventiveAuthority.linkWorkOrder(admin,planLegacy.id,wo.id);
  const completed=await MaintenanceAuthorityService.completeWorkOrder(admin,wo.id,{exitKm:10200,preventivePlanIds:[planA.id,planB.id]});
  assert(completed.status==='COMPLETED','multi preventive OS did not complete');
  const afterA=await one(sql`SELECT cycle_sequence,last_execution_km,next_due_km,last_work_order_id FROM maintenance_plans WHERE id=${planA.id}`);
  const afterB=await one(sql`SELECT cycle_sequence,last_execution_km,next_due_km,last_work_order_id FROM maintenance_plans WHERE id=${planB.id}`);
  const afterLegacy=await one(sql`SELECT cycle_sequence,last_execution_km,next_due_km,last_work_order_id FROM maintenance_plans WHERE id=${planLegacy.id}`);
  assert(Number(afterA.cycle_sequence)===Number(beforeA.cycle_sequence)+1&&Number(afterA.last_execution_km)===10200&&Number(afterA.next_due_km)===15200&&afterA.last_work_order_id===wo.id,'first selected preventive item did not advance from real execution KM');
  assert(Number(afterB.cycle_sequence)===Number(beforeB.cycle_sequence)+1&&Number(afterB.last_execution_km)===10200&&Number(afterB.next_due_km)===17200&&afterB.last_work_order_id===wo.id,'second selected preventive item did not advance from real execution KM');
  assert(Number(afterLegacy.cycle_sequence)===Number(beforeLegacy.cycle_sequence)&&Number(afterLegacy.next_due_km)===Number(beforeLegacy.next_due_km)&&afterLegacy.last_work_order_id!==wo.id,'unselected legacy-linked preventive item advanced unexpectedly');
  const executions=rows(await db.execute(sql`SELECT maintenance_plan_id,execution_kind,execution_km FROM maintenance_work_order_plan_executions WHERE company_id=${companyA} AND work_order_id=${wo.id} ORDER BY maintenance_plan_id`));
  assert(executions.length===2,'multi preventive execution did not persist exactly two authoritative items');
  assert(executions.every((item:any)=>item.execution_kind==='PREVENTIVA_ANTECIPADA'&&Number(item.execution_km)===10200),'early preventive execution classification/KM is wrong');
  await MaintenanceAuthorityService.completeWorkOrder(admin,wo.id,{exitKm:10200,preventivePlanIds:[planA.id,planB.id]});
  assert(Number((await one(sql`SELECT count(*)::int count FROM maintenance_work_order_plan_executions WHERE company_id=${companyA} AND work_order_id=${wo.id}`)).count)===2,'retry duplicated preventive execution items');
  assert(Number((await one(sql`SELECT cycle_sequence FROM maintenance_plans WHERE id=${planA.id}`)).cycle_sequence)===Number(beforeA.cycle_sequence)+1,'retry advanced selected preventive plan twice');

  const emptyPlan=await MaintenancePreventiveAuthority.createPlan(admin,{vehicleId:vehicleA,name:'Filtro sem execução',maintenanceType:'FILTER_NONE',intervalKm:6000,priority:'LOW'});
  const emptyBefore=await one(sql`SELECT cycle_sequence,next_due_km FROM maintenance_plans WHERE id=${emptyPlan.id}`);
  const emptyWo=await MaintenanceAuthorityService.createWorkOrder(admin,{number:'OS-J2-MULTI-EMPTY',vehicleId:vehicleA,entryKm:10200,description:'Seleção preventiva vazia'});
  await MaintenanceAuthorityService.startWorkOrder(admin,emptyWo.id);
  await MaintenancePreventiveAuthority.linkWorkOrder(admin,emptyPlan.id,emptyWo.id);
  await MaintenanceAuthorityService.completeWorkOrder(admin,emptyWo.id,{exitKm:10300,preventivePlanIds:[]});
  const emptyAfter=await one(sql`SELECT cycle_sequence,next_due_km,last_work_order_id FROM maintenance_plans WHERE id=${emptyPlan.id}`);
  assert(Number(emptyAfter.cycle_sequence)===Number(emptyBefore.cycle_sequence)&&Number(emptyAfter.next_due_km)===Number(emptyBefore.next_due_km)&&emptyAfter.last_work_order_id!==emptyWo.id,'explicit empty preventive selection triggered legacy cycle reset');
  const marker=await one(sql`SELECT preventive_plan_selection_applied FROM work_orders WHERE company_id=${companyA} AND id=${emptyWo.id}`);
  assert(marker?.preventive_plan_selection_applied===true,'work order did not persist explicit preventive selection marker');
  assert(Number((await one(sql`SELECT count(*)::int count FROM maintenance_work_order_plan_executions WHERE company_id=${companyA} AND work_order_id=${emptyWo.id}`)).count)===0,'empty preventive selection created execution rows');
}

async function alerts(plan:MaintenancePlan){await db.execute(sql`UPDATE maintenance_plans SET status='ACTIVE',next_due_km=10600,next_due_date=NULL WHERE id=${plan.id}`);const first=await materializeMaintenanceAlerts(companyA,'2026-08-20');assert(first>0,'maintenance alert not materialized');const second=await materializeMaintenanceAlerts(companyA,'2026-08-20');assert(second===0,'maintenance alert not deduplicated');await db.execute(sql`UPDATE maintenance_plans SET status='PAUSED',next_due_km=10500 WHERE id=${plan.id}`);const paused=await materializeMaintenanceAlerts(companyA,'2026-08-20');assert(paused===0,'paused plan generated alert');await db.execute(sql`UPDATE maintenance_plans SET status='ACTIVE',next_due_km=NULL,next_due_date='2026-08-20' WHERE id=${plan.id}`);await materializeMaintenanceAlerts(companyA,'2026-08-20');const due=await one(sql`SELECT alert_stage FROM notifications WHERE company_id=${companyA} AND entity_type='MaintenancePlan' AND entity_id=${plan.id} AND alert_stage='DUE_TODAY' LIMIT 1`);assert(due?.alert_stage==='DUE_TODAY','date due alert missing');}
async function rls(){await db.execute(sql`INSERT INTO maintenance_plans(id,company_id,vehicle_id,name,maintenance_type,interval_km,last_execution_km,next_due_km,priority,status,cycle_sequence,created_by) VALUES('j2-plan-b',${companyB},${vehicleB},'B','TEST',1000,20000,21000,'MEDIUM','ACTIVE',0,'seed') ON CONFLICT(id) DO NOTHING`);await db.execute(sql.raw(`DROP ROLE IF EXISTS ${roleName}`));await db.execute(sql.raw(`CREATE ROLE ${roleName} LOGIN PASSWORD '${rolePassword}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS`));await db.execute(sql.raw(`GRANT USAGE ON SCHEMA public TO ${roleName}`));await db.execute(sql.raw(`GRANT SELECT,INSERT,UPDATE ON maintenance_plans,oil_change_records,tire_records TO ${roleName}`));const url=new URL(process.env.DATABASE_URL||'postgres://postgres:postgres@127.0.0.1:5432/autoerp_phase1_test'),client=new Client({host:url.hostname,port:Number(url.port||5432),database:url.pathname.slice(1),user:roleName,password:rolePassword});await client.connect();try{await client.query('BEGIN');await client.query(`SELECT set_config('app.current_tenant',$1,true)`,[companyA]);const visible=await client.query('SELECT company_id FROM maintenance_plans');assert(visible.rows.every((r:any)=>r.company_id===companyA),'RLS leaked plan');let denied=false;try{await client.query(`INSERT INTO maintenance_plans(id,company_id,vehicle_id,name,maintenance_type,interval_km,priority,status,cycle_sequence,created_by) VALUES('j2-cross',$1,$2,'X','X',1000,'MEDIUM','ACTIVE',0,'x')`,[companyB,vehicleB]);}catch{denied=true;}assert(denied,'RLS allowed cross tenant write');await client.query('ROLLBACK');}finally{await client.end();await db.execute(sql.raw(`DROP OWNED BY ${roleName}`));await db.execute(sql.raw(`DROP ROLE IF EXISTS ${roleName}`));}}
async function main(){await seed();await httpSecurity();policyTests();const plan=await core();await multiPlanExecution();await alerts(plan);await rls();console.log('SECURITY-2J2 preventive maintenance authority integration: PASS');}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
