import { sql } from 'drizzle-orm';
import { db } from '../../db';
import { TelemetryAuthorityService } from '../telemetryAuthority';
import type { AuthenticatedPrincipal } from '../auth';
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
function rows(result:any):any[]{return Array.isArray(result?.rows)?result.rows:[];}
const companyA='telemetry-1a-company-a',companyB='telemetry-1a-company-b',vehicleA='telemetry-1a-vehicle-a',vehicleB='telemetry-1a-vehicle-b',trackerA='telemetry-1a-tracker-a',trackerB='telemetry-1a-tracker-b';
const adminA:AuthenticatedPrincipal={companyId:companyA,userId:'telemetry-1a-admin',name:'Telemetry Admin',role:'ADMIN',permissions:['*']};
async function seed():Promise<void>{await db.execute(sql`INSERT INTO companies(id,name,status,created_at,updated_at) VALUES(${companyA},'Telemetry A','ACTIVE',NOW(),NOW()),(${companyB},'Telemetry B','ACTIVE',NOW(),NOW()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO users(id,company_id,name,email,role,active,created_at,updated_at) VALUES(${adminA.userId},${companyA},'Telemetry Admin','telemetry@example.test','ADMIN',true,NOW(),NOW()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO vehicles(id,company_id,plate,renavam,status,current_km,created_at,updated_at) VALUES(${vehicleA},${companyA},'TLA1A01','TLA-REN','AVAILABLE',1000,NOW(),NOW()),(${vehicleB},${companyB},'TLB1B01','TLB-REN','AVAILABLE',2000,NOW(),NOW()) ON CONFLICT(id) DO NOTHING`);await db.execute(sql`INSERT INTO trackers(id,company_id,vehicle_id,serial_number,equipment_model,imei,monthly_cost,installation_date,status,created_at,updated_at) VALUES(${trackerA},${companyA},${vehicleA},'TLA-SERIAL','Synthetic GPS A','111111111111111',0,'2026-08-25','ACTIVE',NOW(),NOW()),(${trackerB},${companyB},${vehicleB},'TLB-SERIAL','Synthetic GPS B','222222222222222',0,'2026-08-25','ACTIVE',NOW(),NOW()) ON CONFLICT(id) DO NOTHING`);}
async function main():Promise<void>{await seed();const occurredAt=new Date(Date.now()-60_000).toISOString();const before=rows(await db.execute(sql`SELECT count(*)::int count FROM account_payables WHERE company_id=${companyA}`))[0].count;const first=await TelemetryAuthorityService.ingest(adminA,{trackerId:trackerA,sourceEventId:'synthetic-odometer-1',eventType:'ODOMETER',occurredAt:occurredAt,payload:{odometerKm:1000,imei:'111111111111111'}});assert(first.created&&first.item.status==='ACCEPTED','first synthetic odometer not accepted');const replay=await TelemetryAuthorityService.ingest(adminA,{trackerId:trackerA,sourceEventId:'synthetic-odometer-1',eventType:'ODOMETER',occurredAt:occurredAt,payload:{odometerKm:1000}});assert(!replay.created&&replay.item.id===first.item.id,'replay was not idempotent');const regressive=await TelemetryAuthorityService.ingest(adminA,{trackerId:trackerA,sourceEventId:'synthetic-odometer-2',eventType:'ODOMETER',occurredAt:occurredAt,payload:{odometerKm:999}});assert(regressive.item.status==='QUARANTINED'&&regressive.item.quarantineReason==='ODOMETER_REGRESSION','regressive odometer not quarantined');let crossTenant=false;try{await TelemetryAuthorityService.ingest(adminA,{trackerId:trackerB,sourceEventId:'cross-tenant',eventType:'HEARTBEAT',occurredAt:occurredAt,payload:{}});}catch{crossTenant=true;}assert(crossTenant,'cross-tenant tracker was accepted');const listed=await TelemetryAuthorityService.list(companyA,trackerA);assert(listed.length===2&&listed.every(item=>!Object.prototype.hasOwnProperty.call(item,'rawPayload')),'list leaked raw telemetry payload');const after=rows(await db.execute(sql`SELECT count(*)::int count FROM account_payables WHERE company_id=${companyA}`))[0].count;assert(Number(before)===Number(after),'telemetry created a financial payable');console.log('TELEMETRY-1A synthetic authority integration: PASS');}
main().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});