// AutoERP Domain Enums

export enum VehicleStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENANCE = 'MAINTENANCE',
  INACTIVE = 'INACTIVE',
  SOLD = 'SOLD',
  ARCHIVED = 'ARCHIVED',
}

export const VEHICLE_CATEGORIES = [
  'Hatch / Sedan Compacto',
  'Sedan Médio',
  'SUV',
  'Pickup / Caminhonete',
  'Utilitário / VUC',
  'Executivo',
] as const;

export type VehicleCategory = (typeof VEHICLE_CATEGORIES)[number];

export enum DriverStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  PENDING_DOCS = 'PENDING_DOCS',
  BLOCKED = 'BLOCKED',
  ARCHIVED = 'ARCHIVED',
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  AWAITING_SIGNATURE = 'AWAITING_SIGNATURE',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  FINISHED = 'FINISHED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum FinancialAccountType {
  CASH = 'CASH',
  BANK = 'BANK',
  DIGITAL_ACCOUNT = 'DIGITAL_ACCOUNT',
  CREDIT_CARD = 'CREDIT_CARD',
  INVESTMENT = 'INVESTMENT',
  OTHER = 'OTHER',
}

export enum SecurityDepositStatus {
  PENDING = 'PENDING',
  RECEIVED = 'RECEIVED',
  PARTIALLY_USED = 'PARTIALLY_USED',
  USED = 'USED',
  RETURNED = 'RETURNED',
  PARTIALLY_RETURNED = 'PARTIALLY_RETURNED',
  REVERSED = 'REVERSED',
}

export enum SecurityDepositMovementType {
  RECEIPT = 'RECEIPT',
  COMPENSATION = 'COMPENSATION',
  RETURN = 'RETURN',
  REVERSAL = 'REVERSAL',
}

export enum ObligationStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  RENEGOTIATED = 'RENEGOTIATED',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  TRANSFER = 'TRANSFER',
  REVERSAL = 'REVERSAL',
}

export enum FinancialCategoryType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  BOTH = 'BOTH',
}

export enum OriginType {
  CONTRACT_RENT = 'CONTRACT_RENT',
  CONTRACT_RENTAL = 'CONTRACT_RENT',
  CONTRACT_FINE = 'CONTRACT_FINE',
  KM_EXCESS = 'KM_EXCESS',
  SECURITY_DEPOSIT = 'SECURITY_DEPOSIT',
  TRAFFIC_TICKET_DRIVER = 'TRAFFIC_TICKET_DRIVER',
  TRAFFIC_TICKET_COMPANY = 'TRAFFIC_TICKET_COMPANY',
  TRAFFIC_TICKET_NIC = 'TRAFFIC_TICKET_NIC',
  MAINTENANCE = 'MAINTENANCE',
  INSURANCE = 'INSURANCE',
  TRACKER = 'TRACKER',
  DOCUMENTATION = 'DOCUMENTATION',
  FINANCING = 'FINANCING',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  MANUAL = 'MANUAL',
  RENEGOTIATION = 'RENEGOTIATION',
}

export enum RecurringFrequency {
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUAL = 'SEMI_ANNUAL',
  ANNUAL = 'ANNUAL',
}

export enum MaintenanceType {
  PREVENTIVE = 'PREVENTIVE',
  CORRECTIVE = 'CORRECTIVE',
  REVISION = 'REVISION',
  OIL_CHANGE = 'OIL_CHANGE',
  TIRES = 'TIRES',
  BRAKES = 'BRAKES',
  SUSPENSION = 'SUSPENSION',
  ELECTRICAL = 'ELECTRICAL',
  BODYWORK = 'BODYWORK',
  OTHER = 'OTHER',
}

export enum MaintenanceStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
}

export enum TicketResponsibility {
  DRIVER = 'DRIVER',
  COMPANY = 'COMPANY',
  UNIDENTIFIED = 'UNIDENTIFIED',
}

export enum TicketStatus {
  PENDING_IDENTIFICATION = 'PENDING_IDENTIFICATION',
  IDENTIFIED = 'IDENTIFIED',
  CHARGED_DRIVER = 'CHARGED_DRIVER',
  COMPANY_PAYABLE_CREATED = 'COMPANY_PAYABLE_CREATED',
  PAID_BY_COMPANY = 'PAID_BY_COMPANY',
  APPEALED = 'APPEALED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  PAY = 'PAY',
  RECEIVE = 'RECEIVE',
  PARTIAL_PAYMENT = 'PARTIAL_PAYMENT',
  REVERSE = 'REVERSE',
  PARTIAL_REVERSE = 'PARTIAL_REVERSE',
  CANCEL = 'CANCEL',
  RENEGOTIATE = 'RENEGOTIATE',
  ARCHIVE = 'ARCHIVE',
  RESTORE = 'RESTORE',
  DELETE = 'DELETE',
  STATEMENT_ENTRY_IMPORTED = 'STATEMENT_ENTRY_IMPORTED',
  RECONCILIATION_MATCHED = 'RECONCILIATION_MATCHED',
  RECONCILIATION_UNMATCHED = 'RECONCILIATION_UNMATCHED',
  RECONCILIATION_IGNORED = 'RECONCILIATION_IGNORED',
  PERIOD_CLOSED = 'PERIOD_CLOSED',
  PERIOD_REOPENED = 'PERIOD_REOPENED',
}

export enum StatementEntryStatus {
  UNMATCHED = 'UNMATCHED',
  SUGGESTED = 'SUGGESTED',
  MATCHED = 'MATCHED',
  IGNORED = 'IGNORED',
  REVERSED = 'REVERSED',
}

export enum StatementDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum FinancialPeriodStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  FINANCIAL = 'FINANCIAL',
  OPERATIONAL = 'OPERATIONAL',
  READONLY = 'READONLY',
}

export enum AccountingRegime {
  CASH = 'CASH',
  ACCRUAL = 'ACCRUAL',
  PREDICTED = 'PREDICTED',
}
