import type { Tracker } from '../types/entities';

export class TrackerApiError extends Error { constructor(public readonly status:number,message:string){super(message);this.name='TrackerApiError';} }
type JsonRecord=Record<string,unknown>;
export interface TrackerExpenseCategory { id:string; name:string; type:string; }
export type TelemetryEventType='POSITION'|'ODOMETER'|'HEARTBEAT';
export type TelemetryEventStatus='ACCEPTED'|'QUARANTINED';
export type TelemetryReviewStatus='PENDING'|'ACKNOWLEDGED'|'DISMISSED';
export type TelemetryReviewDecision='ACKNOWLEDGED'|'DISMISSED';
export type TelemetryHealthStatus='NO_DATA'|'HEALTHY'|'STALE'|'OFFLINE'|'ATTENTION'|'INACTIVE';
export type TelemetryQuarantineReason='IMEI_MISMATCH'|'ODOMETER_REGRESSION'|'ODOMETER_ANOMALOUS_JUMP';
export type TelemetryKmDivergenceDirection='ALIGNED'|'TELEMETRY_ABOVE'|'TELEMETRY_BELOW'|'UNAVAILABLE';
export interface TelemetryEventSummary { id:string;trackerId:string;sourceEventId:string;eventType:TelemetryEventType;occurredAt:string;receivedAt:string;status:TelemetryEventStatus;quarantineReason:TelemetryQuarantineReason|null;reviewStatus:TelemetryReviewStatus|null;reviewReason:string|null;reviewedAt:string|null; }
export interface TelemetryHealthSummary { trackerId:string;healthStatus:TelemetryHealthStatus;lastCommunicationAt:string|null;lastAcceptedEventAt:string|null;latestAcceptedEventType:TelemetryEventType|null;lastAcceptedOdometerKm:number|null;quarantinedLast24h:number; }
export interface TelemetryObservabilitySummary { trackerId:string;retentionDays:number;generatedAt:string;retentionCutoffAt:string;totalEvents:number;acceptedEvents:number;quarantinedEvents:number;pendingReviewEvents:number;retentionEligibleEvents:number;oldestReceivedAt:string|null;newestReceivedAt:string|null; }
export interface TelemetryKmDivergenceSummary { trackerId:string;vehicleId:string;authoritativeVehicleKm:number;telemetryOdometerKm:number|null;differenceKm:number|null;direction:TelemetryKmDivergenceDirection;thresholdKm:number; }
export interface TrackerCreateRequest { vehicleId:string;equipmentModel:string;imei:string;serialNumber?:string;chipCarrier?:string;chipNumber?:string;monthlyCost:number;installationDate:string;supplierId?:string;providerName?:string;providerContact?:string;portalUrl?:string;notes?:string;categoryId?:string;sourceAttachmentId?:string; }
export type TrackerUpdateRequest=Partial<Omit<TrackerCreateRequest,'vehicleId'>>;
function asRecord(value:unknown):JsonRecord{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid tracker API response');return value as JsonRecord;}
function text(value:unknown,field:string):string{if(typeof value!=='string')throw new Error(`Invalid tracker field: ${field}`);return value;}
function safeText(value:unknown):string{return value===undefined||value===null?'':typeof value==='string'?value:String(value);}
function opt(value:unknown):string|undefined{if(value===undefined||value===null||value==='')return undefined;if(typeof value!=='string')throw new Error('Invalid optional tracker field');return value;}
export function safeTrackerPortalUrl(value:unknown):string|undefined {
  if(typeof value!=='string'||!/^https?:\/\//i.test(value.trim()))return undefined;
  try { const url=new URL(value.trim()); return ['http:','https:'].includes(url.protocol)&&url.hostname?value.trim():undefined; } catch { return undefined; }
}
function validateTracker(value:unknown):Tracker{
  const item=asRecord(value),status=text(item.status,'status');if(!['ACTIVE','INACTIVE','REMOVED'].includes(status))throw new Error('Invalid tracker status');const cost=Number(item.monthlyCost??0);if(!Number.isFinite(cost))throw new Error('Invalid tracker monthlyCost');
  return{id:text(item.id,'id'),companyId:text(item.companyId,'companyId'),vehicleId:text(item.vehicleId,'vehicleId'),serialNumber:opt(item.serialNumber),equipmentModel:safeText(item.equipmentModel),imei:safeText(item.imei),chipCarrier:safeText(item.chipCarrier),chipNumber:safeText(item.chipNumber),monthlyCost:cost,installationDate:safeText(item.installationDate),status:status as Tracker['status'],supplierId:opt(item.supplierId),providerName:opt(item.providerName),providerContact:opt(item.providerContact),portalUrl:safeTrackerPortalUrl(item.portalUrl),notes:opt(item.notes),lastPing:opt(item.lastPing),createdBy:opt(item.createdBy),createdAt:text(item.createdAt,'createdAt'),updatedAt:text(item.updatedAt,'updatedAt')};
}
function validateCategory(value:unknown):TrackerExpenseCategory{const item=asRecord(value),type=text(item.type,'type');if(!['EXPENSE','BOTH'].includes(type))throw new Error('Invalid tracker expense category');return{id:text(item.id,'id'),name:text(item.name,'name'),type};}
function iso(value:unknown,field:string):string{const result=text(value,field);if(!Number.isFinite(Date.parse(result)))throw new Error(`Invalid telemetry field: ${field}`);return result;}
function exactTelemetry(value:unknown):TelemetryEventSummary{const item=asRecord(value),allowed=new Set(['id','trackerId','sourceEventId','eventType','occurredAt','receivedAt','status','quarantineReason','reviewStatus','reviewReason','reviewedAt']);if(Object.keys(item).some(key=>!allowed.has(key)))throw new Error('Unsafe telemetry response');const eventType=text(item.eventType,'eventType'),status=text(item.status,'status');if(!['POSITION','ODOMETER','HEARTBEAT'].includes(eventType))throw new Error('Invalid telemetry event type');if(!['ACCEPTED','QUARANTINED'].includes(status))throw new Error('Invalid telemetry status');const reason=item.quarantineReason,reviewStatus=item.reviewStatus,reviewReason=item.reviewReason,reviewedAt=item.reviewedAt;if(reason!==null&&!['IMEI_MISMATCH','ODOMETER_REGRESSION','ODOMETER_ANOMALOUS_JUMP'].includes(String(reason)))throw new Error('Invalid telemetry quarantine reason');if(reviewStatus!==null&&!['PENDING','ACKNOWLEDGED','DISMISSED'].includes(String(reviewStatus)))throw new Error('Invalid telemetry review status');if((status==='ACCEPTED'&&(reason!==null||reviewStatus!==null||reviewReason!==null||reviewedAt!==null))||(status==='QUARANTINED'&&(reason===null||reviewStatus===null)))throw new Error('Inconsistent telemetry quarantine state');if(reviewStatus==='PENDING'&&(reviewReason!==null||reviewedAt!==null))throw new Error('Inconsistent pending telemetry review');if((reviewStatus==='ACKNOWLEDGED'||reviewStatus==='DISMISSED')&&(typeof reviewReason!=='string'||reviewReason.trim().length<3||reviewReason.length>500||reviewedAt===null))throw new Error('Inconsistent completed telemetry review');return{id:text(item.id,'id'),trackerId:text(item.trackerId,'trackerId'),sourceEventId:text(item.sourceEventId,'sourceEventId'),eventType:eventType as TelemetryEventType,occurredAt:iso(item.occurredAt,'occurredAt'),receivedAt:iso(item.receivedAt,'receivedAt'),status:status as TelemetryEventStatus,quarantineReason:reason as TelemetryQuarantineReason|null,reviewStatus:reviewStatus as TelemetryReviewStatus|null,reviewReason:reviewReason as string|null,reviewedAt:reviewedAt===null?null:iso(reviewedAt,'reviewedAt')};}
export function parseTelemetryEventSummary(value:unknown):TelemetryEventSummary{return exactTelemetry(value);}
function nullableIso(value:unknown,field:string):string|null{return value===null?null:iso(value,field);}
export function parseTelemetryHealthSummary(value:unknown):TelemetryHealthSummary{const item=asRecord(value),allowed=new Set(['trackerId','healthStatus','lastCommunicationAt','lastAcceptedEventAt','latestAcceptedEventType','lastAcceptedOdometerKm','quarantinedLast24h']);if(Object.keys(item).some(key=>!allowed.has(key)))throw new Error('Unsafe telemetry health response');const healthStatus=text(item.healthStatus,'healthStatus');if(!['NO_DATA','HEALTHY','STALE','OFFLINE','ATTENTION','INACTIVE'].includes(healthStatus))throw new Error('Invalid telemetry health status');const lastCommunicationAt=nullableIso(item.lastCommunicationAt,'lastCommunicationAt'),lastAcceptedEventAt=nullableIso(item.lastAcceptedEventAt,'lastAcceptedEventAt');const latest=item.latestAcceptedEventType;if(latest!==null&&!['POSITION','ODOMETER','HEARTBEAT'].includes(String(latest)))throw new Error('Invalid latest telemetry event type');const odometer=item.lastAcceptedOdometerKm;if(odometer!==null&&(typeof odometer!=='number'||!Number.isFinite(odometer)||odometer<0))throw new Error('Invalid derived telemetry odometer');const quarantined=Number(item.quarantinedLast24h);if(!Number.isInteger(quarantined)||quarantined<0)throw new Error('Invalid telemetry quarantine count');if(healthStatus==='NO_DATA'&&lastCommunicationAt!==null)throw new Error('Inconsistent telemetry health state');if(lastAcceptedEventAt===null&&(latest!==null||odometer!==null))throw new Error('Inconsistent accepted telemetry summary');return{trackerId:text(item.trackerId,'trackerId'),healthStatus:healthStatus as TelemetryHealthStatus,lastCommunicationAt,lastAcceptedEventAt,latestAcceptedEventType:latest as TelemetryEventType|null,lastAcceptedOdometerKm:odometer as number|null,quarantinedLast24h:quarantined};}
export function parseTelemetryObservabilitySummary(value:unknown):TelemetryObservabilitySummary{const item=asRecord(value),allowed=new Set(['trackerId','retentionDays','generatedAt','retentionCutoffAt','totalEvents','acceptedEvents','quarantinedEvents','pendingReviewEvents','retentionEligibleEvents','oldestReceivedAt','newestReceivedAt']);if(Object.keys(item).some(key=>!allowed.has(key)))throw new Error('Unsafe telemetry observability response');const retentionDays=Number(item.retentionDays),totalEvents=Number(item.totalEvents),acceptedEvents=Number(item.acceptedEvents),quarantinedEvents=Number(item.quarantinedEvents),pendingReviewEvents=Number(item.pendingReviewEvents),retentionEligibleEvents=Number(item.retentionEligibleEvents);if(!Number.isInteger(retentionDays)||retentionDays<30||retentionDays>3650)throw new Error('Invalid telemetry retention window');for(const count of [totalEvents,acceptedEvents,quarantinedEvents,pendingReviewEvents,retentionEligibleEvents])if(!Number.isInteger(count)||count<0)throw new Error('Invalid telemetry observability count');if(acceptedEvents+quarantinedEvents!==totalEvents||pendingReviewEvents>quarantinedEvents||retentionEligibleEvents>totalEvents)throw new Error('Inconsistent telemetry observability summary');const generatedAt=iso(item.generatedAt,'generatedAt'),retentionCutoffAt=iso(item.retentionCutoffAt,'retentionCutoffAt'),oldestReceivedAt=nullableIso(item.oldestReceivedAt,'oldestReceivedAt'),newestReceivedAt=nullableIso(item.newestReceivedAt,'newestReceivedAt');if((totalEvents===0&&(oldestReceivedAt!==null||newestReceivedAt!==null))||(totalEvents>0&&(oldestReceivedAt===null||newestReceivedAt===null)))throw new Error('Inconsistent telemetry observability range');return{trackerId:text(item.trackerId,'trackerId'),retentionDays,generatedAt,retentionCutoffAt,totalEvents,acceptedEvents,quarantinedEvents,pendingReviewEvents,retentionEligibleEvents,oldestReceivedAt,newestReceivedAt};}
function kmNumber(value:unknown,field:string):number{if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>9_999_999)throw new Error(`Invalid telemetry KM field: ${field}`);return value;}
export function parseTelemetryKmDivergenceSummary(value:unknown):TelemetryKmDivergenceSummary{const item=asRecord(value),allowed=new Set(['trackerId','vehicleId','authoritativeVehicleKm','telemetryOdometerKm','differenceKm','direction','thresholdKm']);if(Object.keys(item).some(key=>!allowed.has(key)))throw new Error('Unsafe telemetry KM divergence response');const direction=text(item.direction,'direction');if(!['ALIGNED','TELEMETRY_ABOVE','TELEMETRY_BELOW','UNAVAILABLE'].includes(direction))throw new Error('Invalid telemetry KM divergence direction');const authoritativeVehicleKm=kmNumber(item.authoritativeVehicleKm,'authoritativeVehicleKm'),thresholdKm=kmNumber(item.thresholdKm,'thresholdKm');const telemetryOdometerKm=item.telemetryOdometerKm===null?null:kmNumber(item.telemetryOdometerKm,'telemetryOdometerKm');const differenceKm=item.differenceKm===null?null:kmNumber(item.differenceKm,'differenceKm');if(direction==='UNAVAILABLE'&&(telemetryOdometerKm!==null||differenceKm!==null))throw new Error('Inconsistent unavailable telemetry KM divergence');if(direction!=='UNAVAILABLE'&&(telemetryOdometerKm===null||differenceKm===null))throw new Error('Inconsistent available telemetry KM divergence');return{trackerId:text(item.trackerId,'trackerId'),vehicleId:text(item.vehicleId,'vehicleId'),authoritativeVehicleKm,telemetryOdometerKm,differenceKm,direction:direction as TelemetryKmDivergenceDirection,thresholdKm};}
async function request(path:string,init?:RequestInit):Promise<JsonRecord>{const response=await fetch(path,{...init,credentials:'include'});if(!response.ok){let message=`Tracker request failed (${response.status})`;try{const payload=asRecord(await response.json());if(typeof payload.error==='string'&&payload.error)message=payload.error;}catch{}throw new TrackerApiError(response.status,message);}return asRecord(await response.json());}
function json(method:string,body:unknown):RequestInit{return{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)};}
function list<T>(payload:JsonRecord,validator:(value:unknown)=>T):T[]{if(!Array.isArray(payload.items))throw new Error('Invalid tracker list');return payload.items.map(validator);}
export class TrackerClient {
  static async list(filters?:{vehicleId?:string}):Promise<Tracker[]>{const query=filters?.vehicleId?`?vehicleId=${encodeURIComponent(filters.vehicleId)}`:'';return list(await request(`/api/trackers${query}`),validateTracker);}
  static async listByVehicle(vehicleId:string):Promise<Tracker[]>{return list(await request(`/api/vehicles/${encodeURIComponent(vehicleId)}/trackers`),validateTracker);}
  static async get(id:string):Promise<Tracker>{return validateTracker((await request(`/api/trackers/${encodeURIComponent(id)}`)).item);}
  static async listExpenseCategories():Promise<TrackerExpenseCategory[]>{return list(await request('/api/trackers/expense-categories'),validateCategory);}
  static async listTelemetry(trackerId:string,limit=50):Promise<TelemetryEventSummary[]>{const safeLimit=Number.isInteger(limit)&&limit>0&&limit<=100?limit:50;return list(await request(`/api/trackers/${encodeURIComponent(trackerId)}/telemetry?limit=${safeLimit}`,{headers:{Accept:'application/json'}}),exactTelemetry);}
  static async getTelemetryHealth(trackerId:string):Promise<TelemetryHealthSummary>{return parseTelemetryHealthSummary((await request(`/api/trackers/${encodeURIComponent(trackerId)}/telemetry/health`,{headers:{Accept:'application/json'}})).item);}
  static async getTelemetryObservability(trackerId:string):Promise<TelemetryObservabilitySummary>{return parseTelemetryObservabilitySummary((await request(`/api/trackers/${encodeURIComponent(trackerId)}/telemetry/observability`,{headers:{Accept:'application/json'}})).item);}
  static async getTelemetryKmDivergence(trackerId:string):Promise<TelemetryKmDivergenceSummary>{return parseTelemetryKmDivergenceSummary((await request(`/api/trackers/${encodeURIComponent(trackerId)}/telemetry/km-divergence`,{headers:{Accept:'application/json'}})).item);}
  static async reviewTelemetry(trackerId:string,eventId:string,decision:TelemetryReviewDecision,reason:string):Promise<{item:TelemetryEventSummary;changed:boolean}>{const response=await request(`/api/trackers/${encodeURIComponent(trackerId)}/telemetry/${encodeURIComponent(eventId)}/review`,json('POST',{decision,reason}));const allowed=new Set(['item','changed']);if(Object.keys(response).some(key=>!allowed.has(key))||typeof response.changed!=='boolean')throw new Error('Unsafe telemetry review response');return{item:exactTelemetry(response.item),changed:response.changed};}
  static async create(input:TrackerCreateRequest):Promise<Tracker>{return validateTracker((await request('/api/trackers',json('POST',input))).item);}
  static async update(id:string,input:TrackerUpdateRequest):Promise<Tracker>{return validateTracker((await request(`/api/trackers/${encodeURIComponent(id)}`,json('PATCH',input))).item);}
  static async remove(id:string,reason:string):Promise<Tracker>{return validateTracker((await request(`/api/trackers/${encodeURIComponent(id)}/remove`,json('POST',{reason}))).item);}
}
