import type { AccountPayable,AccountReceivable,TrafficTicket } from '../types/entities';
import { ObligationStatus,TicketResponsibility,TicketStatus } from '../types/enums';

export interface TrafficTicketFinancialCategory{id:string;name:string;type:string;}
export interface TrafficTicketDetails{item:TrafficTicket;financial:{basePayable?:AccountPayable;receivable?:AccountReceivable;nicPayable?:AccountPayable;discountAvailable:boolean};}
type JsonRecord=Record<string,unknown>;
function record(value:unknown):JsonRecord{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid traffic ticket payload');return value as JsonRecord;}
function boolean(value:unknown,field:string):boolean{if(typeof value!=='boolean')throw new Error(`Invalid traffic ticket boolean field: ${field}`);return value;}
const STATUSES=new Set(Object.values(TicketStatus)),RESPONSIBILITIES=new Set(Object.values(TicketResponsibility)),OBLIGATIONS=new Set(Object.values(ObligationStatus));
function ticket(value:unknown):TrafficTicket{const item=record(value);if(typeof item.id!=='string'||typeof item.companyId!=='string'||typeof item.vehicleId!=='string'||typeof item.autoNumber!=='string'||typeof item.organName!=='string'||typeof item.infractionCode!=='string'||typeof item.description!=='string'||typeof item.infractionDate!=='string'||typeof item.dueDate!=='string'||typeof item.originalAmount!=='number'||!Number.isFinite(item.originalAmount)||typeof item.points!=='number'||typeof item.responsibility!=='string'||!RESPONSIBILITIES.has(item.responsibility as TicketResponsibility)||typeof item.status!=='string'||!STATUSES.has(item.status as TicketStatus)||typeof item.createdAt!=='string'||typeof item.updatedAt!=='string')throw new Error('Invalid traffic ticket payload');return item as unknown as TrafficTicket;}
function obligation(value:unknown):AccountPayable|AccountReceivable{const item=record(value);if(typeof item.id!=='string'||typeof item.companyId!=='string'||typeof item.originId!=='string'||typeof item.originalAmount!=='number'||typeof item.paidAmount!=='number'||typeof item.balanceAmount!=='number'||typeof item.dueDate!=='string'||typeof item.status!=='string'||!OBLIGATIONS.has(item.status as ObligationStatus))throw new Error('Invalid traffic ticket obligation payload');return item as unknown as AccountPayable|AccountReceivable;}
function details(value:unknown):TrafficTicketDetails{const payload=record(value),financial=record(payload.financial);return {item:ticket(payload.item),financial:{basePayable:financial.basePayable?obligation(financial.basePayable) as AccountPayable:undefined,receivable:financial.receivable?obligation(financial.receivable) as AccountReceivable:undefined,nicPayable:financial.nicPayable?obligation(financial.nicPayable) as AccountPayable:undefined,discountAvailable:boolean(financial.discountAvailable,'discountAvailable')}};}
async function error(response:Response):Promise<Error>{let message=`Traffic ticket request failed (${response.status})`;try{const payload=record(await response.json());if(typeof payload.error==='string')message=payload.error;}catch{}return new Error(message);}
async function request(url:string,init?:RequestInit):Promise<TrafficTicketDetails>{const response=await fetch(url,{credentials:'include',...init});if(!response.ok)throw await error(response);return details(await response.json());}
export interface CreateTrafficTicketInput{
  vehicleId:string;driverId?:string;contractId?:string;autoNumber:string;organName:string;infractionCode:string;description:string;
  infractionDate:string;dueDate:string;discountDueDate?:string;originalAmount:number;discountedAmount?:number;nicAmount?:number;points:number;
  responsibility:TicketResponsibility;notes?:string;baseExpenseCategoryId:string;driverIncomeCategoryId?:string;nicExpenseCategoryId?:string;nicAmount?:number;
}
export class TrafficTicketClient{
  static async list(filters:{vehicleId?:string;driverId?:string;status?:TicketStatus;responsibility?:TicketResponsibility}={}):Promise<TrafficTicket[]>{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,String(value));});const suffix=params.toString();const response=await fetch(`/api/traffic-tickets${suffix?`?${suffix}`:''}`,{credentials:'include'});if(!response.ok)throw await error(response);const payload=record(await response.json());if(!Array.isArray(payload.items))throw new Error('Invalid traffic ticket list');return payload.items.map(ticket);}
  static async get(id:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}`);}
  static async categories():Promise<TrafficTicketFinancialCategory[]>{const response=await fetch('/api/traffic-tickets/financial-categories',{credentials:'include'});if(!response.ok)throw await error(response);const payload=record(await response.json());if(!Array.isArray(payload.items))throw new Error('Invalid category list');return payload.items.map(value=>{const item=record(value);if(typeof item.id!=='string'||typeof item.name!=='string'||typeof item.type!=='string')throw new Error('Invalid category');return {id:item.id,name:item.name,type:item.type};});}
  static async create(input:CreateTrafficTicketInput):Promise<TrafficTicketDetails>{return request('/api/traffic-tickets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async update(id:string,input:{organName?:string;infractionCode?:string;description?:string;notes?:string}):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async changeResponsibility(id:string,input:{responsibility:TicketResponsibility;driverId?:string;contractId?:string;driverIncomeCategoryId?:string;nicExpenseCategoryId?:string;nicAmount?:number}):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/responsibility`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async appeal(id:string,notes:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/appeal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({notes})});}
  static async cancel(id:string,reason:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/cancel`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})});}
}
