import type { AccountPayable,AccountReceivable,TrafficTicket } from '../types/entities';
import { ObligationStatus,TicketResponsibility,TicketStatus,TrafficTicketDriverIndicationStatus } from '../types/enums';

export interface TrafficTicketFinancialCategory{id:string;name:string;type:string;}
export interface TrafficTicketDetails{item:TrafficTicket;financial:{basePayable?:AccountPayable;receivable?:AccountReceivable;nicPayable?:AccountPayable;discountAvailable:boolean};}
export interface TrafficTicketDriverIndication{id:string;companyId:string;trafficTicketId:string;driverId?:string;status:TrafficTicketDriverIndicationStatus;indicationDeadline?:string;notes?:string;statusChangedAt:string;createdBy?:string;updatedBy?:string;createdAt:string;updatedAt:string;}
export interface TrafficTicketDriverCommunication{outboxId:string;created:boolean;status:'HELD_PROVIDER_DISABLED';providerCallApplied:false;}
export type TrafficTicketVehicleOperationalCause='DOCUMENTATION'|'TECHNICAL_CONDITION'|'OTHER_OPERATIONAL';
export interface TrafficTicketVehicleOperationalAction{taskId:string;created:boolean;cause:TrafficTicketVehicleOperationalCause;category:'DOCUMENT'|'MAINTENANCE'|'OPERATIONAL_GENERAL';}
type JsonRecord=Record<string,unknown>;
function record(value:unknown):JsonRecord{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid traffic ticket payload');return value as JsonRecord;}
function boolean(value:unknown,field:string):boolean{if(typeof value!=='boolean')throw new Error(`Invalid traffic ticket boolean field: ${field}`);return value;}
const STATUSES=new Set(Object.values(TicketStatus)),RESPONSIBILITIES=new Set(Object.values(TicketResponsibility)),OBLIGATIONS=new Set(Object.values(ObligationStatus)),INDICATION_STATUSES=new Set(Object.values(TrafficTicketDriverIndicationStatus));
function ticket(value:unknown):TrafficTicket{const item=record(value);if(typeof item.id!=='string'||typeof item.companyId!=='string'||typeof item.vehicleId!=='string'||(item.vehiclePlate!==undefined&&item.vehiclePlate!==null&&typeof item.vehiclePlate!=='string')||typeof item.autoNumber!=='string'||typeof item.organName!=='string'||typeof item.infractionCode!=='string'||typeof item.description!=='string'||typeof item.infractionDate!=='string'||(item.infractionTime!==undefined&&item.infractionTime!==null&&typeof item.infractionTime!=='string')||(item.infractionLocation!==undefined&&item.infractionLocation!==null&&typeof item.infractionLocation!=='string')||typeof item.dueDate!=='string'||typeof item.originalAmount!=='number'||!Number.isFinite(item.originalAmount)||typeof item.points!=='number'||typeof item.responsibility!=='string'||!RESPONSIBILITIES.has(item.responsibility as TicketResponsibility)||typeof item.status!=='string'||!STATUSES.has(item.status as TicketStatus)||typeof item.createdAt!=='string'||typeof item.updatedAt!=='string')throw new Error('Invalid traffic ticket payload');return item as unknown as TrafficTicket;}
function obligation(value:unknown):AccountPayable|AccountReceivable{const item=record(value);if(typeof item.id!=='string'||typeof item.companyId!=='string'||typeof item.originId!=='string'||typeof item.originalAmount!=='number'||typeof item.paidAmount!=='number'||typeof item.balanceAmount!=='number'||typeof item.dueDate!=='string'||typeof item.status!=='string'||!OBLIGATIONS.has(item.status as ObligationStatus))throw new Error('Invalid traffic ticket obligation payload');return item as unknown as AccountPayable|AccountReceivable;}
function details(value:unknown):TrafficTicketDetails{const payload=record(value),financial=record(payload.financial);return {item:ticket(payload.item),financial:{basePayable:financial.basePayable?obligation(financial.basePayable) as AccountPayable:undefined,receivable:financial.receivable?obligation(financial.receivable) as AccountReceivable:undefined,nicPayable:financial.nicPayable?obligation(financial.nicPayable) as AccountPayable:undefined,discountAvailable:boolean(financial.discountAvailable,'discountAvailable')}};}
function indication(value:unknown):TrafficTicketDriverIndication{const item=record(value);if(typeof item.id!=='string'||typeof item.companyId!=='string'||typeof item.trafficTicketId!=='string'||typeof item.status!=='string'||!INDICATION_STATUSES.has(item.status as TrafficTicketDriverIndicationStatus)||typeof item.statusChangedAt!=='string'||typeof item.createdAt!=='string'||typeof item.updatedAt!=='string')throw new Error('Invalid traffic ticket driver indication payload');return item as unknown as TrafficTicketDriverIndication;}
function communication(value:unknown):TrafficTicketDriverCommunication{const item=record(value);if(typeof item.outboxId!=='string'||!/^wao_[a-f0-9]{32}$/.test(item.outboxId)||typeof item.created!=='boolean'||item.status!=='HELD_PROVIDER_DISABLED'||item.providerCallApplied!==false)throw new Error('Invalid traffic ticket communication payload');return {outboxId:item.outboxId,created:item.created,status:'HELD_PROVIDER_DISABLED',providerCallApplied:false};}
function vehicleOperationalAction(value:unknown):TrafficTicketVehicleOperationalAction{const item=record(value),causes=new Set(['DOCUMENTATION','TECHNICAL_CONDITION','OTHER_OPERATIONAL']),categories=new Set(['DOCUMENT','MAINTENANCE','OPERATIONAL_GENERAL']);if(typeof item.taskId!=='string'||typeof item.created!=='boolean'||typeof item.cause!=='string'||!causes.has(item.cause)||typeof item.category!=='string'||!categories.has(item.category))throw new Error('Invalid traffic ticket vehicle operational payload');return item as unknown as TrafficTicketVehicleOperationalAction;}
async function error(response:Response):Promise<Error>{let message=`Traffic ticket request failed (${response.status})`;try{const payload=record(await response.json());if(typeof payload.error==='string')message=payload.error;}catch{}return new Error(message);}
async function request(url:string,init?:RequestInit):Promise<TrafficTicketDetails>{const response=await fetch(url,{credentials:'include',...init});if(!response.ok)throw await error(response);return details(await response.json());}
async function indicationRequest(url:string,init?:RequestInit):Promise<TrafficTicketDriverIndication>{const response=await fetch(url,{credentials:'include',...init});if(!response.ok)throw await error(response);return indication(await response.json());}
export interface CreateTrafficTicketInput{
  vehicleId?:string;vehiclePlate?:string;driverId?:string;contractId?:string;autoNumber:string;organName:string;infractionCode:string;description:string;
  infractionDate:string;infractionTime?:string;infractionLocation?:string;dueDate:string;discountDueDate?:string;originalAmount:number;discountedAmount?:number;nicAmount?:number;points:number;
  responsibility:TicketResponsibility;notes?:string;baseExpenseCategoryId:string;driverIncomeCategoryId?:string;nicExpenseCategoryId?:string;
}
export class TrafficTicketClient{
  static async list(filters:{vehicleId?:string;driverId?:string;status?:TicketStatus;responsibility?:TicketResponsibility}={}):Promise<TrafficTicket[]>{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,String(value));});const suffix=params.toString();const response=await fetch(`/api/traffic-tickets${suffix?`?${suffix}`:''}`,{credentials:'include'});if(!response.ok)throw await error(response);const payload=record(await response.json());if(!Array.isArray(payload.items))throw new Error('Invalid traffic ticket list');return payload.items.map(ticket);}
  static async get(id:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}`);}
  static async categories():Promise<TrafficTicketFinancialCategory[]>{const response=await fetch('/api/traffic-tickets/financial-categories',{credentials:'include'});if(!response.ok)throw await error(response);const payload=record(await response.json());if(!Array.isArray(payload.items))throw new Error('Invalid category list');return payload.items.map(value=>{const item=record(value);if(typeof item.id!=='string'||typeof item.name!=='string'||typeof item.type!=='string')throw new Error('Invalid category');return {id:item.id,name:item.name,type:item.type};});}
  static async create(input:CreateTrafficTicketInput):Promise<TrafficTicketDetails>{return request('/api/traffic-tickets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async update(id:string,input:{organName?:string;infractionCode?:string;description?:string;infractionTime?:string;infractionLocation?:string;notes?:string}):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async changeResponsibility(id:string,input:{responsibility:TicketResponsibility;driverId?:string;contractId?:string;driverIncomeCategoryId?:string;nicExpenseCategoryId?:string;nicAmount?:number}):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/responsibility`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async appeal(id:string,notes:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/appeal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({notes})});}
  static async cancel(id:string,reason:string):Promise<TrafficTicketDetails>{return request(`/api/traffic-tickets/${encodeURIComponent(id)}/cancel`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})});}
  static async getDriverIndication(id:string):Promise<TrafficTicketDriverIndication>{return indicationRequest(`/api/traffic-tickets/${encodeURIComponent(id)}/driver-indication`);}
  static async updateDriverIndication(id:string,input:{status:TrafficTicketDriverIndicationStatus;indicationDeadline?:string;notes?:string}):Promise<TrafficTicketDriverIndication>{return indicationRequest(`/api/traffic-tickets/${encodeURIComponent(id)}/driver-indication`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});}
  static async prepareDriverCommunication(id:string):Promise<TrafficTicketDriverCommunication>{const response=await fetch(`/api/traffic-tickets/${encodeURIComponent(id)}/driver-communication`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:'{}'});if(!response.ok)throw await error(response);return communication(await response.json());}
  static async createVehicleOperationalAction(id:string,cause:TrafficTicketVehicleOperationalCause):Promise<TrafficTicketVehicleOperationalAction>{const response=await fetch(`/api/traffic-tickets/${encodeURIComponent(id)}/vehicle-operational-action`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({cause})});if(!response.ok)throw await error(response);return vehicleOperationalAction(await response.json());}
}
