import React, { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, Car, CheckCircle2, Clock, Loader2, RefreshCw, ShieldAlert, Users, Zap } from 'lucide-react';
import { OperationalAuthorityClient } from '../../api/operationalAuthorityClient';
import type { ExecutiveOperationsSnapshot, PriorityActionItem } from '../../domain/operations/types';
import { useAuth } from '../../hooks/useAuth';

function riskClass(score:number):string{return score>=80?'text-red-700 bg-red-50 border-red-200':score>=60?'text-orange-700 bg-orange-50 border-orange-200':score>=40?'text-amber-700 bg-amber-50 border-amber-200':'text-emerald-700 bg-emerald-50 border-emerald-200';}
function kpi(label:string,value:number,icon:React.ReactNode,detail?:string){return <div className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</span>{icon}</div><div className="mt-2 text-2xl font-bold text-slate-900">{value}</div>{detail&&<div className="mt-1 text-xs text-slate-500">{detail}</div>}</div>;}

export const ExecutiveOperationsCenterView:React.FC=()=>{
  const {user}=useAuth();
  const [snapshot,setSnapshot]=useState<ExecutiveOperationsSnapshot|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null);
  const [busy,setBusy]=useState<string|null>(null);
  const [message,setMessage]=useState<string|null>(null);

  const load=useCallback(async()=>{setLoading(true);setError(null);try{setSnapshot(await OperationalAuthorityClient.executiveSnapshot());}catch(err){setSnapshot(null);setError(err instanceof Error?err.message:'Falha ao carregar Central Executiva');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);

  async function runAction(action:PriorityActionItem){if(!action.quickActionType)return;setBusy(action.id);setError(null);setMessage(null);try{const result=await OperationalAuthorityClient.executeQuickAction(action.quickActionType,action.entityId,`Ação executada por ${user.name}`);setMessage(result.message);await load();}catch(err){setError(err instanceof Error?err.message:'Falha na ação executiva');}finally{setBusy(null);}}

  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Activity className="h-7 w-7 text-violet-600"/><h1 className="text-2xl font-bold text-slate-900">Central Executiva de Operações</h1></div><p className="mt-1 text-sm text-slate-500">Resumo das operações • responsável: {user.name} ({user.role})</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-medium disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Atualizar resumo</button></div>
    {error&&<div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-4 w-4"/>{error}</div>}
    {message&&<div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
    {loading&&!snapshot?<div className="flex items-center justify-center gap-2 rounded-xl border bg-white p-16 text-slate-500"><Loader2 className="h-5 w-5 animate-spin"/>Gerando snapshot operacional autoritativo...</div>:snapshot&&<>
      <div className={`rounded-xl border p-5 ${riskClass(snapshot.operationalRiskScore.score)}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-sm font-semibold">Saúde operacional</div><div className="mt-1 text-4xl font-bold">{snapshot.healthScore}/100</div></div><div className="text-right"><div className="text-sm font-semibold">Risco: {snapshot.operationalRiskScore.level}</div><div className="mt-1 text-3xl font-bold">{snapshot.operationalRiskScore.score}</div><div className="mt-1 text-xs opacity-70">Snapshot {new Date(snapshot.generatedAt).toLocaleString('pt-BR')}</div></div></div></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpi('Tarefas ativas',snapshot.activeTasks,<Clock className="h-5 w-5 text-blue-500"/>,`${snapshot.blockedTasks} bloqueadas • ${snapshot.overdueTasks} vencidas`)}{kpi('Incidentes ativos',snapshot.openIncidents,<ShieldAlert className="h-5 w-5 text-red-500"/>,`${snapshot.criticalIncidents} críticos`)}{kpi('Veículos disponíveis',snapshot.availableVehicles,<Car className="h-5 w-5 text-emerald-500"/>,`${snapshot.rentedVehicles} alugados • ${snapshot.maintenanceVehicles} manutenção`)}{kpi('Usuários disponíveis',snapshot.usersAvailable,<Users className="h-5 w-5 text-violet-500"/>,`${snapshot.usersOverloaded} sobrecarregados`)}</div>
      <section className="rounded-xl border bg-white p-5"><div className="mb-4 flex items-center gap-2"><Zap className="h-5 w-5 text-amber-500"/><h2 className="font-semibold text-slate-900">O que precisa ser feito agora</h2></div>{snapshot.topPriorityActions.length===0?<p className="text-sm text-slate-500">Nenhuma ação crítica pendente.</p>:<div className="space-y-3">{snapshot.topPriorityActions.map(action=><div key={action.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded bg-slate-900 px-2 py-1 text-xs font-bold text-white">{action.priority}</span><h3 className="font-medium text-slate-900">{action.title}</h3></div><p className="mt-1 text-sm text-slate-600">{action.reason}</p><p className="mt-1 text-xs text-slate-500">{action.recommendation}</p></div>{action.quickActionType&&['START_TASK','UNBLOCK_TASK','RESOLVE_INCIDENT'].includes(action.quickActionType)&&<button disabled={busy===action.id} onClick={()=>void runAction(action)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{busy===action.id?'Executando...':'Executar ação'}</button>}</div>)}</div>}</section>
      <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold text-slate-900">Gargalos ativos</h2>{snapshot.topBottlenecks.length===0?<p className="text-sm text-slate-500">Nenhum gargalo crítico detectado.</p>:<div className="space-y-2">{snapshot.topBottlenecks.map(item=><div key={item.id} className="rounded-lg bg-orange-50 p-3"><div className="text-sm font-medium text-orange-900">{item.title}</div><div className="mt-1 text-xs text-orange-700">{item.description}</div></div>)}</div>}</section><section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold text-slate-900">Riscos prioritários</h2>{snapshot.topRisks.length===0?<p className="text-sm text-slate-500">Nenhum risco crítico detectado.</p>:<div className="space-y-2">{snapshot.topRisks.map(item=><div key={item.id} className="rounded-lg bg-red-50 p-3"><div className="flex justify-between gap-2"><span className="text-sm font-medium text-red-900">{item.title}</span><span className="text-xs font-bold text-red-700">{item.riskScore}</span></div><div className="mt-1 text-xs text-red-700">{item.recommendedAction}</div></div>)}</div>}</section></div>
      <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold text-slate-900">Recomendações</h2>{snapshot.recommendations.length===0?<p className="text-sm text-slate-500">Sem recomendações extraordinárias neste snapshot.</p>:<div className="grid gap-3 md:grid-cols-2">{snapshot.recommendations.map(item=><div key={item.id} className="rounded-lg border p-3"><div className="text-sm font-medium text-slate-900">{item.title}</div><p className="mt-1 text-xs text-slate-600">{item.description}</p><p className="mt-2 text-xs font-medium text-blue-700">{item.recommendedAction}</p></div>)}</div>}</section>
    </>}
  </div>;
};
