import React, { useEffect, useMemo, useState } from 'react';
import { AttachmentClient } from '../../api/attachmentClient';
import { ContractClient } from '../../api/contractClient';
import { DriverClient } from '../../api/driverClient';
import { TrafficTicketClient, type TrafficTicketDetails, type TrafficTicketDriverIndication, type TrafficTicketFinancialCategory } from '../../api/trafficTicketClient';
import { VehicleClient } from '../../api/vehicleClient';
import type { Contract, Driver, Vehicle } from '../../types/entities';
import { TicketResponsibility, TicketStatus, TrafficTicketDriverIndicationStatus } from '../../types/enums';
import { AttachmentList } from '../documents/AttachmentList';
import { Badge, Button, Card, Input, ModalContainer, Select } from '../ui';
import { AlertTriangle, CheckCircle2, FileText, ShieldAlert } from 'lucide-react';
import { formatCurrencyBRL } from '../../shared/utils/currency';

interface TrafficTicketDetailsModalProps {isOpen:boolean;onClose:()=>void;ticketId:string|null;onRefresh:()=>void;companyId?:string;}
const INDICATION_LABELS:Record<TrafficTicketDriverIndicationStatus,string>={PENDING:'Pendente',COMMUNICATED:'Comunicado',DOCUMENTS_SENT:'Documentos enviados',SIGNED:'Documentos assinados',INDICATED:'Indicado',COMPLETED:'Concluído',APPEAL:'Recurso',CANCELLED:'Cancelado'};
const NEXT_INDICATION:Partial<Record<TrafficTicketDriverIndicationStatus,TrafficTicketDriverIndicationStatus>>={PENDING:TrafficTicketDriverIndicationStatus.COMMUNICATED,COMMUNICATED:TrafficTicketDriverIndicationStatus.DOCUMENTS_SENT,DOCUMENTS_SENT:TrafficTicketDriverIndicationStatus.SIGNED,SIGNED:TrafficTicketDriverIndicationStatus.INDICATED,INDICATED:TrafficTicketDriverIndicationStatus.COMPLETED};
export const TrafficTicketDetailsModal:React.FC<TrafficTicketDetailsModalProps>=({isOpen,onClose,ticketId,onRefresh})=>{
  const [details,setDetails]=useState<TrafficTicketDetails|null>(null),[vehicle,setVehicle]=useState<Vehicle|null>(null),[driver,setDriver]=useState<Driver|null>(null),[contract,setContract]=useState<Contract|null>(null),[indication,setIndication]=useState<TrafficTicketDriverIndication|null>(null);
  const [drivers,setDrivers]=useState<Driver[]>([]),[categories,setCategories]=useState<TrafficTicketFinancialCategory[]>([]);
  const [loading,setLoading]=useState(false),[actionLoading,setActionLoading]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
  const [newResponsibility,setNewResponsibility]=useState<TicketResponsibility>(TicketResponsibility.DRIVER),[newDriverId,setNewDriverId]=useState(''),[incomeCategory,setIncomeCategory]=useState(''),[nicCategory,setNicCategory]=useState(''),[nicAmount,setNicAmount]=useState('');
  const [appealNotes,setAppealNotes]=useState(''),[cancelReason,setCancelReason]=useState(''),[uploading,setUploading]=useState(false),[attachmentVersion,setAttachmentVersion]=useState(0),[indicationDeadline,setIndicationDeadline]=useState(''),[indicationNotes,setIndicationNotes]=useState('');
  const income=useMemo(()=>categories.filter(c=>c.type==='INCOME'||c.type==='BOTH'),[categories]),expenses=useMemo(()=>categories.filter(c=>c.type==='EXPENSE'||c.type==='BOTH'),[categories]);

  const load=async()=>{if(!ticketId)return;setLoading(true);setError(null);try{
    const [d,allDrivers,allCategories,i]=await Promise.all([TrafficTicketClient.get(ticketId),DriverClient.list(),TrafficTicketClient.categories(),TrafficTicketClient.getDriverIndication(ticketId)]);
    setDetails(d);setIndication(i);setIndicationDeadline(i.indicationDeadline||'');setIndicationNotes(i.notes||'');setDrivers(allDrivers);setCategories(allCategories);setNewResponsibility(d.item.responsibility);setNewDriverId(d.item.driverId||'');
    const [v,dr,c]=await Promise.all([VehicleClient.get(d.item.vehicleId),d.item.driverId?DriverClient.get(d.item.driverId):Promise.resolve(null),d.item.contractId?ContractClient.get(d.item.contractId):Promise.resolve(null)]);
    setVehicle(v);setDriver(dr);setContract(c);
    const inc=allCategories.find(x=>x.type==='INCOME'||x.type==='BOTH'),exp=allCategories.find(x=>x.type==='EXPENSE'||x.type==='BOTH');if(inc)setIncomeCategory(current=>current||inc.id);if(exp)setNicCategory(current=>current||exp.id);
  }catch(err){setError(err instanceof Error?err.message:'Erro ao carregar multa.');setDetails(null);setIndication(null);}finally{setLoading(false);}};
  useEffect(()=>{if(isOpen&&ticketId)void load();else if(!isOpen){setDetails(null);setVehicle(null);setDriver(null);setContract(null);setIndication(null);setError(null);setSuccess(null);}},[isOpen,ticketId]);

  const run=async(task:()=>Promise<unknown>,message:string)=>{setActionLoading(true);setError(null);setSuccess(null);try{await task();setSuccess(message);await load();onRefresh();}catch(err){setError(err instanceof Error?err.message:'Operação falhou.');}finally{setActionLoading(false);}};
  const change=()=>run(()=>TrafficTicketClient.changeResponsibility(details!.item.id,{responsibility:newResponsibility,driverId:newResponsibility===TicketResponsibility.DRIVER?newDriverId||undefined:undefined,driverIncomeCategoryId:newResponsibility===TicketResponsibility.DRIVER?incomeCategory:undefined,nicExpenseCategoryId:newResponsibility===TicketResponsibility.UNIDENTIFIED?nicCategory:undefined,nicAmount:nicAmount?Number(nicAmount.replace(',','.')):undefined}),'Responsabilidade atualizada.');
  const advanceIndication=()=>{if(!details||!indication)return;const next=NEXT_INDICATION[indication.status];if(!next)return;void run(()=>TrafficTicketClient.updateDriverIndication(details.item.id,{status:next,indicationDeadline:indicationDeadline||undefined,notes:indicationNotes||undefined}),`Indicação atualizada: ${INDICATION_LABELS[next]}.`);};
  const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file||!details)return;setUploading(true);setError(null);try{await AttachmentClient.upload({entityType:'TrafficTicket' as any,entityId:details.item.id,documentType:'TRAFFIC_TICKET_NOTICE',fileName:file.name,mimeType:file.type,content:file});setAttachmentVersion(v=>v+1);setSuccess('Evidência anexada.');}catch(err){setError(err instanceof Error?err.message:'Falha no upload.');}finally{setUploading(false);event.target.value='';}};

  if(!isOpen)return null;
  const t=details?.item,f=details?.financial,nextIndication=indication?NEXT_INDICATION[indication.status]:undefined;
  return <ModalContainer isOpen={isOpen} onClose={onClose} title={t?`Multa ${t.autoNumber}`:'Detalhes da multa'} size="xl">
    {loading?<div className="p-10 text-center text-sm text-slate-500">Carregando...</div>:!t?<div className="p-4 text-rose-700">{error||'Multa não encontrada.'}</div>:<div className="space-y-4 text-xs">
      {error&&<div className="p-3 rounded-xl bg-rose-50 text-rose-700 flex gap-2"><AlertTriangle className="w-4 h-4"/>{error}</div>}
      {success&&<div className="p-3 rounded-xl bg-emerald-50 text-emerald-700 flex gap-2"><CheckCircle2 className="w-4 h-4"/>{success}</div>}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card className="p-4 space-y-2"><h4 className="font-bold">Infração</h4><p><b>Auto:</b> {t.autoNumber}</p><p><b>Órgão:</b> {t.organName}</p><p><b>Código:</b> {t.infractionCode}</p><p><b>Descrição:</b> {t.description}</p><p><b>Data:</b> {t.infractionDate}{t.infractionTime?` às ${t.infractionTime}`:''}</p><p><b>Vencimento:</b> {t.dueDate}</p><p><b>Valor original:</b> {formatCurrencyBRL(t.originalAmount)}</p>{t.discountedAmount!==undefined&&<p><b>Desconto informado:</b> {formatCurrencyBRL(t.discountedAmount)} até {t.discountDueDate} — {f?.discountAvailable?'disponível hoje':'não disponível hoje'}</p>}<p><b>Status:</b> <Badge variant={t.status===TicketStatus.CANCELLED?'danger':t.status===TicketStatus.PAID_BY_COMPANY?'success':'secondary'}>{t.status}</Badge></p></Card>
        <Card className="p-4 space-y-2"><h4 className="font-bold">Vínculos</h4><p><b>Veículo:</b> {vehicle?`${vehicle.plate} — ${vehicle.brand} ${vehicle.model}`:t.vehicleId}</p><p><b>Motorista:</b> {driver?.fullName||'Não identificado'}</p><p><b>Contrato:</b> {contract?.contractNumber||t.contractId||'Sem vínculo inequívoco'}</p><p><b>Responsabilidade:</b> {t.responsibility}</p>{t.responsibility===TicketResponsibility.UNIDENTIFIED&&<p className="text-amber-700 flex gap-2"><ShieldAlert className="w-4 h-4"/>NIC padrão: {formatCurrencyBRL(t.nicAmount??t.originalAmount)}</p>}</Card>
      </div>
      <Card className="p-4 space-y-3"><h4 className="font-bold">Financeiro server-authoritative</h4><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="border rounded-lg p-3"><b>AP-base</b><p>{f?.basePayable?`${f.basePayable.status} · ${formatCurrencyBRL(f.basePayable.originalAmount)}`:'Ausente'}</p><p className="text-slate-500">{t.payableId}</p></div><div className="border rounded-lg p-3"><b>AR motorista</b><p>{f?.receivable?`${f.receivable.status} · ${formatCurrencyBRL(f.receivable.originalAmount)}`:'Não aplicável'}</p><p className="text-slate-500">{t.receivableId}</p></div><div className="border rounded-lg p-3"><b>AP-NIC</b><p>{f?.nicPayable?`${f.nicPayable.status} · ${formatCurrencyBRL(f.nicPayable.originalAmount)}`:'Não aplicável'}</p><p className="text-slate-500">{t.nicPayableId}</p></div></div></Card>
      {indication&&<Card className="p-4 space-y-3"><div className="flex items-center justify-between gap-3"><h4 className="font-bold">Indicação do condutor</h4><Badge variant={indication.status===TrafficTicketDriverIndicationStatus.COMPLETED?'success':indication.status===TrafficTicketDriverIndicationStatus.CANCELLED?'danger':'secondary'}>{INDICATION_LABELS[indication.status]}</Badge></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label className="block mb-1 font-medium">Prazo para indicação</label><Input type="date" value={indicationDeadline} onChange={e=>setIndicationDeadline(e.target.value)} disabled={actionLoading||!nextIndication}/></div><div><label className="block mb-1 font-medium">Observações</label><Input value={indicationNotes} onChange={e=>setIndicationNotes(e.target.value)} placeholder="Observações do processo" disabled={actionLoading||!nextIndication}/></div></div>{t.responsibility!==TicketResponsibility.DRIVER&&indication.status===TrafficTicketDriverIndicationStatus.PENDING&&<p className="text-amber-700 flex gap-2"><ShieldAlert className="w-4 h-4"/>Identifique o motorista responsável antes de avançar a indicação.</p>}{nextIndication&&<Button onClick={advanceIndication} disabled={actionLoading||(t.responsibility!==TicketResponsibility.DRIVER&&nextIndication!==TrafficTicketDriverIndicationStatus.CANCELLED)}>Avançar para: {INDICATION_LABELS[nextIndication]}</Button>}</Card>}
      {t.status!==TicketStatus.CANCELLED&&<Card className="p-4 space-y-3"><h4 className="font-bold">Alterar responsabilidade</h4><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Select value={newResponsibility} onChange={e=>setNewResponsibility(e.target.value as TicketResponsibility)}>{Object.values(TicketResponsibility).map(v=><option key={v} value={v}>{v}</option>)}</Select>{newResponsibility===TicketResponsibility.DRIVER&&<><Select value={newDriverId} onChange={e=>setNewDriverId(e.target.value)}><option value="">Motorista</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.fullName}</option>)}</Select><Select value={incomeCategory} onChange={e=>setIncomeCategory(e.target.value)}><option value="">Categoria AR</option>{income.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></>}{newResponsibility===TicketResponsibility.UNIDENTIFIED&&<><Select value={nicCategory} onChange={e=>setNicCategory(e.target.value)}><option value="">Categoria NIC</option>{expenses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Input value={nicAmount} onChange={e=>setNicAmount(e.target.value)} placeholder="NIC opcional"/></>}</div><Button onClick={change} disabled={actionLoading}>Aplicar alteração</Button></Card>}
      <Card className="p-4 space-y-3"><h4 className="font-bold flex gap-2"><FileText className="w-4 h-4"/>Documentos e evidências</h4><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/><div key={attachmentVersion}><AttachmentList entityType="TrafficTicket" entityId={t.id}/></div></Card>
      {t.status!==TicketStatus.CANCELLED&&<Card className="p-4 space-y-3"><h4 className="font-bold">Recurso / cancelamento</h4><Input value={appealNotes} onChange={e=>setAppealNotes(e.target.value)} placeholder="Detalhes do recurso"/><Button variant="outline" disabled={actionLoading||!appealNotes.trim()} onClick={()=>run(()=>TrafficTicketClient.appeal(t.id,appealNotes),'Recurso registrado.')}>Registrar recurso</Button><Input value={cancelReason} onChange={e=>setCancelReason(e.target.value)} placeholder="Motivo do cancelamento"/><Button variant="outline" disabled={actionLoading||!cancelReason.trim()} onClick={()=>{if(window.confirm('Cancelar esta multa e as obrigações abertas relacionadas?'))void run(()=>TrafficTicketClient.cancel(t.id,cancelReason),'Multa cancelada.');}}>Cancelar multa</Button></Card>}
    </div>}
  </ModalContainer>;
};
